import type { LocaleCode } from "@/lib/i18nConfig";

export const customerDeviceLocaleOrder = [
  "de", "tr", "nl", "fr", "it", "ru", "es", "pt", "zh", "pl", "sq",
] as const satisfies readonly Exclude<LocaleCode, "en">[];

type CustomerDeviceTranslationTuple = readonly [
  string, string, string, string, string, string, string, string, string, string, string,
];

// Ordered as DE, TR, NL, FR, IT, RU, ES, PT, ZH, PL, SQ.
export const customerDeviceTranslations: Record<string, CustomerDeviceTranslationTuple> = {
  "· Trusted until": ["· Vertraut bis", "· Şu tarihe kadar güvenilir", "· Vertrouwd tot", "· Approuvé jusqu’au", "· Attendibile fino al", "· Доверено до", "· De confianza hasta", "· De confiança até", "· 信任至", "· Zaufane do", "· E besuar deri më"],
  "6-digit security code": ["6-stelliger Sicherheitscode", "6 haneli güvenlik kodu", "Beveiligingscode van 6 cijfers", "Code de sécurité à 6 chiffres", "Codice di sicurezza a 6 cifre", "6-значный код безопасности", "Código de seguridad de 6 dígitos", "Código de segurança de 6 dígitos", "6 位安全码", "6-cyfrowy kod bezpieczeństwa", "Kod sigurie me 6 shifra"],
  "Check your e-mail": ["Prüfen Sie Ihre E-Mail", "E-postanızı kontrol edin", "Controleer je e-mail", "Vérifiez votre e-mail", "Controlla la tua e-mail", "Проверьте электронную почту", "Revisa tu correo electrónico", "Verifique o seu e-mail", "请查看您的电子邮件", "Sprawdź swoją pocztę e-mail", "Kontrolloni e-mailin tuaj"],
  "Current": ["Aktuell", "Mevcut", "Huidig", "Actuel", "Attuale", "Текущее", "Actual", "Atual", "当前", "Bieżące", "Aktuale"],
  "Last used": ["Zuletzt verwendet", "Son kullanım", "Laatst gebruikt", "Dernière utilisation", "Ultimo utilizzo", "Последнее использование", "Último uso", "Última utilização", "上次使用", "Ostatnio używane", "Përdorur së fundi"],
  "Loading trusted devices...": ["Vertrauenswürdige Geräte werden geladen...", "Güvenilir cihazlar yükleniyor...", "Vertrouwde apparaten laden...", "Chargement des appareils approuvés...", "Caricamento dei dispositivi attendibili...", "Загрузка доверенных устройств...", "Cargando dispositivos de confianza...", "A carregar dispositivos de confiança...", "正在加载可信设备...", "Ładowanie zaufanych urządzeń...", "Po ngarkohen pajisjet e besuara..."],
  "New device protection": ["Schutz für neue Geräte", "Yeni cihaz koruması", "Beveiliging voor nieuwe apparaten", "Protection des nouveaux appareils", "Protezione dei nuovi dispositivi", "Защита новых устройств", "Protección para nuevos dispositivos", "Proteção de novos dispositivos", "新设备保护", "Ochrona nowych urządzeń", "Mbrojtja e pajisjeve të reja"],
  "New devices require an e-mail security code. Devices you explicitly trust can sign in for 30 days without another code.": ["Neue Geräte benötigen einen Sicherheitscode per E-Mail. Geräte, denen Sie ausdrücklich vertrauen, können sich 30 Tage lang ohne weiteren Code anmelden.", "Yeni cihazlarda e-posta güvenlik kodu gerekir. Açıkça güvendiğiniz cihazlar 30 gün boyunca başka bir kod olmadan giriş yapabilir.", "Nieuwe apparaten vereisen een beveiligingscode per e-mail. Apparaten die je expliciet vertrouwt, kunnen 30 dagen zonder extra code inloggen.", "Les nouveaux appareils nécessitent un code de sécurité envoyé par e-mail. Les appareils que vous approuvez explicitement peuvent se connecter pendant 30 jours sans autre code.", "I nuovi dispositivi richiedono un codice di sicurezza via e-mail. I dispositivi considerati esplicitamente attendibili possono accedere per 30 giorni senza un altro codice.", "Для новых устройств требуется код безопасности из электронной почты. Устройства, которым вы явно доверяете, могут входить в систему в течение 30 дней без повторного кода.", "Los nuevos dispositivos requieren un código de seguridad por correo electrónico. Los dispositivos que marques expresamente como de confianza podrán iniciar sesión durante 30 días sin otro código.", "Os novos dispositivos requerem um código de segurança por e-mail. Os dispositivos em que confiar explicitamente podem iniciar sessão durante 30 dias sem outro código.", "新设备需要电子邮件安全码。您明确设为可信的设备可在 30 天内无需再次输入代码即可登录。", "Nowe urządzenia wymagają kodu bezpieczeństwa wysłanego e-mailem. Urządzenia oznaczone przez Ciebie jako zaufane mogą logować się przez 30 dni bez kolejnego kodu.", "Pajisjet e reja kërkojnë një kod sigurie me e-mail. Pajisjet që i shënoni qartë si të besuara mund të identifikohen për 30 ditë pa një kod tjetër."],
  "No trusted devices are saved. You can select “Trust this device for 30 days” the next time you verify a login.": ["Es sind keine vertrauenswürdigen Geräte gespeichert. Bei der nächsten Anmeldebestätigung können Sie „Diesem Gerät 30 Tage vertrauen“ auswählen.", "Kayıtlı güvenilir cihaz yok. Bir sonraki giriş doğrulamanızda “Bu cihaza 30 gün güven” seçeneğini işaretleyebilirsiniz.", "Er zijn geen vertrouwde apparaten opgeslagen. Bij je volgende aanmeldverificatie kun je ‘Dit apparaat 30 dagen vertrouwen’ selecteren.", "Aucun appareil approuvé n’est enregistré. Lors de votre prochaine vérification de connexion, vous pourrez sélectionner « Faire confiance à cet appareil pendant 30 jours ».", "Non sono stati salvati dispositivi attendibili. Alla prossima verifica dell’accesso potrai selezionare “Considera attendibile questo dispositivo per 30 giorni”.", "Доверенные устройства не сохранены. При следующем подтверждении входа можно выбрать «Доверять этому устройству 30 дней».", "No hay dispositivos de confianza guardados. La próxima vez que verifiques un inicio de sesión podrás seleccionar «Confiar en este dispositivo durante 30 días».", "Não existem dispositivos de confiança guardados. Na próxima verificação de início de sessão, pode selecionar «Confiar neste dispositivo durante 30 dias».", "尚未保存任何可信设备。下次验证登录时，您可以选择“信任此设备 30 天”。", "Nie zapisano żadnych zaufanych urządzeń. Przy następnej weryfikacji logowania możesz wybrać opcję „Ufaj temu urządzeniu przez 30 dni”.", "Nuk është ruajtur asnjë pajisje e besuar. Herën tjetër që verifikoni një hyrje, mund të zgjidhni “Besoji kësaj pajisjeje për 30 ditë”."],
  "Resend code": ["Code erneut senden", "Kodu yeniden gönder", "Code opnieuw verzenden", "Renvoyer le code", "Reinvia il codice", "Отправить код повторно", "Reenviar código", "Reenviar código", "重新发送代码", "Wyślij kod ponownie", "Ridërgo kodin"],
  "Revoke": ["Widerrufen", "Güveni kaldır", "Intrekken", "Révoquer", "Revoca", "Отозвать", "Revocar", "Revogar", "撤销信任", "Cofnij zaufanie", "Revoko"],
  "Revoke all other devices": ["Allen anderen Geräten das Vertrauen entziehen", "Diğer tüm cihazların güvenini kaldır", "Alle andere apparaten intrekken", "Révoquer tous les autres appareils", "Revoca tutti gli altri dispositivi", "Отозвать доверие ко всем остальным устройствам", "Revocar todos los demás dispositivos", "Revogar todos os outros dispositivos", "撤销对所有其他设备的信任", "Cofnij zaufanie do wszystkich pozostałych urządzeń", "Revoko të gjitha pajisjet e tjera"],
  "Revoking a saved device blocks its MG AutoTech customer-data access. If you suspect account theft, reset your password too.": ["Wenn Sie einem gespeicherten Gerät das Vertrauen entziehen, wird dessen Zugriff auf MG AutoTech-Kundendaten gesperrt. Wenn Sie vermuten, dass Ihr Konto übernommen wurde, setzen Sie zusätzlich Ihr Passwort zurück.", "Kayıtlı bir cihazın güvenini kaldırmak, cihazın MG AutoTech müşteri verilerine erişimini engeller. Hesabınızın ele geçirildiğinden şüpheleniyorsanız parolanızı da sıfırlayın.", "Als je een opgeslagen apparaat intrekt, wordt de toegang tot MG AutoTech-klantgegevens geblokkeerd. Als je vermoedt dat je account is overgenomen, stel dan ook je wachtwoord opnieuw in.", "La révocation d’un appareil enregistré bloque son accès aux données client MG AutoTech. Si vous pensez que votre compte a été compromis, réinitialisez également votre mot de passe.", "La revoca di un dispositivo salvato ne blocca l’accesso ai dati cliente MG AutoTech. Se sospetti che il tuo account sia stato compromesso, reimposta anche la password.", "Отзыв сохранённого устройства блокирует его доступ к клиентским данным MG AutoTech. Если вы подозреваете взлом аккаунта, также сбросьте пароль.", "Revocar un dispositivo guardado bloque su acceso a los datos de cliente de MG AutoTech. Si sospechas que tu cuenta está comprometida, restablece también la contraseña.", "Revogar um dispositivo guardado bloqueia o acesso deste aos dados de cliente da MG AutoTech. Se suspeitar que a conta foi comprometida, reponha também a palavra-passe.", "撤销已保存设备的信任后，该设备将无法访问 MG AutoTech 客户数据。如果您怀疑账户被盗，也请重置密码。", "Cofnięcie zaufania do zapisanego urządzenia blokuje jego dostęp do danych klientów MG AutoTech. Jeśli podejrzewasz przejęcie konta, zresetuj również hasło.", "Revokimi i një pajisjeje të ruajtur bllokon qasjen e saj në të dhënat e klientëve të MG AutoTech. Nëse dyshoni se llogaria është komprometuar, rivendosni edhe fjalëkalimin."],
  "Security & trusted devices": ["Sicherheit & vertrauenswürdige Geräte", "Güvenlik ve güvenilir cihazlar", "Beveiliging en vertrouwde apparaten", "Sécurité et appareils approuvés", "Sicurezza e dispositivi attendibili", "Безопасность и доверенные устройства", "Seguridad y dispositivos de confianza", "Segurança e dispositivos de confiança", "安全与可信设备", "Bezpieczeństwo i zaufane urządzenia", "Siguria dhe pajisjet e besuara"],
  "Security code": ["Sicherheitscode", "Güvenlik kodu", "Beveiligingscode", "Code de sécurité", "Codice di sicurezza", "Код безопасности", "Código de seguridad", "Código de segurança", "安全码", "Kod bezpieczeństwa", "Kodi i sigurisë"],
  "Trust this device for 30 days": ["Diesem Gerät 30 Tage vertrauen", "Bu cihaza 30 gün güven", "Dit apparaat 30 dagen vertrouwen", "Faire confiance à cet appareil pendant 30 jours", "Considera attendibile questo dispositivo per 30 giorni", "Доверять этому устройству 30 дней", "Confiar en este dispositivo durante 30 días", "Confiar neste dispositivo durante 30 dias", "信任此设备 30 天", "Ufaj temu urządzeniu przez 30 dni", "Besoji kësaj pajisjeje për 30 ditë"],
  "Use a different account": ["Anderes Konto verwenden", "Farklı bir hesap kullan", "Een ander account gebruiken", "Utiliser un autre compte", "Usa un altro account", "Использовать другой аккаунт", "Usar otra cuenta", "Utilizar outra conta", "使用其他账户", "Użyj innego konta", "Përdor një llogari tjetër"],
  "Use this only on a private device you control.": ["Verwenden Sie diese Option nur auf einem privaten Gerät, das Sie selbst kontrollieren.", "Bunu yalnızca kontrolünüzdeki kişisel bir cihazda kullanın.", "Gebruik dit alleen op een privéapparaat dat je zelf beheert.", "N’utilisez cette option que sur un appareil privé que vous contrôlez.", "Usa questa opzione solo su un dispositivo privato sotto il tuo controllo.", "Используйте эту функцию только на личном устройстве, которое вы контролируете.", "Usa esta opción solo en un dispositivo privado que controles.", "Utilize esta opção apenas num dispositivo privado que controle.", "仅在您掌控的私人设备上使用此选项。", "Używaj tej opcji tylko na prywatnym urządzeniu, które kontrolujesz.", "Përdoreni këtë vetëm në një pajisje private që e kontrolloni."],
  "Verify and continue": ["Bestätigen und fortfahren", "Doğrula ve devam et", "Verifiëren en doorgaan", "Vérifier et continuer", "Verifica e continua", "Подтвердить и продолжить", "Verificar y continuar", "Verificar e continuar", "验证并继续", "Zweryfikuj i kontynuuj", "Verifiko dhe vazhdo"],
  "Verifying...": ["Wird überprüft...", "Doğrulanıyor...", "Verifiëren...", "Vérification...", "Verifica in corso...", "Проверка...", "Verificando...", "A verificar...", "正在验证...", "Weryfikowanie...", "Po verifikohet..."],
  "Your security e-mail is being prepared. The code field will be available after it is accepted for sending.": ["Ihre Sicherheits-E-Mail wird vorbereitet. Das Codefeld wird verfügbar, sobald der Versand bestätigt wurde.", "Güvenlik e-postanız hazırlanıyor. Gönderim kabul edildikten sonra kod alanı açılacak.", "Je beveiligingsmail wordt voorbereid. Het codeveld wordt beschikbaar nadat de verzending is geaccepteerd.", "Votre e-mail de sécurité est en cours de préparation. Le champ du code sera disponible une fois l’envoi accepté.", "La tua e-mail di sicurezza è in preparazione. Il campo del codice sarà disponibile dopo l’accettazione dell’invio.", "Письмо с кодом безопасности готовится. Поле для ввода кода станет доступно после принятия отправки.", "Tu correo electrónico de seguridad se está preparando. El campo del código estará disponible cuando se acepte el envío.", "O seu e-mail de segurança está a ser preparado. O campo do código ficará disponível quando o envio for aceite.", "正在准备您的安全电子邮件。发送请求获接受后，代码输入框将可用。", "Trwa przygotowywanie wiadomości e-mail z kodem bezpieczeństwa. Pole kodu będzie dostępne po przyjęciu wiadomości do wysłania.", "E-maili juaj i sigurisë po përgatitet. Fusha e kodit do të jetë e disponueshme pasi dërgimi të pranohet."],
  "Too many security-code requests were made. Wait for the timer before trying again.": ["Es wurden zu viele Sicherheitscodes angefordert. Warten Sie bis zum Ablauf des Timers, bevor Sie es erneut versuchen.", "Çok fazla güvenlik kodu istendi. Yeniden denemeden önce sayacın bitmesini bekleyin.", "Er zijn te veel beveiligingscodes aangevraagd. Wacht tot de timer is afgelopen voordat je het opnieuw probeert.", "Trop de codes de sécurité ont été demandés. Attendez la fin du compte à rebours avant de réessayer.", "Sono stati richiesti troppi codici di sicurezza. Attendi la fine del timer prima di riprovare.", "Запрошено слишком много кодов безопасности. Дождитесь окончания таймера перед повторной попыткой.", "Se han solicitado demasiados códigos de seguridad. Espera a que termine el temporizador antes de volver a intentarlo.", "Foram pedidos demasiados códigos de segurança. Aguarde que o temporizador termine antes de tentar novamente.", "安全码请求次数过多。请等待计时结束后再试。", "Wysłano zbyt wiele próśb o kod bezpieczeństwa. Przed ponowną próbą poczekaj na zakończenie odliczania.", "Janë bërë shumë kërkesa për kod sigurie. Prisni që kohëmatësi të përfundojë përpara se të provoni përsëri."],
  "A 6-digit security code was accepted for sending to": ["Ein 6-stelliger Sicherheitscode wurde zum Versand an folgende Adresse angenommen:", "6 haneli güvenlik kodunun şu adrese gönderimi kabul edildi:", "Een beveiligingscode van 6 cijfers is geaccepteerd voor verzending naar:", "Un code de sécurité à 6 chiffres a été accepté pour envoi à :", "Un codice di sicurezza a 6 cifre è stato accettato per l’invio a:", "6-значный код безопасности принят к отправке на адрес:", "Se aceptó el envío de un código de seguridad de 6 dígitos a:", "Foi aceite o envio de um código de segurança de 6 dígitos para:", "已接受向以下地址发送 6 位安全码：", "6-cyfrowy kod bezpieczeństwa został przyjęty do wysłania na adres:", "Një kod sigurie me 6 shifra u pranua për t’u dërguar te:"],
  "A 6-digit security code was already sent to": ["Ein 6-stelliger Sicherheitscode wurde bereits an folgende Adresse gesendet:", "6 haneli güvenlik kodu zaten şu adrese gönderildi:", "Een beveiligingscode van 6 cijfers is al verzonden naar:", "Un code de sécurité à 6 chiffres a déjà été envoyé à :", "Un codice di sicurezza a 6 cifre è già stato inviato a:", "6-значный код безопасности уже отправлен на адрес:", "Ya se envió un código de seguridad de 6 dígitos a:", "Já foi enviado um código de segurança de 6 dígitos para:", "已向以下地址发送 6 位安全码：", "6-cyfrowy kod bezpieczeństwa został już wysłany na adres:", "Një kod sigurie me 6 shifra është dërguar tashmë te:"],
  "We are checking whether this device is already trusted.": ["Wir prüfen, ob dieses Gerät bereits vertrauenswürdig ist.", "Bu cihazın zaten güvenilir olup olmadığını kontrol ediyoruz.", "We controleren of dit apparaat al wordt vertrouwd.", "Nous vérifions si cet appareil est déjà approuvé.", "Stiamo verificando se questo dispositivo è già attendibile.", "Проверяем, является ли это устройство уже доверенным.", "Estamos comprobando si este dispositivo ya es de confianza.", "Estamos a verificar se este dispositivo já é de confiança.", "正在检查此设备是否已受信任。", "Sprawdzamy, czy to urządzenie jest już zaufane.", "Po kontrollojmë nëse kjo pajisje është tashmë e besuar."],
  "attempts left.": ["Versuche übrig.", "deneme kaldı.", "pogingen over.", "tentatives restantes.", "tentativi rimasti.", "попыток осталось.", "intentos restantes.", "tentativas restantes.", "次尝试机会。", "prób pozostało.", "përpjekje të mbetura."],
  "Resend code in": ["Code erneut senden in", "Kodu yeniden göndermeye kalan süre:", "Code opnieuw verzenden over", "Renvoyer le code dans", "Reinvia il codice tra", "Повторная отправка кода через", "Reenviar código en", "Reenviar código dentro de", "距离重新发送代码还需", "Ponowne wysłanie kodu za", "Ridërgo kodin pas"],
  "Try again in": ["Erneut versuchen in", "Yeniden denemeye kalan süre:", "Opnieuw proberen over", "Réessayer dans", "Riprova tra", "Повторная попытка через", "Volver a intentarlo en", "Tentar novamente dentro de", "距离重试还需", "Spróbuj ponownie za", "Provo përsëri pas"],
  "Try again": ["Erneut versuchen", "Tekrar deneyin", "Probeer het opnieuw", "Réessayez", "Riprova", "Попробовать ещё раз", "Inténtalo de nuevo", "Tente novamente", "请重试", "Spróbuj ponownie", "Provoni përsëri"],
};
