import type { LocaleCode } from "@/lib/i18nConfig";

export type SeoUiCopy = {
  online: string;
  workflowTitle: string;
  workflowText: string;
  brandsText: string;
  company: string;
  platform: string;
  legal: string;
  contact: string;
  about: string;
  tools: string;
  secureAccount: string;
  readyTitle: string;
  rights: string;
};

export const seoUiCopy: Record<LocaleCode, SeoUiCopy> = {
  en: {
    online: "Online",
    workflowTitle: "Controlled file-service workflow",
    workflowText: "One request connects the vehicle data, original file, technical review, delivery and revision history.",
    brandsText: "Vehicle and ECU support is confirmed from the submitted file, hardware/software data and read method.",
    company: "Company",
    platform: "Platform",
    legal: "Legal",
    contact: "Contact",
    about: "About MG AutoTech",
    tools: "Workshop tools",
    secureAccount: "Secure customer account and private file delivery.",
    readyTitle: "Ready to submit a file?",
    rights: "All rights reserved.",
  },
  de: {
    online: "Online",
    workflowTitle: "Kontrollierter Dateiservice-Ablauf",
    workflowText: "Eine Anfrage verbindet Fahrzeugdaten, Originaldatei, technische Prüfung, Auslieferung und Revisionsverlauf.",
    brandsText: "Fahrzeug- und ECU-Unterstützung wird anhand der Datei, HW/SW-Daten und Lesemethode geprüft.",
    company: "Unternehmen",
    platform: "Plattform",
    legal: "Rechtliches",
    contact: "Kontakt",
    about: "Über MG AutoTech",
    tools: "Werkstatt-Tools",
    secureAccount: "Sicheres Kundenkonto und private Dateilieferung.",
    readyTitle: "Datei zur Bearbeitung senden?",
    rights: "Alle Rechte vorbehalten.",
  },
  nl: {
    online: "Online",
    workflowTitle: "Gecontroleerd bestandsserviceproces",
    workflowText: "Eén aanvraag verbindt voertuigdata, origineel bestand, technische controle, levering en revisiehistorie.",
    brandsText: "Voertuig- en ECU-ondersteuning wordt gecontroleerd aan de hand van bestand, HW/SW-data en leesmethode.",
    company: "Bedrijf",
    platform: "Platform",
    legal: "Juridisch",
    contact: "Contact",
    about: "Over MG AutoTech",
    tools: "Werkplaatstools",
    secureAccount: "Veilig klantaccount en privébestandslevering.",
    readyTitle: "Klaar om een bestand te versturen?",
    rights: "Alle rechten voorbehouden.",
  },
  fr: {
    online: "En ligne",
    workflowTitle: "Processus contrôlé de service de fichiers",
    workflowText: "Une demande relie les données véhicule, le fichier d'origine, le contrôle technique, la livraison et les révisions.",
    brandsText: "La compatibilité véhicule et ECU est vérifiée à partir du fichier, des données HW/SW et de la méthode de lecture.",
    company: "Entreprise",
    platform: "Plateforme",
    legal: "Mentions légales",
    contact: "Contact",
    about: "À propos de MG AutoTech",
    tools: "Outils atelier",
    secureAccount: "Compte client sécurisé et livraison privée des fichiers.",
    readyTitle: "Prêt à envoyer un fichier ?",
    rights: "Tous droits réservés.",
  },
  it: {
    online: "Online",
    workflowTitle: "Processo controllato di servizio file",
    workflowText: "Una richiesta collega dati veicolo, file originale, controllo tecnico, consegna e cronologia revisioni.",
    brandsText: "Il supporto di veicolo ed ECU viene verificato tramite file, dati HW/SW e metodo di lettura.",
    company: "Azienda",
    platform: "Piattaforma",
    legal: "Note legali",
    contact: "Contatti",
    about: "Chi è MG AutoTech",
    tools: "Strumenti officina",
    secureAccount: "Account cliente sicuro e consegna privata dei file.",
    readyTitle: "Pronto a inviare un file?",
    rights: "Tutti i diritti riservati.",
  },
  ru: {
    online: "Онлайн",
    workflowTitle: "Контролируемый процесс обработки файлов",
    workflowText: "Одна заявка объединяет данные автомобиля, исходный файл, техническую проверку, выдачу и историю доработок.",
    brandsText: "Поддержка автомобиля и ECU подтверждается по файлу, данным HW/SW и методу чтения.",
    company: "Компания",
    platform: "Платформа",
    legal: "Правовая информация",
    contact: "Контакты",
    about: "О MG AutoTech",
    tools: "Инструменты для сервиса",
    secureAccount: "Защищённый кабинет и конфиденциальная выдача файлов.",
    readyTitle: "Готовы отправить файл?",
    rights: "Все права защищены.",
  },
  es: {
    online: "En línea",
    workflowTitle: "Proceso controlado de servicio de archivos",
    workflowText: "Una solicitud conecta los datos del vehículo, archivo original, revisión técnica, entrega e historial de revisiones.",
    brandsText: "La compatibilidad del vehículo y la ECU se confirma mediante el archivo, los datos HW/SW y el método de lectura.",
    company: "Empresa",
    platform: "Plataforma",
    legal: "Información legal",
    contact: "Contacto",
    about: "Acerca de MG AutoTech",
    tools: "Herramientas de taller",
    secureAccount: "Cuenta segura y entrega privada de archivos.",
    readyTitle: "¿Listo para enviar un archivo?",
    rights: "Todos los derechos reservados.",
  },
  tr: {
    online: "Çevrimiçi",
    workflowTitle: "Kontrollü dosya servis süreci",
    workflowText: "Tek bir talep; araç bilgilerini, orijinal dosyayı, teknik kontrolü, teslimatı ve revizyon geçmişini bir arada tutar.",
    brandsText: "Araç ve ECU desteği; gönderilen dosya, HW/SW bilgisi ve okuma yöntemine göre doğrulanır.",
    company: "Kurumsal",
    platform: "Platform",
    legal: "Yasal",
    contact: "İletişim",
    about: "MG AutoTech hakkında",
    tools: "Servis araçları",
    secureAccount: "Güvenli müşteri hesabı ve özel dosya teslimatı.",
    readyTitle: "Dosyanızı göndermeye hazır mısınız?",
    rights: "Tüm hakları saklıdır.",
  },
  pt: {
    online: "Online",
    workflowTitle: "Processo controlado de serviço de ficheiros",
    workflowText: "Um pedido reúne os dados do veículo, ficheiro original, verificação técnica, entrega e histórico de revisões.",
    brandsText: "O suporte do veículo e da ECU é confirmado pelo ficheiro, dados HW/SW e método de leitura.",
    company: "Empresa",
    platform: "Plataforma",
    legal: "Informação legal",
    contact: "Contacto",
    about: "Sobre a MG AutoTech",
    tools: "Ferramentas de oficina",
    secureAccount: "Conta de cliente segura e entrega privada de ficheiros.",
    readyTitle: "Pronto para enviar um ficheiro?",
    rights: "Todos os direitos reservados.",
  },
  zh: {
    online: "在线",
    workflowTitle: "受控的文件服务流程",
    workflowText: "一个订单集中管理车辆资料、原始文件、技术审核、文件交付和修改记录。",
    brandsText: "我们会根据上传文件、硬件/软件信息和读取方式确认车辆与 ECU 的支持情况。",
    company: "公司",
    platform: "平台",
    legal: "法律信息",
    contact: "联系我们",
    about: "关于 MG AutoTech",
    tools: "车间工具",
    secureAccount: "安全的客户账户与私密文件交付。",
    readyTitle: "准备提交文件了吗？",
    rights: "保留所有权利。",
  },
  pl: {
    online: "Online",
    workflowTitle: "Kontrolowany proces obsługi plików",
    workflowText: "Jedno zlecenie łączy dane pojazdu, plik oryginalny, kontrolę techniczną, dostawę i historię poprawek.",
    brandsText: "Obsługa pojazdu i ECU jest potwierdzana na podstawie pliku, danych HW/SW i metody odczytu.",
    company: "Firma",
    platform: "Platforma",
    legal: "Informacje prawne",
    contact: "Kontakt",
    about: "O MG AutoTech",
    tools: "Narzędzia warsztatowe",
    secureAccount: "Bezpieczne konto klienta i prywatna dostawa plików.",
    readyTitle: "Chcesz wysłać plik?",
    rights: "Wszelkie prawa zastrzeżone.",
  },
  sq: {
    online: "Online",
    workflowTitle: "Proces i kontrolluar i shërbimit të skedarëve",
    workflowText: "Një kërkesë lidh të dhënat e automjetit, skedarin origjinal, kontrollin teknik, dorëzimin dhe historikun e revizioneve.",
    brandsText: "Mbështetja e automjetit dhe ECU-së konfirmohet nga file-i, të dhënat HW/SW dhe metoda e leximit.",
    company: "Kompania",
    platform: "Platforma",
    legal: "Informacion ligjor",
    contact: "Kontakt",
    about: "Rreth MG AutoTech",
    tools: "Mjete për servis",
    secureAccount: "Llogari e sigurt klienti dhe dorëzim privat i file-ve.",
    readyTitle: "Gati për të dërguar një file?",
    rights: "Të gjitha të drejtat e rezervuara.",
  },
};
