import type { PublicVehicleOption } from "@/lib/vehicleControl/types";

// Customer-safe bootstrap generated from the canonical JSON fallback catalog.
export const publicVehicleBrandSeed = [
  { id: "acura", name: "Acura" },
  { id: "alfa-romeo", name: "Alfa Romeo" },
  { id: "alpina", name: "Alpina" },
  { id: "alpine", name: "Alpine" },
  { id: "aston-martin", name: "Aston Martin" },
  { id: "audi", name: "Audi" },
  { id: "bentley", name: "Bentley" },
  { id: "bmw", name: "BMW" },
  { id: "bugatti", name: "Bugatti" },
  { id: "buick", name: "Buick" },
  { id: "cadillac", name: "Cadillac" },
  { id: "case", name: "Case" },
  { id: "caterpillar", name: "Caterpillar" },
  { id: "challenger", name: "Challenger" },
  { id: "changan", name: "Changan" },
  { id: "chery", name: "Chery" },
  { id: "chevrolet", name: "Chevrolet" },
  { id: "chrysler", name: "Chrysler" },
  { id: "citroen", name: "Citroën" },
  { id: "claas", name: "Claas" },
  { id: "cupra", name: "Cupra" },
  { id: "dacia", name: "Dacia" },
  { id: "daewoo", name: "Daewoo" },
  { id: "daf", name: "DAF" },
  { id: "dallara", name: "Dallara" },
  { id: "deutz-fahr", name: "Deutz Fahr" },
  { id: "dodge", name: "Dodge" },
  { id: "ds", name: "DS" },
  { id: "fendt", name: "Fendt" },
  { id: "ferrari", name: "Ferrari" },
  { id: "fiat", name: "Fiat" },
  { id: "ford", name: "Ford" },
  { id: "geely", name: "Geely" },
  { id: "genesis", name: "Genesis" },
  { id: "gmc", name: "GMC" },
  { id: "holden", name: "Holden" },
  { id: "honda", name: "Honda" },
  { id: "hummer", name: "Hummer" },
  { id: "hyundai", name: "Hyundai" },
  { id: "infiniti", name: "Infiniti" },
  { id: "isuzu", name: "Isuzu" },
  { id: "iveco", name: "Iveco" },
  { id: "jac", name: "Jac" },
  { id: "jaguar", name: "Jaguar" },
  { id: "jcb", name: "JCB" },
  { id: "jeep", name: "Jeep" },
  { id: "john-deere", name: "John Deere" },
  { id: "karsan", name: "Karsan" },
  { id: "kia", name: "Kia" },
  { id: "krone", name: "Krone" },
  { id: "ktm", name: "KTM" },
  { id: "lamborghini", name: "Lamborghini" },
  { id: "lamborghini-tractors", name: "Lamborghini Tractors" },
  { id: "lancia", name: "Lancia" },
  { id: "land-rover", name: "Land Rover" },
  { id: "lexus", name: "Lexus" },
  { id: "lincoln", name: "Lincoln" },
  { id: "lotus", name: "Lotus" },
  { id: "luxgen", name: "Luxgen" },
  { id: "lynk-and-co", name: "Lynk & Co" },
  { id: "mahindra", name: "Mahindra" },
  { id: "man", name: "MAN" },
  { id: "maserati", name: "Maserati" },
  { id: "massey-fergusson", name: "Massey Fergusson" },
  { id: "mazda", name: "Mazda" },
  { id: "mccormick", name: "McCormick" },
  { id: "mclaren", name: "McLaren" },
  { id: "mercedes-benz", name: "Mercedes-Benz" },
  { id: "mercedes-benz-trucks", name: "Mercedes-Benz Trucks" },
  { id: "mercury", name: "Mercury" },
  { id: "mg", name: "MG" },
  { id: "mini", name: "Mini" },
  { id: "mitsubishi", name: "Mitsubishi" },
  { id: "new-holland", name: "New Holland" },
  { id: "nissan", name: "Nissan" },
  { id: "oldsmobile", name: "Oldsmobile" },
  { id: "opel", name: "Opel" },
  { id: "peugeot", name: "Peugeot" },
  { id: "pontiac", name: "Pontiac" },
  { id: "porsche", name: "Porsche" },
  { id: "renault", name: "Renault" },
  { id: "renault-truck", name: "Renault truck" },
  { id: "roewe", name: "Roewe" },
  { id: "rolls-royce", name: "Rolls Royce" },
  { id: "rover", name: "Rover" },
  { id: "saab", name: "Saab" },
  { id: "saturn", name: "Saturn" },
  { id: "scania-trucks", name: "Scania trucks" },
  { id: "seat", name: "Seat" },
  { id: "skoda", name: "Skoda" },
  { id: "smart", name: "Smart" },
  { id: "ssangyong", name: "SsangYong" },
  { id: "steyr", name: "Steyr" },
  { id: "subaru", name: "Subaru" },
  { id: "suzuki", name: "Suzuki" },
  { id: "toyota", name: "Toyota" },
  { id: "valtra", name: "Valtra" },
  { id: "vauxhall", name: "Vauxhall" },
  { id: "volkswagen", name: "Volkswagen" },
  { id: "volvo", name: "Volvo" },
  { id: "volvo-trucks", name: "Volvo Trucks" },
  { id: "wey", name: "WEY" },
] satisfies PublicVehicleOption[];
