"use client";

import Link from "next/link";
import { useCallback, useEffect, useState } from "react";
import { ArrowLeft, Braces, CreditCard, Globe2, Loader2, Save, ShieldCheck, TriangleAlert } from "lucide-react";
import { supabase } from "@/lib/supabaseClient";
import { defaultWidgetSettings, widgetLanguageCodes, type WidgetLanguage, type WidgetSettings } from "@/lib/widget/types";

const names: Record<WidgetLanguage, string> = { de: "German", en: "English", tr: "Turkish", fr: "French", es: "Spanish", it: "Italian", nl: "Dutch", pl: "Polish", ro: "Romanian", pt: "Portuguese", ru: "Russian", ar: "Arabic" };

export default function AdminWidgetSettingsPage() {
  const [settings, setSettings] = useState<WidgetSettings>(defaultWidgetSettings);
  const [loading, setLoading] = useState(true); const [saving, setSaving] = useState(false); const [message, setMessage] = useState(""); const [setup, setSetup] = useState(false);
  const authFetch = useCallback(async (url: string, init?: RequestInit) => { const token = (await supabase.auth.getSession()).data.session?.access_token; if (!token) throw new Error("Unauthorized"); return fetch(url, { ...init, headers: { ...(init?.headers ?? {}), Authorization: `Bearer ${token}` } }); }, []);
  const load = useCallback(async () => { try { const response = await authFetch("/api/admin/widget-settings", { cache: "no-store" }); const data = await response.json(); if (response.status === 401 || response.status === 403) { window.location.href = "/login"; return; } if (!response.ok) { setSetup(Boolean(data.setupRequired)); throw new Error(data.error); } setSettings(data.settings); } catch (error) { if (error instanceof Error && error.message === "Unauthorized") { window.location.href = "/login"; return; } setMessage(error instanceof Error ? error.message : "Settings could not be loaded."); } finally { setLoading(false); } }, [authFetch]);
  useEffect(() => { void Promise.resolve().then(load); }, [load]);
  function set<K extends keyof WidgetSettings>(key: K, value: WidgetSettings[K]) { setSettings((current) => ({ ...current, [key]: value })); }
  function toggleLanguage(code: WidgetLanguage) { const next = settings.enabled_languages.includes(code) ? settings.enabled_languages.filter((item) => item !== code) : [...settings.enabled_languages, code]; if (next.length) set("enabled_languages", next); }
  async function save() { setSaving(true); setMessage(""); const response = await authFetch("/api/admin/widget-settings", { method: "PATCH", headers: { "Content-Type": "application/json" }, body: JSON.stringify(settings) }); const data = await response.json(); setSaving(false); if (!response.ok) { setMessage(data.error || "Settings could not be saved."); return; } setSettings(data.settings); setMessage("Global widget settings saved."); }
  if (loading) return <main className="flex min-h-screen items-center justify-center bg-[#050505] text-white"><Loader2 className="mr-3 h-6 w-6 animate-spin text-red-500" />Loading widget controls...</main>;
  return <main className="min-h-screen bg-[#050505] text-white"><header className="border-b border-white/10"><div className="mx-auto flex max-w-6xl items-center justify-between px-4 py-5"><div className="flex items-center gap-3"><Braces className="h-7 w-7 text-red-500" /><div><div className="text-xs font-black uppercase tracking-[0.18em] text-red-500">Admin control</div><h1 className="text-2xl font-black">Global Widget Settings</h1></div></div><Link href="/admin/widget-clients" className="rounded-lg border border-white/10 px-4 py-3 text-sm font-black"><ArrowLeft className="mr-2 inline h-4 w-4" />Widget clients</Link></div></header><section className="mx-auto max-w-6xl px-4 py-8">{message && <div className={`mb-6 border p-4 text-sm ${setup ? "border-amber-700/40 bg-amber-950/20 text-amber-200" : "border-red-800/40 bg-red-950/20 text-red-100"}`}>{message}{setup && <div className="mt-2 font-black">Run scripts/add-vehicle-widget-saas.sql in Supabase tomorrow.</div>}</div>}
    <div className="grid gap-8 lg:grid-cols-2"><Section title="General" icon={<Braces />}><Toggle label="Widget product enabled" checked={settings.widget_product_enabled} onChange={(v) => set("widget_product_enabled", v)} /><Toggle label="Public signup enabled" checked={settings.public_signup_enabled} onChange={(v) => set("public_signup_enabled", v)} /><Toggle label="Checkout enabled" checked={settings.checkout_enabled} onChange={(v) => set("checkout_enabled", v)} /><Toggle label="Live demo enabled" checked={settings.demo_enabled} onChange={(v) => set("demo_enabled", v)} /></Section>
    <Section title="Pricing" icon={<CreditCard />}><div className="grid gap-4 sm:grid-cols-2"><NumberField label="Monthly price" value={settings.monthly_price} onChange={(v) => set("monthly_price", v)} step="0.01" /><TextField label="Currency" value={settings.currency} onChange={(v) => set("currency", v.toLowerCase())} /></div><p className="mt-4 text-sm text-zinc-500">Checkout always uses this server-side price. The browser cannot override it.</p></Section>
    <Section title="Languages" icon={<Globe2 />}><label className="mb-4 block text-xs font-black uppercase text-zinc-500">Default language<select value={settings.default_language} onChange={(e) => set("default_language", e.target.value as WidgetLanguage)} className="mt-2 h-12 w-full rounded-lg border border-white/10 bg-black/30 px-3 text-sm font-bold">{settings.enabled_languages.map((code) => <option key={code} value={code}>{names[code]}</option>)}</select></label><div className="flex flex-wrap gap-2">{widgetLanguageCodes.map((code) => <button key={code} type="button" onClick={() => toggleLanguage(code)} className={`rounded-lg border px-3 py-2 text-xs font-black ${settings.enabled_languages.includes(code) ? "border-red-700 bg-red-950/30" : "border-white/10 text-zinc-600"}`}>{code.toUpperCase()} · {names[code]}</button>)}</div></Section>
    <Section title="Branding & security" icon={<ShieldCheck />}><Toggle label="Show MG AutoTech branding" checked={settings.show_mg_branding} onChange={(v) => set("show_mg_branding", v)} /><Toggle label="Require domain whitelist" checked={settings.require_domain_whitelist} onChange={(v) => set("require_domain_whitelist", v)} /><Toggle label="Usage logging enabled" checked={settings.usage_logging_enabled} onChange={(v) => set("usage_logging_enabled", v)} /><Toggle label="Script embed enabled" checked={settings.allow_script_embed} onChange={(v) => set("allow_script_embed", v)} /><Toggle label="Iframe embed enabled" checked={settings.allow_iframe_embed} onChange={(v) => set("allow_iframe_embed", v)} /><NumberField label="Default monthly usage limit" value={settings.default_monthly_usage_limit} onChange={(v) => set("default_monthly_usage_limit", v)} step="1" /></Section></div>
    <div className="mt-8 flex flex-col gap-4 border-t border-white/10 pt-6 sm:flex-row sm:items-center sm:justify-between"><div className="flex items-start gap-3 text-sm text-zinc-500"><TriangleAlert className="mt-0.5 h-5 w-5 text-amber-400" /><span>Turning off <strong className="text-white">Widget product enabled</strong> immediately blocks every public widget.</span></div><button onClick={save} disabled={saving || setup} className="flex h-12 items-center justify-center rounded-lg bg-[#b1121b] px-6 text-sm font-black disabled:opacity-40">{saving ? <Loader2 className="h-4 w-4 animate-spin" /> : <><Save className="mr-2 h-4 w-4" />Save global settings</>}</button></div>
  </section></main>;
}
function Section({ title, icon, children }: { title: string; icon: React.ReactNode; children: React.ReactNode }) { return <section className="border-t border-white/10 pt-5"><h2 className="mb-5 flex items-center gap-2 text-xl font-black"><span className="text-red-500">{icon}</span>{title}</h2><div className="space-y-3">{children}</div></section>; }
function Toggle({ label, checked, onChange }: { label: string; checked: boolean; onChange: (value: boolean) => void }) { return <label className="flex cursor-pointer items-center justify-between gap-4 rounded-lg border border-white/10 bg-white/[0.025] p-4"><span className="text-sm font-black">{label}</span><input type="checkbox" checked={checked} onChange={(e) => onChange(e.target.checked)} className="h-5 w-5 accent-red-600" /></label>; }
function TextField({ label, value, onChange }: { label: string; value: string; onChange: (value: string) => void }) { return <label className="block text-xs font-black uppercase text-zinc-500">{label}<input value={value} onChange={(e) => onChange(e.target.value)} className="mt-2 h-12 w-full rounded-lg border border-white/10 bg-black/30 px-3 text-sm font-bold text-white" /></label>; }
function NumberField({ label, value, onChange, step }: { label: string; value: number; onChange: (value: number) => void; step: string }) { return <label className="block text-xs font-black uppercase text-zinc-500">{label}<input type="number" min="0" step={step} value={value} onChange={(e) => onChange(Number(e.target.value))} className="mt-2 h-12 w-full rounded-lg border border-white/10 bg-black/30 px-3 text-sm font-bold text-white" /></label>; }
