"use client";

import Link from "next/link";
import { useCallback, useEffect, useMemo, useState } from "react";
import { ArrowLeft, Braces, Clipboard, ExternalLink, Loader2, Pause, Play, Search, Settings, ShieldOff } from "lucide-react";
import { authenticatedFetch } from "@/lib/authGuards";

type ClientRow = { id: string; company_name: string; email: string; website_domain: string; allowed_domain: string; status: string; widget_enabled: boolean; plan: string; monthly_price: number; currency: string; stripe_subscription_status: string | null; stripe_customer_id: string | null; public_key: string | null; usage_this_month: number; blocked_this_month: number; pending_domain_request_count: number; latest_requested_domain: string | null; created_at: string };

export default function AdminWidgetClientsPage() {
  const [clients, setClients] = useState<ClientRow[]>([]); const [loading, setLoading] = useState(true); const [message, setMessage] = useState(""); const [search, setSearch] = useState("");
  const authFetch = useCallback((url: string, init?: RequestInit) => authenticatedFetch(url, { ...init, cache: "no-store" }), []);
  const load = useCallback(async () => { try { const response = await authFetch("/api/admin/widget-clients"); const data = await response.json(); if (!response.ok) throw new Error(data.error); setClients(data.clients ?? []); } catch (error) { setMessage(error instanceof Error ? error.message : "Widget clients could not be loaded."); } finally { setLoading(false); } }, [authFetch]);
  useEffect(() => { void Promise.resolve().then(load); }, [load]);
  async function quickAction(id: string, action: "activate" | "suspend") { const response = await authFetch(`/api/admin/widget-clients/${id}`, { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ action }) }); const data = await response.json(); if (!response.ok) { setMessage(data.error || "Action failed."); return; } await load(); }
  async function copyEmbed(client: ClientRow) { if (!client.public_key) { setMessage("This client has no active public key."); return; } await navigator.clipboard.writeText(`<div id="mga-vehicle-lookup"></div>\n<script src="https://file.mgautotech.de/widget/vehicle-lookup.js" data-client-key="${client.public_key}" data-target="#mga-vehicle-lookup"></script>`); setMessage(`Embed code copied for ${client.company_name}.`); }
  const filtered = useMemo(() => { const term = search.toLowerCase().trim(); return !term ? clients : clients.filter((c) => [c.company_name,c.email,c.allowed_domain,c.website_domain,c.status,c.plan,c.latest_requested_domain ?? "", c.pending_domain_request_count > 0 ? "pending domain request domain review" : ""].join(" ").toLowerCase().includes(term)); }, [clients, search]);
  if (loading) return <main className="flex min-h-screen items-center justify-center bg-[#050505] text-white"><Loader2 className="mr-3 h-6 w-6 animate-spin text-red-500" />Loading widget clients...</main>;
  return <main className="min-h-screen bg-[#050505] text-white"><header className="border-b border-white/10"><div className="mx-auto flex max-w-[1500px] items-center justify-between gap-3 px-4 py-5"><div className="flex items-center gap-3"><Braces className="h-7 w-7 text-red-500" /><div><div className="text-xs font-black uppercase tracking-[0.18em] text-red-500">Widget SaaS</div><h1 className="text-2xl font-black">Widget Clients</h1></div></div><div className="flex gap-2"><Link href="/admin/widget-settings" className="rounded-lg border border-white/10 px-3 py-3 text-sm font-black"><Settings className="mr-2 inline h-4 w-4" />Settings</Link><Link href="/admin" className="rounded-lg border border-white/10 px-3 py-3 text-sm font-black"><ArrowLeft className="mr-2 inline h-4 w-4" />Admin</Link></div></div></header><section className="mx-auto max-w-[1500px] px-4 py-8">{message && <div className="mb-6 border border-amber-700/40 bg-amber-950/20 p-4 text-sm text-amber-200">{message}</div>}<div className="mb-6 grid gap-3 sm:grid-cols-2 lg:grid-cols-5"><Metric label="Total clients" value={clients.length} /><Metric label="Active" value={clients.filter((c) => c.status === "active" && c.widget_enabled).length} /><Metric label="Past due / suspended" value={clients.filter((c) => ["past_due","suspended"].includes(c.status)).length} /><Metric label="Blocked this month" value={clients.reduce((sum,c) => sum + c.blocked_this_month, 0)} /><Metric label="Pending domain requests" value={clients.reduce((sum,c) => sum + c.pending_domain_request_count, 0)} /></div><div className="relative mb-5 max-w-xl"><Search className="absolute left-4 top-1/2 h-4 w-4 -translate-y-1/2 text-zinc-500" /><input value={search} onChange={(e) => setSearch(e.target.value)} placeholder="Search company, email, domain, plan or pending request..." className="h-12 w-full rounded-lg border border-white/10 bg-black/30 pl-11 pr-4 text-sm font-bold outline-none focus:border-red-700" /></div>
    <div className="hidden overflow-x-auto border-y border-white/10 md:block"><table className="w-full min-w-[1440px] text-left text-sm"><thead className="text-xs uppercase tracking-[0.12em] text-zinc-500"><tr>{["Company","Domain","Domain review","Status","Plan","Price","Stripe","Usage","Blocked","Created","Actions"].map((h) => <th key={h} className="px-4 py-4">{h}</th>)}</tr></thead><tbody>{filtered.map((c) => <tr key={c.id} className="border-t border-white/10"><td className="px-4 py-4"><div className="font-black">{c.company_name}</div><div className="mt-1 text-xs text-zinc-500">{c.email}</div></td><td className="px-4 py-4"><div className="font-bold">{c.allowed_domain}</div><div className="text-xs text-zinc-600">{c.website_domain}</div></td><td className="px-4 py-4"><PendingDomainSignal clientId={c.id} count={c.pending_domain_request_count} domain={c.latest_requested_domain} /></td><td className="px-4 py-4"><Status value={c.status} enabled={c.widget_enabled} /></td><td className="px-4 py-4 font-black uppercase">{c.plan}</td><td className="px-4 py-4 font-black">{Number(c.monthly_price).toFixed(2)} {c.currency.toUpperCase()}</td><td className="px-4 py-4 text-zinc-400">{c.stripe_subscription_status || "Manual"}</td><td className="px-4 py-4 font-black">{c.usage_this_month}</td><td className="px-4 py-4 font-black text-red-300">{c.blocked_this_month}</td><td className="px-4 py-4 text-zinc-500">{new Date(c.created_at).toLocaleDateString()}</td><td className="px-4 py-4"><div className="flex gap-2"><Link href={`/admin/widget-clients/${c.id}`} className="rounded-lg bg-[#b1121b] px-3 py-2 text-xs font-black">View</Link><button onClick={() => quickAction(c.id, c.status === "active" ? "suspend" : "activate")} className="rounded-lg border border-white/10 p-2" aria-label={c.status === "active" ? "Suspend client" : "Activate client"}>{c.status === "active" ? <Pause className="h-4 w-4" /> : <Play className="h-4 w-4" />}</button><button onClick={() => copyEmbed(c)} className="rounded-lg border border-white/10 p-2" aria-label="Copy embed code"><Clipboard className="h-4 w-4" /></button>{c.stripe_customer_id && <a href={`https://dashboard.stripe.com/customers/${c.stripe_customer_id}`} target="_blank" rel="noreferrer" className="rounded-lg border border-white/10 p-2" aria-label="Open Stripe customer"><ExternalLink className="h-4 w-4" /></a>}</div></td></tr>)}</tbody></table></div>
    <div className="grid gap-3 md:hidden">{filtered.map((c) => <Link key={c.id} href={`/admin/widget-clients/${c.id}`} className="rounded-xl border border-white/10 bg-white/[0.025] p-5"><div className="flex items-start justify-between gap-3"><div className="min-w-0"><div className="truncate text-lg font-black">{c.company_name}</div><div className="mt-1 truncate text-sm text-zinc-500">{c.allowed_domain}</div></div><Status value={c.status} enabled={c.widget_enabled} /></div><div className="mt-4 grid grid-cols-2 gap-2 text-xs"><Small label="Plan" value={c.plan} /><Small label="Usage" value={String(c.usage_this_month)} /><Small label="Blocked" value={String(c.blocked_this_month)} /><Small label="Pending" value={c.pending_domain_request_count > 0 ? `${c.pending_domain_request_count} - ${c.latest_requested_domain ?? "Domain review"}` : "None"} /></div></Link>)}</div>{!filtered.length && <div className="py-20 text-center text-zinc-600"><ShieldOff className="mx-auto mb-3 h-8 w-8" />No widget clients found.</div>}</section></main>;
}
function Metric({ label, value }: { label: string; value: number }) { return <div className="border-l border-red-800/50 bg-white/[0.025] p-5"><div className="text-xs font-black uppercase tracking-[0.12em] text-zinc-500">{label}</div><div className="mt-2 text-3xl font-black">{value}</div></div>; }
function PendingDomainSignal({ clientId, count, domain }: { clientId: string; count: number; domain: string | null }) { if (count <= 0) return <span className="text-xs font-bold text-zinc-600">No pending request</span>; return <Link href={`/admin/widget-clients/${clientId}`} aria-label={`Review ${count} pending domain request${count === 1 ? "" : "s"} for ${domain ?? "this widget client"}`} className="inline-flex max-w-[230px] flex-col rounded-lg border border-amber-700/40 bg-amber-950/25 px-3 py-2 text-xs font-black text-amber-200"><span>{count} pending</span><span className="mt-1 break-all text-[11px] font-bold text-amber-100/80">{domain || "Domain review"}</span></Link>; }
function Status({ value, enabled }: { value: string; enabled: boolean }) { const good = value === "active" && enabled; return <span className={`inline-flex rounded-full border px-2.5 py-1 text-[11px] font-black uppercase ${good ? "border-emerald-700/40 bg-emerald-950/30 text-emerald-300" : "border-red-800/40 bg-red-950/25 text-red-300"}`}>{value}</span>; }
function Small({ label, value }: { label: string; value: string }) { return <div className="rounded-lg bg-black/30 p-3"><div className="text-zinc-600">{label}</div><div className="mt-1 truncate font-black text-white">{value}</div></div>; }
