import type { TransactionalEmailLanguage } from "@/lib/email/types";

export type EmailLocaleCopy = {
  serviceName: string;
  portal: string;
  update: string;
  secureNotice: string;
  defaultFooter: string;
  contact: string;
  details: {
    reference: string;
    customerId: string;
    status: string;
    vehicle: string;
    services: string;
    amount: string;
    credits: string;
    paymentReference: string;
    accountHolder: string;
    bank: string;
    file: string;
    message: string;
    actionRequired: string;
    support: string;
  };
  actions: {
    openDashboard: string;
    resetPassword: string;
  };
  deviceVerification: {
    subject: string;
    preheader: string;
    title: string;
    intro: string;
    securityCodeLabel: string;
    deviceLabel: string;
    validForLabel: string;
    unexpectedAction: string;
    neverShare: string;
    supportNeverAsks: string;
  };
  intros: {
    account: string;
    password: string;
    request: string;
    file: string;
    payment: string;
    message: string;
  };
  passwordFooter: string;
  lifecycle: {
    fileReview: string;
    inProgress: string;
    responseRequired: string;
    revisionReview: string;
    completed: string;
    cancelled: string;
    fileRequired: string;
    fileReceived: string;
    technicalReview: string;
    readyForDelivery: string;
    delivered: string;
    manualReview: string;
    checkMessage: string;
    uploadFile: string;
  };
  events: {
    accountReady: string;
    passwordReset: string;
    requestCreated: string;
    requestReminder: string;
    requestReceived: string;
    fileReceived: string;
    additionalFileRequired: string;
    additionalFileReceived: string;
    requestReview: string;
    requestProgress: string;
    responseRequired: string;
    requestCompleted: string;
    requestDelivered: string;
    requestCancelled: string;
    requestNotPossible: string;
    creditPurchase: string;
    bankTransfer: string;
    paymentReceived: string;
    creditsAdded: string;
    paymentFailed: string;
    paymentReview: string;
    newMessage: string;
    uploadEnabled: string;
    uploadDisabled: string;
  };
};

export const emailLocaleCopy: Record<TransactionalEmailLanguage, EmailLocaleCopy> = {
  en: {
    serviceName: "Secure ECU / TCU File Service",
    portal: "Customer Portal", update: "MG AutoTech Update",
    secureNotice: "Files and confidential technical data are available only inside the signed-in MG AutoTech customer portal.",
    defaultFooter: "This email contains customer-relevant information only. Internal work notes and private technical data are never sent by email.", contact: "Contact",
    details: { reference: "Reference", customerId: "Customer ID", status: "Status", vehicle: "Vehicle", services: "Services", amount: "Amount", credits: "Credits", paymentReference: "Payment reference", accountHolder: "Account holder", bank: "Bank", file: "File", message: "Message", actionRequired: "Action required", support: "Support" },
    actions: { openDashboard: "Open dashboard", resetPassword: "Reset password securely" },
    deviceVerification: { subject: "MG AutoTech - Account security code", preheader: "Confirm the security check for your customer account.", title: "Confirm this security check", intro: "Use this security code to continue securely with your MG AutoTech customer account.", securityCodeLabel: "Security code", deviceLabel: "Device", validForLabel: "Valid for", unexpectedAction: "If you did not start this action, change your password and contact support.", neverShare: "Never share this code with anyone.", supportNeverAsks: "MG AutoTech will never ask you for this code by phone or chat." },
    intros: { account: "Your secure MG AutoTech customer account is ready to use.", password: "A password reset was requested for your MG AutoTech customer account.", request: "There is an update for your MG AutoTech request. Open the secure dashboard for full details.", file: "A file update was recorded securely for your MG AutoTech request.", payment: "There is an update to your MG AutoTech payment or credit balance.", message: "MG AutoTech sent you a new customer-visible message." },
    passwordFooter: "If you did not request this, ignore this email. Do not share the security link.",
    lifecycle: { fileReview: "File review", inProgress: "In progress", responseRequired: "Response required", revisionReview: "Revision under review", completed: "Completed", cancelled: "Cancelled", fileRequired: "File required", fileReceived: "File received", technicalReview: "Technical review", readyForDelivery: "Ready for delivery", delivered: "Delivered", manualReview: "Manual review", checkMessage: "Open your request and review the latest message in the customer portal.", uploadFile: "Open your request and upload the requested file only through the customer portal." },
    events: { accountReady: "Your customer account is ready", passwordReset: "Reset your password securely", requestCreated: "Request created", requestReminder: "Complete your request", requestReceived: "Request received", fileReceived: "File received", additionalFileRequired: "Additional file required", additionalFileReceived: "Additional file received", requestReview: "Request under review", requestProgress: "Request in progress", responseRequired: "Your response is required", requestCompleted: "Request completed", requestDelivered: "Your file is ready", requestCancelled: "Request cancelled", requestNotPossible: "Request currently not possible", creditPurchase: "Credit purchase started", bankTransfer: "Bank transfer information", paymentReceived: "Payment received", creditsAdded: "Credits added", paymentFailed: "Payment failed", paymentReview: "Payment under review", newMessage: "New request message", uploadEnabled: "Additional upload enabled", uploadDisabled: "Additional upload disabled" },
  },
  de: {
    serviceName: "Sicherer ECU-/TCU-Dateiservice",
    portal: "Kundenportal", update: "MG AutoTech Update",
    secureNotice: "Dateien und vertrauliche technische Daten sind nur im angemeldeten MG AutoTech Kundenportal verfügbar.",
    defaultFooter: "Diese E-Mail enthält nur kundenrelevante Informationen. Interne Notizen und private technische Daten werden nicht per E-Mail versendet.", contact: "Kontakt",
    details: { reference: "Referenz", customerId: "Kunden-ID", status: "Status", vehicle: "Fahrzeug", services: "Services", amount: "Betrag", credits: "Credits", paymentReference: "Zahlungsreferenz", accountHolder: "Kontoinhaber", bank: "Bank", file: "Datei", message: "Nachricht", actionRequired: "Aktion erforderlich", support: "Support" },
    actions: { openDashboard: "Dashboard öffnen", resetPassword: "Passwort sicher zurücksetzen" },
    deviceVerification: { subject: "MG AutoTech – Sicherheitscode für Ihr Konto", preheader: "Bestätigen Sie die Sicherheitsprüfung für Ihr Kundenkonto.", title: "Sicherheitsprüfung bestätigen", intro: "Verwenden Sie diesen Sicherheitscode, um sicher mit Ihrem MG AutoTech Kundenkonto fortzufahren.", securityCodeLabel: "Sicherheitscode", deviceLabel: "Gerät", validForLabel: "Gültig für", unexpectedAction: "Wenn Sie diese Aktion nicht gestartet haben, ändern Sie Ihr Passwort und kontaktieren Sie den Support.", neverShare: "Teilen Sie diesen Sicherheitscode niemals mit anderen Personen.", supportNeverAsks: "MG AutoTech fragt niemals telefonisch oder im Chat nach diesem Code." },
    intros: { account: "Ihr sicheres MG AutoTech Kundenkonto ist einsatzbereit.", password: "Für Ihr MG AutoTech Kundenkonto wurde eine Passwort-Zurücksetzung angefordert.", request: "Zu Ihrer MG AutoTech Anfrage liegt ein Update vor. Alle Details finden Sie im sicheren Dashboard.", file: "Für Ihre MG AutoTech Anfrage wurde ein Datei-Update sicher erfasst.", payment: "Zu Ihrer MG AutoTech Zahlung oder Ihrem Credit-Guthaben liegt ein Update vor.", message: "MG AutoTech hat Ihnen eine neue kundensichtbare Nachricht gesendet." },
    passwordFooter: "Falls Sie dies nicht angefordert haben, ignorieren Sie diese E-Mail. Geben Sie den Sicherheitslink nicht weiter.",
    lifecycle: { fileReview: "Dateiprüfung", inProgress: "In Bearbeitung", responseRequired: "Rückmeldung erforderlich", revisionReview: "Revision in Prüfung", completed: "Abgeschlossen", cancelled: "Storniert", fileRequired: "Datei erforderlich", fileReceived: "Datei erhalten", technicalReview: "Technische Prüfung", readyForDelivery: "Bereit zur Auslieferung", delivered: "Ausgeliefert", manualReview: "Manuelle Prüfung", checkMessage: "Öffnen Sie Ihre Anfrage und prüfen Sie die aktuelle Nachricht im Kundenportal.", uploadFile: "Öffnen Sie Ihre Anfrage und laden Sie die angeforderte Datei nur über das Kundenportal hoch." },
    events: { accountReady: "Ihr Kundenkonto ist bereit", passwordReset: "Passwort sicher zurücksetzen", requestCreated: "Anfrage erstellt", requestReminder: "Anfrage abschließen", requestReceived: "Anfrage erhalten", fileReceived: "Datei erhalten", additionalFileRequired: "Zusätzliche Datei erforderlich", additionalFileReceived: "Zusätzliche Datei erhalten", requestReview: "Anfrage wird geprüft", requestProgress: "Anfrage in Bearbeitung", responseRequired: "Ihre Rückmeldung ist erforderlich", requestCompleted: "Anfrage abgeschlossen", requestDelivered: "Ihre Datei ist bereit", requestCancelled: "Anfrage storniert", requestNotPossible: "Anfrage derzeit nicht möglich", creditPurchase: "Credit-Kauf gestartet", bankTransfer: "Überweisungsinformationen", paymentReceived: "Zahlung erhalten", creditsAdded: "Credits hinzugefügt", paymentFailed: "Zahlung fehlgeschlagen", paymentReview: "Zahlung wird geprüft", newMessage: "Neue Anfragenachricht", uploadEnabled: "Zusätzlicher Upload aktiviert", uploadDisabled: "Zusätzlicher Upload deaktiviert" },
  },
  tr: {
    serviceName: "Güvenli ECU / TCU Dosya Hizmeti",
    portal: "Müşteri Paneli", update: "MG AutoTech Güncellemesi",
    secureNotice: "Dosyalar ve gizli teknik veriler yalnızca giriş yapılmış MG AutoTech müşteri panelinde sunulur.",
    defaultFooter: "Bu e-posta yalnızca müşteriye açık bilgiler içerir. Dahili notlar ve özel teknik veriler e-posta ile gönderilmez.", contact: "İletişim",
    details: { reference: "Referans", customerId: "Müşteri No", status: "Durum", vehicle: "Araç", services: "Hizmetler", amount: "Tutar", credits: "Kredi", paymentReference: "Ödeme referansı", accountHolder: "Hesap sahibi", bank: "Banka", file: "Dosya", message: "Mesaj", actionRequired: "İşlem gerekli", support: "Destek" },
    actions: { openDashboard: "Paneli aç", resetPassword: "Şifreyi güvenle sıfırla" },
    deviceVerification: { subject: "MG AutoTech - Hesap güvenlik kodu", preheader: "Müşteri hesabınız için güvenlik kontrolünü doğrulayın.", title: "Bu güvenlik kontrolünü doğrulayın", intro: "MG AutoTech müşteri hesabınızda güvenle devam etmek için bu güvenlik kodunu kullanın.", securityCodeLabel: "Güvenlik kodu", deviceLabel: "Cihaz", validForLabel: "Geçerlilik süresi", unexpectedAction: "Bu işlemi siz başlatmadıysanız şifrenizi değiştirin ve destekle iletişime geçin.", neverShare: "Bu kodu hiç kimseyle paylaşmayın.", supportNeverAsks: "MG AutoTech bu kodu telefonla veya sohbet üzerinden asla istemez." },
    intros: { account: "Güvenli MG AutoTech müşteri hesabınız kullanıma hazır.", password: "MG AutoTech müşteri hesabınız için şifre sıfırlama talebi oluşturuldu.", request: "MG AutoTech talebinizle ilgili bir güncelleme var. Ayrıntılar için güvenli paneli açın.", file: "MG AutoTech talebiniz için bir dosya güncellemesi güvenle kaydedildi.", payment: "MG AutoTech ödemeniz veya kredi bakiyenizle ilgili bir güncelleme var.", message: "MG AutoTech size müşteriye açık yeni bir mesaj gönderdi." },
    passwordFooter: "Bu talebi siz oluşturmadıysanız e-postayı dikkate almayın. Güvenlik bağlantısını paylaşmayın.",
    lifecycle: { fileReview: "Dosya incelemesi", inProgress: "İşleniyor", responseRequired: "Yanıt gerekli", revisionReview: "Revizyon inceleniyor", completed: "Tamamlandı", cancelled: "İptal edildi", fileRequired: "Dosya gerekli", fileReceived: "Dosya alındı", technicalReview: "Teknik inceleme", readyForDelivery: "Teslime hazır", delivered: "Teslim edildi", manualReview: "Manuel inceleme", checkMessage: "Talebinizi açın ve müşteri panelindeki son mesajı kontrol edin.", uploadFile: "Talebinizi açın ve istenen dosyayı yalnızca müşteri panelinden yükleyin." },
    events: { accountReady: "Müşteri hesabınız hazır", passwordReset: "Şifrenizi güvenle sıfırlayın", requestCreated: "Talep oluşturuldu", requestReminder: "Talebinizi tamamlayın", requestReceived: "Talep alındı", fileReceived: "Dosya alındı", additionalFileRequired: "Ek dosya gerekli", additionalFileReceived: "Ek dosya alındı", requestReview: "Talep inceleniyor", requestProgress: "Talep işleniyor", responseRequired: "Yanıtınız gerekli", requestCompleted: "Talep tamamlandı", requestDelivered: "Dosyanız hazır", requestCancelled: "Talep iptal edildi", requestNotPossible: "Talep şu anda yapılamıyor", creditPurchase: "Kredi satın alma başlatıldı", bankTransfer: "Havale bilgileri", paymentReceived: "Ödeme alındı", creditsAdded: "Krediler eklendi", paymentFailed: "Ödeme başarısız", paymentReview: "Ödeme inceleniyor", newMessage: "Yeni talep mesajı", uploadEnabled: "Ek yükleme açıldı", uploadDisabled: "Ek yükleme kapatıldı" },
  },
  nl: {
    serviceName: "Veilige ECU-/TCU-bestandsservice",
    portal: "Klantenportaal", update: "MG AutoTech-update", secureNotice: "Bestanden en vertrouwelijke technische gegevens zijn alleen beschikbaar in het beveiligde MG AutoTech-klantenportaal.", defaultFooter: "Deze e-mail bevat alleen klantinformatie. Interne notities en privé technische gegevens worden nooit per e-mail verzonden.", contact: "Contact",
    details: { reference: "Referentie", customerId: "Klant-ID", status: "Status", vehicle: "Voertuig", services: "Diensten", amount: "Bedrag", credits: "Credits", paymentReference: "Betalingskenmerk", accountHolder: "Rekeninghouder", bank: "Bank", file: "Bestand", message: "Bericht", actionRequired: "Actie vereist", support: "Ondersteuning" },
    actions: { openDashboard: "Dashboard openen", resetPassword: "Wachtwoord veilig resetten" }, deviceVerification: { subject: "MG AutoTech - Beveiligingscode voor uw account", preheader: "Bevestig de beveiligingscontrole voor uw klantenaccount.", title: "Bevestig deze beveiligingscontrole", intro: "Gebruik deze beveiligingscode om uw MG AutoTech-klantenaccount veilig te blijven gebruiken.", securityCodeLabel: "Beveiligingscode", deviceLabel: "Apparaat", validForLabel: "Geldig voor", unexpectedAction: "Als u deze actie niet hebt gestart, wijzig dan uw wachtwoord en neem contact op met de ondersteuning.", neverShare: "Deel deze code nooit met iemand.", supportNeverAsks: "MG AutoTech zal u nooit telefonisch of via de chat om deze code vragen." }, intros: { account: "Uw beveiligde MG AutoTech-klantenaccount is klaar voor gebruik.", password: "Er is een wachtwoordreset aangevraagd voor uw MG AutoTech-account.", request: "Er is een update voor uw MG AutoTech-aanvraag. Open het beveiligde dashboard voor details.", file: "Een bestandsupdate is veilig vastgelegd bij uw MG AutoTech-aanvraag.", payment: "Er is een update over uw MG AutoTech-betaling of creditsaldo.", message: "MG AutoTech heeft u een nieuw klantbericht gestuurd." }, passwordFooter: "Hebt u dit niet aangevraagd, negeer dan deze e-mail en deel de beveiligingslink niet.",
    lifecycle: { fileReview: "Bestandscontrole", inProgress: "In behandeling", responseRequired: "Reactie vereist", revisionReview: "Revisie wordt beoordeeld", completed: "Voltooid", cancelled: "Geannuleerd", fileRequired: "Bestand vereist", fileReceived: "Bestand ontvangen", technicalReview: "Technische controle", readyForDelivery: "Klaar voor levering", delivered: "Geleverd", manualReview: "Handmatige controle", checkMessage: "Open uw aanvraag en bekijk het nieuwste bericht in het klantenportaal.", uploadFile: "Open uw aanvraag en upload het gevraagde bestand alleen via het klantenportaal." },
    events: { accountReady: "Uw klantenaccount is klaar", passwordReset: "Wachtwoord veilig resetten", requestCreated: "Aanvraag aangemaakt", requestReminder: "Aanvraag afronden", requestReceived: "Aanvraag ontvangen", fileReceived: "Bestand ontvangen", additionalFileRequired: "Extra bestand vereist", additionalFileReceived: "Extra bestand ontvangen", requestReview: "Aanvraag wordt beoordeeld", requestProgress: "Aanvraag in behandeling", responseRequired: "Uw reactie is vereist", requestCompleted: "Aanvraag voltooid", requestDelivered: "Uw bestand is klaar", requestCancelled: "Aanvraag geannuleerd", requestNotPossible: "Aanvraag momenteel niet mogelijk", creditPurchase: "Creditaankoop gestart", bankTransfer: "Bankoverschrijving", paymentReceived: "Betaling ontvangen", creditsAdded: "Credits toegevoegd", paymentFailed: "Betaling mislukt", paymentReview: "Betaling wordt beoordeeld", newMessage: "Nieuw aanvraagbericht", uploadEnabled: "Extra upload ingeschakeld", uploadDisabled: "Extra upload uitgeschakeld" },
  },
  fr: {
    serviceName: "Service de fichiers ECU / TCU sécurisé",
    portal: "Portail client", update: "Mise à jour MG AutoTech", secureNotice: "Les fichiers et données techniques confidentielles sont disponibles uniquement dans le portail client MG AutoTech sécurisé.", defaultFooter: "Cet e-mail contient uniquement des informations destinées au client. Les notes internes et données techniques privées ne sont jamais envoyées par e-mail.", contact: "Contact",
    details: { reference: "Référence", customerId: "ID client", status: "Statut", vehicle: "Véhicule", services: "Services", amount: "Montant", credits: "Crédits", paymentReference: "Référence de paiement", accountHolder: "Titulaire du compte", bank: "Banque", file: "Fichier", message: "Message", actionRequired: "Action requise", support: "Assistance" },
    actions: { openDashboard: "Ouvrir le tableau de bord", resetPassword: "Réinitialiser le mot de passe" }, deviceVerification: { subject: "MG AutoTech - Code de sécurité de votre compte", preheader: "Confirmez le contrôle de sécurité de votre compte client.", title: "Confirmez ce contrôle de sécurité", intro: "Utilisez ce code de sécurité pour continuer à utiliser votre compte client MG AutoTech en toute sécurité.", securityCodeLabel: "Code de sécurité", deviceLabel: "Appareil", validForLabel: "Valide pendant", unexpectedAction: "Si vous n’êtes pas à l’origine de cette action, modifiez votre mot de passe et contactez l’assistance.", neverShare: "Ne communiquez jamais ce code à qui que ce soit.", supportNeverAsks: "MG AutoTech ne vous demandera jamais ce code par téléphone ou via le chat." }, intros: { account: "Votre compte client MG AutoTech sécurisé est prêt.", password: "Une réinitialisation du mot de passe a été demandée pour votre compte MG AutoTech.", request: "Votre demande MG AutoTech a été mise à jour. Consultez le tableau de bord sécurisé pour les détails.", file: "Une mise à jour de fichier a été enregistrée en toute sécurité pour votre demande.", payment: "Votre paiement ou solde de crédits MG AutoTech a été mis à jour.", message: "MG AutoTech vous a envoyé un nouveau message visible par le client." }, passwordFooter: "Si vous n'êtes pas à l'origine de cette demande, ignorez cet e-mail et ne partagez pas le lien de sécurité.",
    lifecycle: { fileReview: "Contrôle du fichier", inProgress: "En cours", responseRequired: "Réponse requise", revisionReview: "Révision en cours", completed: "Terminé", cancelled: "Annulé", fileRequired: "Fichier requis", fileReceived: "Fichier reçu", technicalReview: "Contrôle technique", readyForDelivery: "Prêt pour livraison", delivered: "Livré", manualReview: "Contrôle manuel", checkMessage: "Ouvrez votre demande et consultez le dernier message dans le portail client.", uploadFile: "Ouvrez votre demande et téléversez le fichier demandé uniquement via le portail client." },
    events: { accountReady: "Votre compte client est prêt", passwordReset: "Réinitialiser votre mot de passe", requestCreated: "Demande créée", requestReminder: "Finaliser votre demande", requestReceived: "Demande reçue", fileReceived: "Fichier reçu", additionalFileRequired: "Fichier supplémentaire requis", additionalFileReceived: "Fichier supplémentaire reçu", requestReview: "Demande en cours d'examen", requestProgress: "Demande en cours", responseRequired: "Votre réponse est requise", requestCompleted: "Demande terminée", requestDelivered: "Votre fichier est prêt", requestCancelled: "Demande annulée", requestNotPossible: "Demande actuellement impossible", creditPurchase: "Achat de crédits démarré", bankTransfer: "Informations de virement", paymentReceived: "Paiement reçu", creditsAdded: "Crédits ajoutés", paymentFailed: "Échec du paiement", paymentReview: "Paiement en cours d'examen", newMessage: "Nouveau message de demande", uploadEnabled: "Téléversement supplémentaire activé", uploadDisabled: "Téléversement supplémentaire désactivé" },
  },
  it: {
    serviceName: "Servizio file ECU / TCU sicuro",
    portal: "Portale clienti", update: "Aggiornamento MG AutoTech", secureNotice: "File e dati tecnici riservati sono disponibili solo nel portale clienti MG AutoTech autenticato.", defaultFooter: "Questa e-mail contiene solo informazioni per il cliente. Note interne e dati tecnici privati non vengono mai inviati via e-mail.", contact: "Contatto",
    details: { reference: "Riferimento", customerId: "ID cliente", status: "Stato", vehicle: "Veicolo", services: "Servizi", amount: "Importo", credits: "Crediti", paymentReference: "Causale pagamento", accountHolder: "Intestatario", bank: "Banca", file: "File", message: "Messaggio", actionRequired: "Azione richiesta", support: "Assistenza" },
    actions: { openDashboard: "Apri dashboard", resetPassword: "Reimposta password" }, deviceVerification: { subject: "MG AutoTech - Codice di sicurezza dell'account", preheader: "Conferma il controllo di sicurezza per il tuo account cliente.", title: "Conferma questo controllo di sicurezza", intro: "Usa questo codice di sicurezza per continuare ad accedere in sicurezza al tuo account cliente MG AutoTech.", securityCodeLabel: "Codice di sicurezza", deviceLabel: "Dispositivo", validForLabel: "Valido per", unexpectedAction: "Se non hai avviato tu questa operazione, modifica la password e contatta l’assistenza.", neverShare: "Non condividere mai questo codice con nessuno.", supportNeverAsks: "MG AutoTech non ti chiederà mai questo codice per telefono o tramite chat." }, intros: { account: "Il tuo account cliente MG AutoTech sicuro è pronto.", password: "È stato richiesto il ripristino della password del tuo account MG AutoTech.", request: "La tua richiesta MG AutoTech è stata aggiornata. Apri la dashboard sicura per i dettagli.", file: "Un aggiornamento del file è stato registrato in modo sicuro per la tua richiesta.", payment: "Il pagamento o il saldo crediti MG AutoTech è stato aggiornato.", message: "MG AutoTech ti ha inviato un nuovo messaggio visibile al cliente." }, passwordFooter: "Se non hai richiesto questa operazione, ignora l'e-mail e non condividere il link di sicurezza.",
    lifecycle: { fileReview: "Controllo file", inProgress: "In lavorazione", responseRequired: "Risposta richiesta", revisionReview: "Revisione in controllo", completed: "Completato", cancelled: "Annullato", fileRequired: "File richiesto", fileReceived: "File ricevuto", technicalReview: "Controllo tecnico", readyForDelivery: "Pronto per la consegna", delivered: "Consegnato", manualReview: "Controllo manuale", checkMessage: "Apri la richiesta e controlla l'ultimo messaggio nel portale clienti.", uploadFile: "Apri la richiesta e carica il file richiesto solo tramite il portale clienti." },
    events: { accountReady: "Il tuo account cliente è pronto", passwordReset: "Reimposta la password", requestCreated: "Richiesta creata", requestReminder: "Completa la richiesta", requestReceived: "Richiesta ricevuta", fileReceived: "File ricevuto", additionalFileRequired: "File aggiuntivo richiesto", additionalFileReceived: "File aggiuntivo ricevuto", requestReview: "Richiesta in revisione", requestProgress: "Richiesta in lavorazione", responseRequired: "È richiesta una risposta", requestCompleted: "Richiesta completata", requestDelivered: "Il tuo file è pronto", requestCancelled: "Richiesta annullata", requestNotPossible: "Richiesta al momento non possibile", creditPurchase: "Acquisto crediti avviato", bankTransfer: "Dati per bonifico", paymentReceived: "Pagamento ricevuto", creditsAdded: "Crediti aggiunti", paymentFailed: "Pagamento non riuscito", paymentReview: "Pagamento in revisione", newMessage: "Nuovo messaggio richiesta", uploadEnabled: "Caricamento aggiuntivo abilitato", uploadDisabled: "Caricamento aggiuntivo disabilitato" },
  },
  es: {
    serviceName: "Servicio seguro de archivos ECU / TCU",
    portal: "Portal del cliente", update: "Actualización de MG AutoTech", secureNotice: "Los archivos y datos técnicos confidenciales solo están disponibles en el portal seguro de MG AutoTech.", defaultFooter: "Este correo solo contiene información para el cliente. Las notas internas y los datos técnicos privados nunca se envían por correo.", contact: "Contacto",
    details: { reference: "Referencia", customerId: "ID de cliente", status: "Estado", vehicle: "Vehículo", services: "Servicios", amount: "Importe", credits: "Créditos", paymentReference: "Referencia de pago", accountHolder: "Titular", bank: "Banco", file: "Archivo", message: "Mensaje", actionRequired: "Acción requerida", support: "Soporte" },
    actions: { openDashboard: "Abrir panel", resetPassword: "Restablecer contraseña" }, deviceVerification: { subject: "MG AutoTech - Código de seguridad de la cuenta", preheader: "Confirma la verificación de seguridad de tu cuenta de cliente.", title: "Confirma esta verificación de seguridad", intro: "Usa este código de seguridad para seguir utilizando de forma segura tu cuenta de cliente de MG AutoTech.", securityCodeLabel: "Código de seguridad", deviceLabel: "Dispositivo", validForLabel: "Válido durante", unexpectedAction: "Si no has iniciado esta acción, cambia tu contraseña y ponte en contacto con el servicio de asistencia.", neverShare: "No compartas nunca este código con nadie.", supportNeverAsks: "MG AutoTech nunca te pedirá este código por teléfono ni por chat." }, intros: { account: "Tu cuenta segura de cliente MG AutoTech está lista.", password: "Se solicitó restablecer la contraseña de tu cuenta MG AutoTech.", request: "Hay una actualización de tu solicitud MG AutoTech. Abre el panel seguro para ver los detalles.", file: "Se registró de forma segura una actualización de archivo para tu solicitud.", payment: "Hay una actualización de tu pago o saldo de créditos MG AutoTech.", message: "MG AutoTech te envió un nuevo mensaje visible para el cliente." }, passwordFooter: "Si no solicitaste esta acción, ignora el correo y no compartas el enlace de seguridad.",
    lifecycle: { fileReview: "Revisión del archivo", inProgress: "En proceso", responseRequired: "Respuesta requerida", revisionReview: "Revisión en curso", completed: "Completado", cancelled: "Cancelado", fileRequired: "Archivo requerido", fileReceived: "Archivo recibido", technicalReview: "Revisión técnica", readyForDelivery: "Listo para entregar", delivered: "Entregado", manualReview: "Revisión manual", checkMessage: "Abre tu solicitud y revisa el último mensaje en el portal del cliente.", uploadFile: "Abre tu solicitud y carga el archivo solicitado solo mediante el portal del cliente." },
    events: { accountReady: "Tu cuenta de cliente está lista", passwordReset: "Restablece tu contraseña", requestCreated: "Solicitud creada", requestReminder: "Completa tu solicitud", requestReceived: "Solicitud recibida", fileReceived: "Archivo recibido", additionalFileRequired: "Archivo adicional requerido", additionalFileReceived: "Archivo adicional recibido", requestReview: "Solicitud en revisión", requestProgress: "Solicitud en proceso", responseRequired: "Se requiere tu respuesta", requestCompleted: "Solicitud completada", requestDelivered: "Tu archivo está listo", requestCancelled: "Solicitud cancelada", requestNotPossible: "Solicitud no disponible actualmente", creditPurchase: "Compra de créditos iniciada", bankTransfer: "Información de transferencia", paymentReceived: "Pago recibido", creditsAdded: "Créditos añadidos", paymentFailed: "Pago fallido", paymentReview: "Pago en revisión", newMessage: "Nuevo mensaje de solicitud", uploadEnabled: "Carga adicional habilitada", uploadDisabled: "Carga adicional deshabilitada" },
  },
  pt: {
    serviceName: "Serviço seguro de ficheiros ECU / TCU",
    portal: "Portal do cliente", update: "Atualização MG AutoTech", secureNotice: "Os ficheiros e dados técnicos confidenciais estão disponíveis apenas no portal seguro MG AutoTech.", defaultFooter: "Este e-mail contém apenas informações para o cliente. Notas internas e dados técnicos privados nunca são enviados por e-mail.", contact: "Contacto",
    details: { reference: "Referência", customerId: "ID de cliente", status: "Estado", vehicle: "Veículo", services: "Serviços", amount: "Montante", credits: "Créditos", paymentReference: "Referência de pagamento", accountHolder: "Titular da conta", bank: "Banco", file: "Ficheiro", message: "Mensagem", actionRequired: "Ação necessária", support: "Suporte" },
    actions: { openDashboard: "Abrir painel", resetPassword: "Repor palavra-passe" }, deviceVerification: { subject: "MG AutoTech - Código de segurança da conta", preheader: "Confirme a verificação de segurança da sua conta de cliente.", title: "Confirme esta verificação de segurança", intro: "Utilize este código de segurança para continuar a utilizar a sua conta de cliente MG AutoTech em segurança.", securityCodeLabel: "Código de segurança", deviceLabel: "Dispositivo", validForLabel: "Válido durante", unexpectedAction: "Se não iniciou esta ação, altere a sua palavra-passe e contacte o suporte.", neverShare: "Nunca partilhe este código com ninguém.", supportNeverAsks: "A MG AutoTech nunca lhe pedirá este código por telefone ou via chat." }, intros: { account: "A sua conta segura de cliente MG AutoTech está pronta.", password: "Foi pedida uma reposição da palavra-passe da sua conta MG AutoTech.", request: "Existe uma atualização da sua solicitação MG AutoTech. Abra o painel seguro para ver os detalhes.", file: "Foi registada em segurança uma atualização de ficheiro para a sua solicitação.", payment: "Existe uma atualização do seu pagamento ou saldo de créditos MG AutoTech.", message: "A MG AutoTech enviou-lhe uma nova mensagem visível ao cliente." }, passwordFooter: "Se não pediu esta ação, ignore o e-mail e não partilhe a ligação de segurança.",
    lifecycle: { fileReview: "Revisão do ficheiro", inProgress: "Em processamento", responseRequired: "Resposta necessária", revisionReview: "Revisão em análise", completed: "Concluído", cancelled: "Cancelado", fileRequired: "Ficheiro necessário", fileReceived: "Ficheiro recebido", technicalReview: "Revisão técnica", readyForDelivery: "Pronto para entrega", delivered: "Entregue", manualReview: "Revisão manual", checkMessage: "Abra a solicitação e consulte a mensagem mais recente no portal do cliente.", uploadFile: "Abra a solicitação e carregue o ficheiro pedido apenas pelo portal do cliente." },
    events: { accountReady: "A sua conta de cliente está pronta", passwordReset: "Repor a sua palavra-passe", requestCreated: "Solicitação criada", requestReminder: "Concluir solicitação", requestReceived: "Solicitação recebida", fileReceived: "Ficheiro recebido", additionalFileRequired: "Ficheiro adicional necessário", additionalFileReceived: "Ficheiro adicional recebido", requestReview: "Solicitação em revisão", requestProgress: "Solicitação em processamento", responseRequired: "A sua resposta é necessária", requestCompleted: "Solicitação concluída", requestDelivered: "O seu ficheiro está pronto", requestCancelled: "Solicitação cancelada", requestNotPossible: "Solicitação indisponível neste momento", creditPurchase: "Compra de créditos iniciada", bankTransfer: "Informações de transferência", paymentReceived: "Pagamento recebido", creditsAdded: "Créditos adicionados", paymentFailed: "Pagamento falhou", paymentReview: "Pagamento em revisão", newMessage: "Nova mensagem da solicitação", uploadEnabled: "Carregamento adicional ativado", uploadDisabled: "Carregamento adicional desativado" },
  },
  pl: {
    serviceName: "Bezpieczna obsługa plików ECU / TCU",
    portal: "Panel klienta", update: "Aktualizacja MG AutoTech", secureNotice: "Pliki i poufne dane techniczne są dostępne wyłącznie w zabezpieczonym panelu klienta MG AutoTech.", defaultFooter: "Ta wiadomość zawiera tylko informacje dla klienta. Notatki wewnętrzne i prywatne dane techniczne nie są wysyłane e-mailem.", contact: "Kontakt",
    details: { reference: "Numer referencyjny", customerId: "ID klienta", status: "Status", vehicle: "Pojazd", services: "Usługi", amount: "Kwota", credits: "Kredyty", paymentReference: "Tytuł płatności", accountHolder: "Właściciel konta", bank: "Bank", file: "Plik", message: "Wiadomość", actionRequired: "Wymagane działanie", support: "Pomoc" },
    actions: { openDashboard: "Otwórz panel", resetPassword: "Bezpiecznie zresetuj hasło" }, deviceVerification: { subject: "MG AutoTech - Kod bezpieczeństwa konta", preheader: "Potwierdź weryfikację bezpieczeństwa swojego konta klienta.", title: "Potwierdź weryfikację bezpieczeństwa", intro: "Użyj tego kodu bezpieczeństwa, aby bezpiecznie kontynuować korzystanie z konta klienta MG AutoTech.", securityCodeLabel: "Kod bezpieczeństwa", deviceLabel: "Urządzenie", validForLabel: "Ważny przez", unexpectedAction: "Jeśli ta czynność nie została przez Ciebie zainicjowana, zmień hasło i skontaktuj się z pomocą techniczną.", neverShare: "Nigdy nie udostępniaj tego kodu nikomu.", supportNeverAsks: "MG AutoTech nigdy nie poprosi Cię o ten kod przez telefon ani na czacie." }, intros: { account: "Twoje bezpieczne konto klienta MG AutoTech jest gotowe.", password: "Poproszono o zresetowanie hasła do konta MG AutoTech.", request: "Twoje zlecenie MG AutoTech zostało zaktualizowane. Szczegóły znajdziesz w bezpiecznym panelu.", file: "Aktualizacja pliku została bezpiecznie zapisana przy Twoim zleceniu.", payment: "Płatność lub saldo kredytów MG AutoTech zostały zaktualizowane.", message: "MG AutoTech wysłało nową wiadomość widoczną dla klienta." }, passwordFooter: "Jeśli nie zlecałeś tej operacji, zignoruj wiadomość i nie udostępniaj bezpiecznego linku.",
    lifecycle: { fileReview: "Kontrola pliku", inProgress: "W realizacji", responseRequired: "Wymagana odpowiedź", revisionReview: "Weryfikacja poprawki", completed: "Zakończono", cancelled: "Anulowano", fileRequired: "Wymagany plik", fileReceived: "Plik odebrany", technicalReview: "Kontrola techniczna", readyForDelivery: "Gotowe do odbioru", delivered: "Dostarczono", manualReview: "Kontrola ręczna", checkMessage: "Otwórz zlecenie i sprawdź najnowszą wiadomość w panelu klienta.", uploadFile: "Otwórz zlecenie i prześlij wymagany plik wyłącznie przez panel klienta." },
    events: { accountReady: "Twoje konto klienta jest gotowe", passwordReset: "Zresetuj bezpiecznie hasło", requestCreated: "Zlecenie utworzone", requestReminder: "Dokończ zlecenie", requestReceived: "Zlecenie odebrane", fileReceived: "Plik odebrany", additionalFileRequired: "Wymagany dodatkowy plik", additionalFileReceived: "Dodatkowy plik odebrany", requestReview: "Zlecenie w weryfikacji", requestProgress: "Zlecenie w realizacji", responseRequired: "Wymagana jest Twoja odpowiedź", requestCompleted: "Zlecenie zakończone", requestDelivered: "Twój plik jest gotowy", requestCancelled: "Zlecenie anulowane", requestNotPossible: "Zlecenie obecnie niemożliwe", creditPurchase: "Zakup kredytów rozpoczęty", bankTransfer: "Dane do przelewu", paymentReceived: "Płatność otrzymana", creditsAdded: "Kredyty dodane", paymentFailed: "Płatność nieudana", paymentReview: "Płatność w weryfikacji", newMessage: "Nowa wiadomość do zlecenia", uploadEnabled: "Dodatkowe przesyłanie włączone", uploadDisabled: "Dodatkowe przesyłanie wyłączone" },
  },
  ru: {
    serviceName: "Безопасный сервис файлов ECU / TCU",
    portal: "Кабинет клиента", update: "Обновление MG AutoTech", secureNotice: "Файлы и конфиденциальные технические данные доступны только в защищённом кабинете MG AutoTech.", defaultFooter: "Это письмо содержит только информацию для клиента. Внутренние заметки и закрытые технические данные не отправляются по электронной почте.", contact: "Контакты",
    details: { reference: "Номер", customerId: "ID клиента", status: "Статус", vehicle: "Автомобиль", services: "Услуги", amount: "Сумма", credits: "Кредиты", paymentReference: "Назначение платежа", accountHolder: "Владелец счёта", bank: "Банк", file: "Файл", message: "Сообщение", actionRequired: "Требуется действие", support: "Поддержка" },
    actions: { openDashboard: "Открыть кабинет", resetPassword: "Безопасно сбросить пароль" }, deviceVerification: { subject: "MG AutoTech - Код безопасности аккаунта", preheader: "Подтвердите проверку безопасности вашего аккаунта MG AutoTech.", title: "Подтвердите проверку безопасности", intro: "Используйте этот код безопасности, чтобы безопасно продолжить работу в аккаунте клиента MG AutoTech.", securityCodeLabel: "Код безопасности", deviceLabel: "Устройство", validForLabel: "Действует в течение", unexpectedAction: "Если вы не запускали это действие, смените пароль и обратитесь в службу поддержки.", neverShare: "Никому не сообщайте этот код.", supportNeverAsks: "MG AutoTech никогда не попросит вас сообщить этот код по телефону или в чате." }, intros: { account: "Ваш защищённый аккаунт MG AutoTech готов к работе.", password: "Запрошен сброс пароля для вашего аккаунта MG AutoTech.", request: "По вашей заявке MG AutoTech есть обновление. Подробности доступны в защищённом кабинете.", file: "Обновление файла безопасно зарегистрировано для вашей заявки.", payment: "Есть обновление по платежу или балансу кредитов MG AutoTech.", message: "MG AutoTech отправил вам новое сообщение для клиента." }, passwordFooter: "Если вы не запрашивали это действие, проигнорируйте письмо и не передавайте ссылку.",
    lifecycle: { fileReview: "Проверка файла", inProgress: "В работе", responseRequired: "Требуется ответ", revisionReview: "Проверка доработки", completed: "Завершено", cancelled: "Отменено", fileRequired: "Требуется файл", fileReceived: "Файл получен", technicalReview: "Техническая проверка", readyForDelivery: "Готово к выдаче", delivered: "Доставлено", manualReview: "Ручная проверка", checkMessage: "Откройте заявку и проверьте последнее сообщение в кабинете клиента.", uploadFile: "Откройте заявку и загрузите требуемый файл только через кабинет клиента." },
    events: { accountReady: "Ваш аккаунт клиента готов", passwordReset: "Сбросить пароль", requestCreated: "Заявка создана", requestReminder: "Завершить заявку", requestReceived: "Заявка получена", fileReceived: "Файл получен", additionalFileRequired: "Требуется дополнительный файл", additionalFileReceived: "Дополнительный файл получен", requestReview: "Заявка проверяется", requestProgress: "Заявка в работе", responseRequired: "Требуется ваш ответ", requestCompleted: "Заявка завершена", requestDelivered: "Ваш файл готов", requestCancelled: "Заявка отменена", requestNotPossible: "Заявка сейчас невозможна", creditPurchase: "Покупка кредитов начата", bankTransfer: "Данные для перевода", paymentReceived: "Платёж получен", creditsAdded: "Кредиты добавлены", paymentFailed: "Платёж не прошёл", paymentReview: "Платёж проверяется", newMessage: "Новое сообщение по заявке", uploadEnabled: "Дополнительная загрузка включена", uploadDisabled: "Дополнительная загрузка отключена" },
  },
  zh: {
    serviceName: "安全 ECU / TCU 文件服务",
    portal: "客户中心", update: "MG AutoTech 更新", secureNotice: "文件和机密技术数据仅可在已登录的 MG AutoTech 安全客户中心查看。", defaultFooter: "此邮件仅包含客户可见信息。内部备注和私密技术数据不会通过邮件发送。", contact: "联系方式",
    details: { reference: "参考号", customerId: "客户编号", status: "状态", vehicle: "车辆", services: "服务", amount: "金额", credits: "积分", paymentReference: "付款附言", accountHolder: "账户持有人", bank: "银行", file: "文件", message: "消息", actionRequired: "需要操作", support: "支持" },
    actions: { openDashboard: "打开客户中心", resetPassword: "安全重置密码" }, deviceVerification: { subject: "MG AutoTech - 账户安全验证码", preheader: "请确认您的客户账户安全验证。", title: "确认此次安全验证", intro: "请使用此安全验证码，安全地继续使用您的 MG AutoTech 客户账户。", securityCodeLabel: "安全验证码", deviceLabel: "设备", validForLabel: "有效期", unexpectedAction: "如果此操作并非由您发起，请更改密码并联系支持团队。", neverShare: "切勿向任何人透露此验证码。", supportNeverAsks: "MG AutoTech 绝不会通过电话或聊天向您索取此验证码。" }, intros: { account: "您的 MG AutoTech 安全客户账户已可使用。", password: "您的 MG AutoTech 账户收到密码重置请求。", request: "您的 MG AutoTech 请求有新进展。请在安全客户中心查看详情。", file: "您的 MG AutoTech 请求已安全记录文件更新。", payment: "您的 MG AutoTech 付款或积分余额有新进展。", message: "MG AutoTech 向您发送了一条新的客户可见消息。" }, passwordFooter: "如果并非您本人请求，请忽略此邮件且不要分享安全链接。",
    lifecycle: { fileReview: "文件审核", inProgress: "处理中", responseRequired: "需要回复", revisionReview: "修订审核中", completed: "已完成", cancelled: "已取消", fileRequired: "需要文件", fileReceived: "已收到文件", technicalReview: "技术审核", readyForDelivery: "可交付", delivered: "已交付", manualReview: "人工审核", checkMessage: "请打开请求并查看客户中心中的最新消息。", uploadFile: "请打开请求，并仅通过客户中心上传所需文件。" },
    events: { accountReady: "您的客户账户已准备好", passwordReset: "安全重置密码", requestCreated: "请求已创建", requestReminder: "完成您的请求", requestReceived: "已收到请求", fileReceived: "已收到文件", additionalFileRequired: "需要补充文件", additionalFileReceived: "已收到补充文件", requestReview: "请求审核中", requestProgress: "请求处理中", responseRequired: "需要您的回复", requestCompleted: "请求已完成", requestDelivered: "您的文件已准备好", requestCancelled: "请求已取消", requestNotPossible: "当前无法完成请求", creditPurchase: "已开始购买积分", bankTransfer: "银行转账信息", paymentReceived: "已收到付款", creditsAdded: "已添加积分", paymentFailed: "付款失败", paymentReview: "付款审核中", newMessage: "新的请求消息", uploadEnabled: "已启用补充上传", uploadDisabled: "已停用补充上传" },
  },
  sq: {
    serviceName: "Shërbim i sigurt skedarësh ECU / TCU",
    portal: "Portali i klientit", update: "Përditësim MG AutoTech", secureNotice: "Skedarët dhe të dhënat teknike konfidenciale janë të disponueshme vetëm në portalin e sigurt MG AutoTech.", defaultFooter: "Ky email përmban vetëm informacion për klientin. Shënimet e brendshme dhe të dhënat teknike private nuk dërgohen me email.", contact: "Kontakt",
    details: { reference: "Referenca", customerId: "ID e klientit", status: "Statusi", vehicle: "Automjeti", services: "Shërbimet", amount: "Shuma", credits: "Kredite", paymentReference: "Referenca e pagesës", accountHolder: "Mbajtësi i llogarisë", bank: "Banka", file: "Skedari", message: "Mesazhi", actionRequired: "Kërkohet veprim", support: "Mbështetje" },
    actions: { openDashboard: "Hap panelin", resetPassword: "Rivendos fjalëkalimin" }, deviceVerification: { subject: "MG AutoTech - Kodi i sigurisë së llogarisë", preheader: "Konfirmoni kontrollin e sigurisë për llogarinë tuaj të klientit.", title: "Konfirmoni këtë kontroll sigurie", intro: "Përdoreni këtë kod sigurie për të vazhduar në mënyrë të sigurt me llogarinë tuaj të klientit MG AutoTech.", securityCodeLabel: "Kodi i sigurisë", deviceLabel: "Pajisja", validForLabel: "I vlefshëm për", unexpectedAction: "Nëse nuk e keni nisur ju këtë veprim, ndryshoni fjalëkalimin dhe kontaktoni mbështetjen.", neverShare: "Mos e ndani kurrë këtë kod me askënd.", supportNeverAsks: "MG AutoTech nuk do t’jua kërkojë kurrë këtë kod me telefon ose përmes bisedës." }, intros: { account: "Llogaria juaj e sigurt MG AutoTech është gati.", password: "U kërkua rivendosja e fjalëkalimit për llogarinë tuaj MG AutoTech.", request: "Ka një përditësim për kërkesën tuaj MG AutoTech. Hapni panelin e sigurt për hollësi.", file: "Një përditësim skedari u regjistrua në mënyrë të sigurt për kërkesën tuaj.", payment: "Ka një përditësim për pagesën ose gjendjen e krediteve MG AutoTech.", message: "MG AutoTech ju dërgoi një mesazh të ri të dukshëm për klientin." }, passwordFooter: "Nëse nuk e kërkuat këtë veprim, shpërfilleni emailin dhe mos e ndani lidhjen e sigurisë.",
    lifecycle: { fileReview: "Kontrolli i skedarit", inProgress: "Në proces", responseRequired: "Kërkohet përgjigje", revisionReview: "Rishikimi po kontrollohet", completed: "Përfunduar", cancelled: "Anuluar", fileRequired: "Kërkohet skedar", fileReceived: "Skedari u mor", technicalReview: "Kontroll teknik", readyForDelivery: "Gati për dorëzim", delivered: "Dorëzuar", manualReview: "Kontroll manual", checkMessage: "Hapni kërkesën dhe kontrolloni mesazhin më të fundit në portalin e klientit.", uploadFile: "Hapni kërkesën dhe ngarkoni skedarin e kërkuar vetëm përmes portalit të klientit." },
    events: { accountReady: "Llogaria juaj e klientit është gati", passwordReset: "Rivendosni fjalëkalimin", requestCreated: "Kërkesa u krijua", requestReminder: "Përfundoni kërkesën", requestReceived: "Kërkesa u mor", fileReceived: "Skedari u mor", additionalFileRequired: "Kërkohet skedar shtesë", additionalFileReceived: "Skedari shtesë u mor", requestReview: "Kërkesa po shqyrtohet", requestProgress: "Kërkesa është në proces", responseRequired: "Kërkohet përgjigjja juaj", requestCompleted: "Kërkesa u përfundua", requestDelivered: "Skedari juaj është gati", requestCancelled: "Kërkesa u anulua", requestNotPossible: "Kërkesa nuk mund të kryhet tani", creditPurchase: "Blerja e krediteve filloi", bankTransfer: "Të dhënat e transfertës", paymentReceived: "Pagesa u mor", creditsAdded: "Kreditet u shtuan", paymentFailed: "Pagesa dështoi", paymentReview: "Pagesa po kontrollohet", newMessage: "Mesazh i ri për kërkesën", uploadEnabled: "Ngarkimi shtesë u aktivizua", uploadDisabled: "Ngarkimi shtesë u çaktivizua" },
  },
};
