"use client";

import Link from "next/link";
import { useCallback, useEffect, useMemo, useState } from "react";
import { useParams } from "next/navigation";
import { ArrowLeft, Ban, CheckCircle2, ExternalLink, KeyRound, Loader2, RefreshCw, Save, XCircle } from "lucide-react";
import { EmbedCodeBox } from "@/components/widget/EmbedCodeBox";
import { supabase } from "@/lib/supabaseClient";
import { widgetLanguageCodes, type WidgetClient, type WidgetLanguage } from "@/lib/widget/types";

type ApiKey = { id: string; public_key: string; is_active: boolean; created_at: string; revoked_at: string | null };
type AccessLog = { id: string; request_domain: string | null; path: string | null; language: string | null; status: string; block_reason: string | null; created_at: string };
type DomainRequest = { id: string; old_domain: string | null; requested_domain: string; status: string; admin_note: string | null; created_at: string };
type AuditLog = { id: string; action: string; details: Record<string, unknown>; created_at: string };
type DetailPayload = { client: WidgetClient; keys: ApiKey[]; logs: AccessLog[]; domainRequests: DomainRequest[]; auditLogs: AuditLog[] };
const siteUrl = (process.env.NEXT_PUBLIC_SITE_URL || "https://file.mgautotech.de").replace(/\/$/, "");

export default function AdminWidgetClientDetailPage() {
  const params = useParams<{ id: string }>(); const id = params.id;
  const [data, setData] = useState<DetailPayload | null>(null); const [loading, setLoading] = useState(true); const [saving, setSaving] = useState(false); const [message, setMessage] = useState("");
  const authFetch = useCallback(async (url: string, init?: RequestInit) => { const token = (await supabase.auth.getSession()).data.session?.access_token; if (!token) throw new Error("Unauthorized"); return fetch(url, { ...init, headers: { ...(init?.headers ?? {}), Authorization: `Bearer ${token}` } }); }, []);
  const load = useCallback(async () => { try { const response = await authFetch(`/api/admin/widget-clients/${id}`, { cache: "no-store" }); const payload = await response.json(); if (response.status === 401 || response.status === 403) { window.location.href = "/login"; return; } if (!response.ok) throw new Error(payload.error); setData(payload); } catch (error) { if (error instanceof Error && error.message === "Unauthorized") { window.location.href = "/login"; return; } setMessage(error instanceof Error ? error.message : "Client could not be loaded."); } finally { setLoading(false); } }, [authFetch, id]);
  useEffect(() => { void Promise.resolve().then(load); }, [load]);
  const client = data?.client; const activeKey = data?.keys.find((key) => key.is_active)?.public_key ?? "";
  const scriptCode = `<div id="mga-vehicle-lookup"></div>\n<script src="${siteUrl}/widget/vehicle-lookup.js" data-client-key="${activeKey}" data-target="#mga-vehicle-lookup"></script>`;
  const iframeCode = `<iframe src="${siteUrl}/embed/vehicle-selector?key=${activeKey}" style="width:100%;height:700px;border:0;border-radius:12px;" loading="lazy"></iframe>`;
  const blockedDomains = useMemo(() => [...new Set((data?.logs ?? []).filter((log) => log.status === "blocked").map((log) => log.request_domain).filter(Boolean))], [data]);
  function update(key: keyof WidgetClient, value: unknown) { setData((current) => current ? { ...current, client: { ...current.client, [key]: value } } : current); }
  async function save() { if (!client) return; setSaving(true); setMessage(""); const response = await authFetch(`/api/admin/widget-clients/${id}`, { method: "PATCH", headers: { "Content-Type": "application/json" }, body: JSON.stringify(client) }); const payload = await response.json(); setSaving(false); if (!response.ok) { setMessage(payload.error || "Client could not be saved."); return; } setData((current) => current ? { ...current, client: payload.client } : current); setMessage("Widget client saved and audited."); }
  async function action(name: string, extra: Record<string, unknown> = {}) { setMessage(""); const response = await authFetch(`/api/admin/widget-clients/${id}`, { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ action: name, ...extra }) }); const payload = await response.json(); if (!response.ok) { setMessage(payload.error || "Action failed."); return; } setMessage(`Action completed: ${name}`); await load(); }
  if (loading) return <main className="flex min-h-screen items-center justify-center bg-[#050505] text-white"><Loader2 className="mr-3 h-6 w-6 animate-spin text-red-500" />Loading widget client...</main>;
  if (!client || !data) return <main className="min-h-screen bg-[#050505] p-10 text-white"><Link href="/admin/widget-clients">Back</Link><div className="mt-10 text-red-300">{message || "Client not found."}</div></main>;
  return <main className="min-h-screen bg-[#050505] text-white"><header className="border-b border-white/10"><div className="mx-auto flex max-w-[1500px] flex-col gap-4 px-4 py-5 sm:flex-row sm:items-center sm:justify-between"><div><Link href="/admin/widget-clients" className="text-sm font-black text-zinc-500"><ArrowLeft className="mr-2 inline h-4 w-4" />Widget clients</Link><h1 className="mt-2 text-2xl font-black sm:text-3xl">{client.company_name}</h1><div className="mt-1 text-sm text-zinc-500">{client.email} · {client.allowed_domain}</div></div><div className="flex flex-wrap gap-2"><button onClick={() => action("activate")} className="rounded-lg border border-emerald-700/40 bg-emerald-950/25 px-3 py-2.5 text-xs font-black text-emerald-300"><CheckCircle2 className="mr-2 inline h-4 w-4" />Activate</button><button onClick={() => action("suspend")} className="rounded-lg border border-amber-700/40 bg-amber-950/25 px-3 py-2.5 text-xs font-black text-amber-300"><Ban className="mr-2 inline h-4 w-4" />Suspend</button><button onClick={() => action("cancel")} className="rounded-lg border border-red-800/40 bg-red-950/25 px-3 py-2.5 text-xs font-black text-red-300"><XCircle className="mr-2 inline h-4 w-4" />Cancel access</button></div></div></header>
  <section className="mx-auto max-w-[1500px] px-4 py-8">{message && <div className="mb-6 border border-red-800/40 bg-red-950/20 p-4 text-sm">{message}</div>}<div className="mb-8 grid gap-3 sm:grid-cols-4"><Metric label="Local status" value={client.status} /><Metric label="Stripe status" value={client.stripe_subscription_status || "manual"} /><Metric label="Plan" value={client.plan} /><Metric label="Monthly limit" value={client.monthly_usage_limit.toLocaleString()} /></div>
    <div className="grid gap-8 xl:grid-cols-[1fr_390px]"><div className="min-w-0 space-y-8"><FormSection title="Client and subscription"><div className="grid gap-4 sm:grid-cols-2 lg:grid-cols-3"><Field label="Company name" value={client.company_name} onChange={(v) => update("company_name", v)} /><Field label="Email" value={client.email} onChange={(v) => update("email", v)} type="email" /><Select label="Status" value={client.status} onChange={(v) => update("status", v)} options={["pending","active","past_due","suspended","cancelled"]} /><Select label="Plan" value={client.plan} onChange={(v) => update("plan", v)} options={["starter","pro","white_label"]} /><NumberField label="Monthly price" value={client.monthly_price} onChange={(v) => update("monthly_price", v)} /><Field label="Currency" value={client.currency} onChange={(v) => update("currency", v)} /></div><div className="mt-4 grid gap-2 sm:grid-cols-2 lg:grid-cols-3"><Toggle label="Widget enabled" checked={client.widget_enabled} onChange={(v) => update("widget_enabled", v)} /><Toggle label="Domain verified" checked={client.domain_verified} onChange={(v) => update("domain_verified", v)} /></div></FormSection>
      <FormSection title="Domain security"><div className="grid gap-4 sm:grid-cols-2"><Field label="Website domain" value={client.website_domain} onChange={(v) => update("website_domain", v)} /><Field label="Allowed domain" value={client.allowed_domain} onChange={(v) => update("allowed_domain", v)} /></div><div className="mt-4 grid gap-2 sm:grid-cols-2"><Toggle label="Allow www alias" checked={client.allow_www_alias} onChange={(v) => update("allow_www_alias", v)} /><Toggle label="Allow subdomains" checked={client.allow_subdomains} onChange={(v) => update("allow_subdomains", v)} /></div>{blockedDomains.length > 0 && <div className="mt-5"><div className="text-xs font-black uppercase text-red-400">Blocked domains</div><div className="mt-2 flex flex-wrap gap-2">{blockedDomains.map((domain) => <span key={domain} className="rounded-lg border border-red-800/30 bg-red-950/20 px-3 py-2 text-xs font-bold text-red-200">{domain}</span>)}</div></div>}</FormSection>
      <FormSection title="Widget appearance and contact"><div className="grid gap-4 sm:grid-cols-2 lg:grid-cols-3"><Field label="Widget title" value={client.widget_title} onChange={(v) => update("widget_title", v)} /><Field label="Button text" value={client.button_text} onChange={(v) => update("button_text", v)} /><Select label="Theme" value={client.theme_mode} onChange={(v) => update("theme_mode", v)} options={["light","dark","auto"]} /><Field label="Main colour" value={client.main_color} onChange={(v) => update("main_color", v)} /><Field label="Button text colour" value={client.button_text_color} onChange={(v) => update("button_text_color", v)} /><Field label="Highlight colour" value={client.difference_color} onChange={(v) => update("difference_color", v)} /><Field label="Enquiry email" value={client.enquiry_email || ""} onChange={(v) => update("enquiry_email", v)} type="email" /><Field label="WhatsApp number" value={client.whatsapp_number || ""} onChange={(v) => update("whatsapp_number", v)} /><NumberField label="Monthly usage limit" value={client.monthly_usage_limit} onChange={(v) => update("monthly_usage_limit", Math.round(v))} /></div><div className="mt-5"><div className="mb-2 text-xs font-black uppercase text-zinc-500">Allowed languages</div><div className="flex flex-wrap gap-2">{widgetLanguageCodes.map((code) => <button type="button" key={code} onClick={() => update("allowed_languages", client.allowed_languages.includes(code) ? client.allowed_languages.filter((item) => item !== code) : [...client.allowed_languages, code])} className={`rounded-lg border px-3 py-2 text-xs font-black ${client.allowed_languages.includes(code) ? "border-red-700 bg-red-950/30" : "border-white/10 text-zinc-600"}`}>{code.toUpperCase()}</button>)}</div><Select label="Default language" value={client.default_language} onChange={(v) => update("default_language", v as WidgetLanguage)} options={client.allowed_languages} /></div></FormSection>
      <FormSection title="Client permissions"><div className="grid gap-2 sm:grid-cols-2 lg:grid-cols-3">{[["show_branding","Show branding"],["allow_script_embed","Allow script embed"],["allow_iframe_embed","Allow iframe embed"],["can_edit_colours","Can edit colours"],["can_edit_language","Can edit language"],["can_edit_contact","Can edit contact"],["can_hide_branding","Can hide branding"]].map(([key,label]) => <Toggle key={key} label={label} checked={Boolean(client[key as keyof WidgetClient])} onChange={(v) => update(key as keyof WidgetClient, v)} />)}</div></FormSection>
      <button onClick={save} disabled={saving} className="flex h-13 w-full items-center justify-center rounded-lg bg-[#b1121b] px-6 text-sm font-black disabled:opacity-50">{saving ? <Loader2 className="h-4 w-4 animate-spin" /> : <><Save className="mr-2 h-4 w-4" />Save client settings</>}</button>
      <FormSection title="Access logs"><div className="overflow-x-auto"><table className="w-full min-w-[760px] text-left text-xs"><thead className="uppercase text-zinc-600"><tr><th className="py-3">Time</th><th>Domain</th><th>Path</th><th>Status</th><th>Reason</th><th>Lang</th></tr></thead><tbody>{data.logs.map((log) => <tr key={log.id} className="border-t border-white/10"><td className="py-3 pr-3 text-zinc-500">{new Date(log.created_at).toLocaleString()}</td><td className="pr-3 font-bold">{log.request_domain || "-"}</td><td className="max-w-48 truncate pr-3 text-zinc-400">{log.path}</td><td className={log.status === "allowed" ? "font-black text-emerald-400" : "font-black text-red-400"}>{log.status}</td><td className="pr-3 text-zinc-400">{log.block_reason || "-"}</td><td>{log.language || "-"}</td></tr>)}</tbody></table>{!data.logs.length && <div className="py-8 text-center text-sm text-zinc-600">No access logs yet.</div>}</div></FormSection>
      <FormSection title="Audit history"><div className="space-y-2">{data.auditLogs.map((log) => <div key={log.id} className="flex items-center justify-between gap-4 border-t border-white/10 py-3 text-sm"><div className="font-black">{log.action}</div><div className="shrink-0 text-xs text-zinc-600">{new Date(log.created_at).toLocaleString()}</div></div>)}</div></FormSection></div>
      <aside className="space-y-7"><FormSection title="Public API key"><div className="break-all rounded-lg border border-white/10 bg-black/40 p-4 font-mono text-xs text-red-200">{activeKey || "No active key"}</div><div className="mt-3 grid grid-cols-2 gap-2"><button onClick={() => action("regenerate_key")} className="rounded-lg border border-white/10 px-3 py-3 text-xs font-black"><RefreshCw className="mr-2 inline h-4 w-4" />Regenerate</button><button onClick={() => action("revoke_key")} disabled={!activeKey} className="rounded-lg border border-red-800/40 px-3 py-3 text-xs font-black text-red-300 disabled:opacity-40"><KeyRound className="mr-2 inline h-4 w-4" />Revoke</button></div></FormSection>{activeKey && <FormSection title="Embed code"><EmbedCodeBox title="Script" code={scriptCode} /><div className="mt-5"><EmbedCodeBox title="Iframe" code={iframeCode} /></div></FormSection>}
      <FormSection title="Stripe"><div className="space-y-3 text-sm"><Row label="Customer" value={client.stripe_customer_id || "-"} /><Row label="Subscription" value={client.stripe_subscription_id || "-"} /><Row label="Status" value={client.stripe_subscription_status || "Manual"} /></div>{client.stripe_customer_id && <a href={`https://dashboard.stripe.com/customers/${client.stripe_customer_id}`} target="_blank" rel="noreferrer" className="mt-4 flex h-11 items-center justify-center rounded-lg border border-white/10 text-xs font-black">Open Stripe customer<ExternalLink className="ml-2 h-4 w-4" /></a>}</FormSection>
      <FormSection title="Domain change requests"><div className="space-y-3">{data.domainRequests.map((request) => <div key={request.id} className="rounded-lg border border-white/10 p-4"><div className="text-xs text-zinc-600">{request.old_domain || "-"} →</div><div className="mt-1 break-all font-black">{request.requested_domain}</div><div className="mt-2 text-xs font-black uppercase text-amber-300">{request.status}</div>{request.status === "pending" && <div className="mt-3 flex gap-2"><button onClick={() => action("approve_domain", { requestId: request.id })} className="flex-1 rounded-lg bg-emerald-700 px-3 py-2 text-xs font-black">Approve</button><button onClick={() => action("reject_domain", { requestId: request.id })} className="flex-1 rounded-lg bg-red-800 px-3 py-2 text-xs font-black">Reject</button></div>}</div>)}{!data.domainRequests.length && <div className="text-sm text-zinc-600">No domain requests.</div>}</div></FormSection></aside></div>
  </section></main>;
}
function FormSection({ title, children }: { title: string; children: React.ReactNode }) { return <section className="border-t border-white/10 pt-5"><h2 className="mb-5 text-xl font-black">{title}</h2>{children}</section>; }
function Field({ label, value, onChange, type = "text" }: { label: string; value: string; onChange: (value: string) => void; type?: string }) { return <label className="block text-xs font-black uppercase text-zinc-500">{label}<input type={type} value={value} onChange={(e) => onChange(e.target.value)} className="mt-2 h-11 w-full rounded-lg border border-white/10 bg-black/30 px-3 text-sm font-bold text-white" /></label>; }
function NumberField({ label, value, onChange }: { label: string; value: number; onChange: (value: number) => void }) { return <label className="block text-xs font-black uppercase text-zinc-500">{label}<input type="number" min="0" step="0.01" value={value} onChange={(e) => onChange(Number(e.target.value))} className="mt-2 h-11 w-full rounded-lg border border-white/10 bg-black/30 px-3 text-sm font-bold text-white" /></label>; }
function Select({ label, value, onChange, options }: { label: string; value: string; onChange: (value: string) => void; options: readonly string[] | string[] }) { return <label className="mt-4 block text-xs font-black uppercase text-zinc-500">{label}<select value={value} onChange={(e) => onChange(e.target.value)} className="mt-2 h-11 w-full rounded-lg border border-white/10 bg-black/30 px-3 text-sm font-bold text-white">{options.map((item) => <option key={item} value={item}>{item}</option>)}</select></label>; }
function Toggle({ label, checked, onChange }: { label: string; checked: boolean; onChange: (value: boolean) => void }) { return <label className="flex items-center justify-between gap-3 rounded-lg border border-white/10 bg-white/[0.025] p-3 text-xs font-black"><span>{label}</span><input type="checkbox" checked={checked} onChange={(e) => onChange(e.target.checked)} className="h-4 w-4 accent-red-600" /></label>; }
function Metric({ label, value }: { label: string; value: string }) { return <div className="border-l border-red-800/50 bg-white/[0.025] p-4"><div className="text-xs font-black uppercase text-zinc-600">{label}</div><div className="mt-2 truncate font-black">{value}</div></div>; }
function Row({ label, value }: { label: string; value: string }) { return <div className="flex items-start justify-between gap-3"><span className="text-zinc-600">{label}</span><span className="max-w-[230px] break-all text-right font-bold">{value}</span></div>; }
