// This file is generated by scripts/generate-customer-workflow-client-translations.ts.
// Edit the master catalog or group source inventory, then regenerate it.

import type { LocaleCode } from "@/lib/i18nConfig";
import {
  createCustomerWorkflowClientTranslators,
} from "@/lib/i18n/customer-workflow-client-runtime";

export const customerWorkflowLocaleOrder = [
  "nl",
  "de",
  "fr",
  "it",
  "ru",
  "es",
  "tr",
  "pt",
  "zh",
  "pl",
  "sq"
] as const satisfies readonly Exclude<LocaleCode, "en">[];

export const customerWorkflowExactTranslations = {} as const satisfies Readonly<Record<string, readonly string[]>>;

export const customerWorkflowSourceStrings = Object.keys(customerWorkflowExactTranslations);

export const customerWorkflowTemplateRows = [] as const;

export type CustomerWorkflowTranslationKey = (typeof customerWorkflowTemplateRows)[number][0];

const translators = createCustomerWorkflowClientTranslators(
  customerWorkflowExactTranslations,
  customerWorkflowTemplateRows,
);

export function customerWorkflowExactT(locale: LocaleCode, source: string) {
  return translators.exactT(locale, source);
}

export function customerWorkflowT(
  locale: LocaleCode,
  key: CustomerWorkflowTranslationKey,
  values: Record<string, string | number> = {},
) {
  return translators.t(locale, key, values);
}
