// This file is generated by scripts/generate-customer-workflow-client-translations.ts.
// Edit the master catalog or group source inventory, then regenerate it.

import type { LocaleCode } from "@/lib/i18nConfig";
import {
  createCustomerWorkflowClientTranslators,
} from "@/lib/i18n/customer-workflow-client-runtime";

export const customerWorkflowLocaleOrder = [
  "nl",
  "de",
  "fr",
  "it",
  "ru",
  "es",
  "tr",
  "pt",
  "zh",
  "pl",
  "sq"
] as const satisfies readonly Exclude<LocaleCode, "en">[];

export const customerWorkflowExactTranslations = {} as const satisfies Readonly<Record<string, readonly string[]>>;

export const customerWorkflowSourceStrings = Object.keys(customerWorkflowExactTranslations);

export const customerWorkflowTemplateRows = [
  [
    "createSimilarRequest",
    "Create a similar request for {vehicle}",
    "Maak een vergelijkbare aanvraag voor {vehicle}",
    "Erstellen Sie eine ähnliche Anfrage für {vehicle}",
    "Créer une demande similaire pour {vehicle}",
    "Crea una richiesta simile per {vehicle}",
    "Создать аналогичную заявку для {vehicle}",
    "Cree una solicitud similar para {vehicle}",
    "{vehicle} için benzer bir talep oluşturun",
    "Crie um pedido semelhante para {vehicle}",
    "为 {vehicle} 创建类似的请求",
    "Utwórz podobne zlecenie dla {vehicle}",
    "Krijo një kërkesë të ngjashme për {vehicle}"
  ],
  [
    "creditsCountLower",
    "{count} credits",
    "{count} credits",
    "{count} Credits",
    "{count} crédits",
    "{count} crediti",
    "Кредитов: {count}",
    "{count} créditos",
    "{count} kredi",
    "{count} créditos",
    "{count} 积分",
    "{count} kredytów",
    "{count} kredite"
  ],
  [
    "downloadFile",
    "Download {label} file",
    "Download het {label}-bestand",
    "Laden Sie die Datei {label} herunter",
    "Télécharger le fichier {label}",
    "Scarica il file {label}",
    "Скачать файл {label}",
    "Descargar el archivo {label}",
    "{label} dosyasını indir",
    "Descarregar ficheiro {label}",
    "下载{label}文件",
    "Pobierz plik {label}",
    "Shkarko skedarin {label}"
  ],
  [
    "downloadLabel",
    "Download {label}",
    "Download {label}",
    "Laden Sie {label} herunter",
    "Télécharger {label}",
    "Scarica {label}",
    "Скачать {label}",
    "Descargar {label}",
    "{label}'ı indirin",
    "Descarregar {label}",
    "下载{label}",
    "Pobierz {label}",
    "Shkarko {label}"
  ],
  [
    "downloadUploadedFile",
    "Download uploaded file {fileName}",
    "Download geüpload bestand {fileName}",
    "Hochgeladene Datei {fileName} herunterladen",
    "Télécharger le fichier téléversé {fileName}",
    "Scarica il file caricato {fileName}",
    "Скачать загруженный файл {fileName}",
    "Descargar el archivo cargado {fileName}",
    "Yüklenen {fileName} dosyasını indir",
    "Descarregar o ficheiro enviado {fileName}",
    "下载上传的文件 {fileName}",
    "Pobierz przesłany plik {fileName}",
    "Shkarko skedarin e ngarkuar {fileName}"
  ],
  [
    "fallbackVehicle",
    "vehicle",
    "Voertuig",
    "Fahrzeug",
    "Véhicule",
    "Veicolo",
    "Автомобиль",
    "Vehículo",
    "Araç",
    "Veículo",
    "车辆",
    "Pojazd",
    "Automjeti"
  ],
  [
    "lastRequest",
    "Last request {date}",
    "Laatste aanvraag {date}",
    "Letzte Anfrage am {date}",
    "Dernière demande {date}",
    "Ultima richiesta {date}",
    "Последняя заявка {date}",
    "Última solicitud {date}",
    "Son talep {date}",
    "Último pedido: {date}",
    "上次请求 {date}",
    "Ostatnie zlecenie {date}",
    "Kërkesa e fundit {date}"
  ],
  [
    "loadNextOrders",
    "Load next {count} orders",
    "Volgende {count} orders laden",
    "Nächste {count} Aufträge laden",
    "Charger les {count} commandes suivantes",
    "Carica i prossimi {count} ordini",
    "Загрузить следующие заказы: {count}",
    "Cargar los {count} pedidos siguientes",
    "Sonraki {count} siparişi yükle",
    "Carregar os {count} pedidos seguintes",
    "加载接下来的 {count} 个订单",
    "Wczytaj kolejnych {count} zleceń",
    "Ngarko {count} porositë e ardhshme"
  ],
  [
    "receivedCount",
    "{count} received",
    "{count} ontvangen",
    "{count} empfangen",
    "{count} reçus",
    "{count} ricevuto",
    "{count} получено",
    "{count} recibida",
    "{count} alındı",
    "{count} recebidos",
    "已收到 {count} 个",
    "Otrzymano {count}",
    "{count} është marrë"
  ],
  [
    "requestCount",
    "{total} requests in this view. Only {pageSize} are loaded at a time.",
    "{total} aanvragen in deze weergave. Er worden slechts {pageSize} tegelijk geladen.",
    "{total} Anfragen in dieser Ansicht. Es werden jeweils nur {pageSize} geladen.",
    "{total} demandes dans cette vue. Seules {pageSize} sont chargées à la fois.",
    "{total} richieste in questa visualizzazione. Vengono caricati solo {pageSize} alla volta.",
    "{total} заявок в этом представлении. Одновременно загружается только {pageSize}.",
    "{total} solicitudes en esta vista. Solo se cargan {pageSize} a la vez.",
    "Bu görünümde {total} talep var. Aynı anda yalnızca {pageSize} yüklenir.",
    "{total} pedidos nesta vista. Apenas {pageSize} são carregados de cada vez.",
    "此视图中有 {total} 个请求。一次仅加载 {pageSize}。",
    "Liczba zleceń w tym widoku: {total}. Jednorazowo ładowanych jest tylko {pageSize}.",
    "{total} kërkesa në këtë pamje. Vetëm {pageSize} ngarkohen në të njëjtën kohë."
  ],
  [
    "serviceNotSet",
    "Service not set",
    "Geen service geselecteerd",
    "Service nicht ausgewählt",
    "Service non sélectionné",
    "Servizio non selezionato",
    "Услуга не выбрана",
    "Servicio no seleccionado",
    "Hizmet seçilmedi",
    "Serviço não selecionado",
    "未选择服务",
    "Nie wybrano usługi",
    "Shërbimi nuk është zgjedhur"
  ],
  [
    "supportSummary",
    "MG AutoTech request: #{requestId}\nStatus: {status}\nVehicle: {vehicle}\nService: {service}\nCreated: {created}",
    "MG AutoTech-aanvraag: #{requestId}\nStatus: {status}\nVoertuig: {vehicle}\nService: {service}\nAangemaakt: {created}",
    "MG AutoTech-Anfrage: #{requestId}\nStatus: {status}\nFahrzeug: {vehicle}\nService: {service}\nErstellt: {created}",
    "Demande MG AutoTech : #{requestId}\nStatut : {status}\nVéhicule : {vehicle}\nService : {service}\nCréée le : {created}",
    "Richiesta MG AutoTech: #{requestId}\nStato: {status}\nVeicolo: {vehicle}\nServizio: {service}\nCreata: {created}",
    "Заявка MG AutoTech: #{requestId}\nСтатус: {status}\nАвтомобиль: {vehicle}\nУслуга: {service}\nСоздана: {created}",
    "Solicitud de MG AutoTech: #{requestId}\nEstado: {status}\nVehículo: {vehicle}\nServicio: {service}\nCreada: {created}",
    "MG AutoTech talebi: #{requestId}\nDurum: {status}\nAraç: {vehicle}\nHizmet: {service}\nOluşturulma: {created}",
    "Pedido MG AutoTech: #{requestId}\nEstado: {status}\nVeículo: {vehicle}\nServiço: {service}\nCriado: {created}",
    "MG AutoTech 请求：#{requestId}\n状态：{status}\n车辆：{vehicle}\n服务：{service}\n创建时间：{created}",
    "Zlecenie MG AutoTech: #{requestId}\nStatus: {status}\nPojazd: {vehicle}\nUsługa: {service}\nUtworzono: {created}",
    "Kërkesa MG AutoTech: #{requestId}\nStatusi: {status}\nAutomjeti: {vehicle}\nShërbimi: {service}\nKrijuar: {created}"
  ],
  [
    "thisVehicle",
    "this vehicle",
    "dit voertuig",
    "dieses Fahrzeug",
    "ce véhicule",
    "questo veicolo",
    "этот автомобиль",
    "este vehículo",
    "bu araç",
    "este veículo",
    "这辆车",
    "ten pojazd",
    "këtë automjet"
  ],
  [
    "updatedAt",
    "Updated {time}",
    "{time} bijgewerkt",
    "Aktualisiert {time}",
    "Mis à jour {time}",
    "{time} aggiornato",
    "Обновлено {time}",
    "Actualizado {time}",
    "{time} güncellendi",
    "Atualizado {time}",
    "更新{time}",
    "Zaktualizowano {time}",
    "Përditësuar {time}"
  ],
  [
    "vehicleNotSet",
    "Vehicle not set",
    "Voertuig niet ingesteld",
    "Fahrzeug nicht angegeben",
    "Véhicule non renseigné",
    "Veicolo non impostato",
    "Автомобиль не указан",
    "Vehículo no indicado",
    "Araç belirtilmedi",
    "Veículo não definido",
    "未设置车辆",
    "Nie podano pojazdu",
    "Automjeti nuk është përcaktuar"
  ]
] as const;

export type CustomerWorkflowTranslationKey = (typeof customerWorkflowTemplateRows)[number][0];

const translators = createCustomerWorkflowClientTranslators(
  customerWorkflowExactTranslations,
  customerWorkflowTemplateRows,
);

export function customerWorkflowExactT(locale: LocaleCode, source: string) {
  return translators.exactT(locale, source);
}

export function customerWorkflowT(
  locale: LocaleCode,
  key: CustomerWorkflowTranslationKey,
  values: Record<string, string | number> = {},
) {
  return translators.t(locale, key, values);
}
