// This file is generated by scripts/generate-customer-workflow-client-translations.ts.
// Edit the master catalog or group source inventory, then regenerate it.

import type { LocaleCode } from "@/lib/i18nConfig";
import {
  createCustomerWorkflowClientTranslators,
} from "@/lib/i18n/customer-workflow-client-runtime";

export const customerWorkflowLocaleOrder = [
  "nl",
  "de",
  "fr",
  "it",
  "ru",
  "es",
  "tr",
  "pt",
  "zh",
  "pl",
  "sq"
] as const satisfies readonly Exclude<LocaleCode, "en">[];

export const customerWorkflowExactTranslations = {} as const satisfies Readonly<Record<string, readonly string[]>>;

export const customerWorkflowSourceStrings = Object.keys(customerWorkflowExactTranslations);

export const customerWorkflowTemplateRows = [
  [
    "stopTrustingDevice",
    "Stop trusting {device}?",
    "{device} niet meer vertrouwen?",
    "Diesem Gerät nicht mehr vertrauen: {device}?",
    "Ne plus faire confiance à {device} ?",
    "Non considerare più attendibile {device}?",
    "Перестать доверять устройству {device}?",
    "¿Dejar de confiar en {device}?",
    "{device} cihazına güvenmeyi bırakmak istiyor musunuz?",
    "Deixar de confiar em {device}?",
    "不再信任 {device}？",
    "Przestać ufać urządzeniu {device}?",
    "Të mos i besohet më pajisjes {device}?"
  ],
  [
    "stopTrustingOtherDevices",
    "Stop trusting every other saved device?",
    "Alle andere opgeslagen apparaten niet meer vertrouwen?",
    "Allen anderen gespeicherten Geräten nicht mehr vertrauen?",
    "Ne plus faire confiance à aucun autre appareil enregistré ?",
    "Interrompere l’attendibilità di tutti gli altri dispositivi salvati?",
    "Перестать доверять всем остальным сохранённым устройствам?",
    "¿Dejar de confiar en todos los demás dispositivos guardados?",
    "Kaydedilmiş diğer tüm cihazlara güvenmeyi durdurmak istiyor musunuz?",
    "Deixar de confiar em todos os outros dispositivos guardados?",
    "停止信任所有其他已保存的设备？",
    "Przestać ufać wszystkim pozostałym zapisanym urządzeniom?",
    "Të hiqet besimi për të gjitha pajisjet e tjera të ruajtura?"
  ],
  [
    "trustedDeviceDates",
    "Last used {lastUsed} · Trusted until {trustedUntil}",
    "Laatst gebruikt {lastUsed} · Vertrouwd tot {trustedUntil}",
    "Zuletzt verwendet: {lastUsed} · Vertrauenswürdig bis {trustedUntil}",
    "Dernière utilisation : {lastUsed} · Appareil approuvé jusqu’au {trustedUntil}",
    "Ultimo utilizzo: {lastUsed} · Attendibile fino al {trustedUntil}",
    "Последнее использование: {lastUsed} · Доверие до: {trustedUntil}",
    "Último uso: {lastUsed} · De confianza hasta {trustedUntil}",
    "Son kullanım: {lastUsed} · Güven süresi: {trustedUntil}",
    "Última utilização: {lastUsed} · De confiança até {trustedUntil}",
    "上次使用：{lastUsed} · 信任至：{trustedUntil}",
    "Ostatnio używane: {lastUsed} · Zaufane do: {trustedUntil}",
    "Përdorur për herë të fundit: {lastUsed} · I besuar deri më: {trustedUntil}"
  ],
  [
    "unknownValue",
    "Unknown",
    "Onbekend",
    "Unbekannt",
    "Inconnu",
    "Sconosciuto",
    "Неизвестно",
    "Desconocido",
    "Bilinmiyor",
    "Desconhecido",
    "未知",
    "Nieznane",
    "E panjohur"
  ]
] as const;

export type CustomerWorkflowTranslationKey = (typeof customerWorkflowTemplateRows)[number][0];

const translators = createCustomerWorkflowClientTranslators(
  customerWorkflowExactTranslations,
  customerWorkflowTemplateRows,
);

export function customerWorkflowExactT(locale: LocaleCode, source: string) {
  return translators.exactT(locale, source);
}

export function customerWorkflowT(
  locale: LocaleCode,
  key: CustomerWorkflowTranslationKey,
  values: Record<string, string | number> = {},
) {
  return translators.t(locale, key, values);
}
