// This file is generated by scripts/generate-customer-workflow-client-translations.ts.
// It contains only DOM-observer copy for the widget surface.

import type { LocaleCode } from "@/lib/i18nConfig";

export const customerWorkflowLocaleOrder = [
  "nl",
  "de",
  "fr",
  "it",
  "ru",
  "es",
  "tr",
  "pt",
  "zh",
  "pl",
  "sq"
] as const satisfies readonly Exclude<LocaleCode, "en">[];

export const customerWorkflowExactTranslations = {
  "Contact support": [
    "Contact opnemen met support",
    "Support kontaktieren",
    "Contacter l'assistance",
    "Contatta l'assistenza",
    "Связаться с поддержкой",
    "Contactar con soporte",
    "Destek ile iletişime geç",
    "Contactar o suporte",
    "联系支持",
    "Skontaktuj się z pomocą",
    "Kontakto mbështetjen"
  ],
  "Open billing portal": [
    "Facturatieportaal openen",
    "Abrechnungsportal öffnen",
    "Ouvrir le portail de facturation",
    "Apri il portale di fatturazione",
    "Открыть платёжный портал",
    "Abrir portal de facturación",
    "Faturalandırma portalını aç",
    "Abrir portal de faturação",
    "打开账单门户",
    "Otwórz portal rozliczeń",
    "Hap portalin e faturimit"
  ],
  "Review the linked subscription, latest payment, next renewal and remaining period before opening the Stripe Customer Portal.": [
    "Controleer het gekoppelde abonnement, de laatste betaling, de volgende verlenging en de resterende looptijd voordat u het Stripe-klantportaal opent.",
    "Prüfen Sie das verknüpfte Abonnement, die letzte Zahlung, die nächste Verlängerung und die Restlaufzeit, bevor Sie das Stripe-Kundenportal öffnen.",
    "Vérifiez l'abonnement lié, le dernier paiement, le prochain renouvellement et la période restante avant d'ouvrir le portail client Stripe.",
    "Controlla l'abbonamento collegato, l'ultimo pagamento, il prossimo rinnovo e il periodo residuo prima di aprire il portale clienti Stripe.",
    "Проверьте связанную подписку, последний платёж, следующее продление и оставшийся срок перед открытием клиентского портала Stripe.",
    "Revise la suscripción vinculada, el último pago, la próxima renovación y el periodo restante antes de abrir el portal de Stripe.",
    "Stripe müşteri portalını açmadan önce bağlı aboneliği, son ödemeyi, sonraki yenilemeyi ve kalan süreyi kontrol edin.",
    "Verifique a subscrição associada, o último pagamento, a próxima renovação e o período restante antes de abrir o portal Stripe.",
    "打开 Stripe 客户门户前，请检查关联订阅、最近付款、下次续订和剩余期限。",
    "Przed otwarciem portalu Stripe sprawdź powiązaną subskrypcję, ostatnią płatność, kolejne odnowienie i pozostały okres.",
    "Kontrolloni abonimin e lidhur, pagesën e fundit, rinovimin e ardhshëm dhe periudhën e mbetur para hapjes së portalit Stripe."
  ],
  "Secure billing managed by Stripe": [
    "Veilige facturatie via Stripe",
    "Sichere Abrechnung über Stripe",
    "Facturation sécurisée gérée par Stripe",
    "Fatturazione sicura gestita da Stripe",
    "Безопасная оплата через Stripe",
    "Facturación segura gestionada por Stripe",
    "Stripe tarafından yönetilen güvenli faturalandırma",
    "Faturação segura gerida pela Stripe",
    "由 Stripe 管理的安全计费",
    "Bezpieczne rozliczenia obsługiwane przez Stripe",
    "Faturim i sigurt i menaxhuar nga Stripe"
  ],
  "Subscription and payments": [
    "Abonnement en betalingen",
    "Abonnement und Zahlungen",
    "Abonnement et paiements",
    "Abbonamento e pagamenti",
    "Подписка и платежи",
    "Suscripción y pagos",
    "Abonelik ve ödemeler",
    "Subscrição e pagamentos",
    "订阅和付款",
    "Subskrypcja i płatności",
    "Abonimi dhe pagesat"
  ],
  "Vehicle Widget": [
    "Voertuigwidget",
    "Fahrzeug-Widget",
    "Widget véhicule",
    "Widget veicolo",
    "Виджет автомобиля",
    "Widget de vehículo",
    "Araç widget'ı",
    "Widget de veículo",
    "车辆小组件",
    "Widżet pojazdu",
    "Widget-i i automjetit"
  ],
  "View widget plans": [
    "Widget-abonnementen bekijken",
    "Widget-Tarife anzeigen",
    "Voir les offres du widget",
    "Visualizza piani widget",
    "Посмотреть тарифы виджета",
    "Ver planes del widget",
    "Widget planlarını görüntüle",
    "Ver planos do widget",
    "查看小组件套餐",
    "Zobacz plany widżetu",
    "Shiko planet e widget-it"
  ],
  "Widget billing": [
    "Widget-facturatie",
    "Widget-Abrechnung",
    "Facturation du widget",
    "Fatturazione widget",
    "Оплата виджета",
    "Facturación del widget",
    "Widget faturalandırma",
    "Faturação do widget",
    "小组件计费",
    "Rozliczenia widżetu",
    "Faturimi i widget-it"
  ],
  "Widget dashboard": [
    "Widgetdashboard",
    "Widget-Dashboard",
    "Tableau de bord du widget",
    "Dashboard widget",
    "Панель виджета",
    "Panel del widget",
    "Widget paneli",
    "Painel do widget",
    "小组件面板",
    "Panel widżetu",
    "Paneli i widget-it"
  ]
} as const satisfies Readonly<Record<string, readonly string[]>>;
