import type { LocaleCode } from "@/lib/i18nConfig";

export const customerOnboardingLocaleOrder = [
  "nl", "de", "fr", "it", "ru", "es", "tr", "pt", "zh", "pl", "sq",
] as const satisfies readonly Exclude<LocaleCode, "en">[];

type TranslationRow = readonly [
  source: string, nl: string, de: string, fr: string, it: string,
  ru: string, es: string, tr: string, pt: string, zh: string, pl: string, sq: string,
];

// Dedicated typed onboarding copy. New UI must not expand legacy DOM-observer catalogs.
export const customerOnboardingRows = [
  ["Opens in a new tab", "Opent in een nieuw tabblad", "Öffnet in einem neuen Tab", "S’ouvre dans un nouvel onglet", "Si apre in una nuova scheda", "Открывается в новой вкладке", "Se abre en una pestaña nueva", "Yeni sekmede açılır", "Abre num novo separador", "在新标签页中打开", "Otwiera się w nowej karcie", "Hapet në një skedë të re"],
  ["Welcome to your workspace", "Welkom in uw werkruimte", "Willkommen in Ihrem Arbeitsbereich", "Bienvenue dans votre espace", "Benvenuto nel tuo spazio di lavoro", "Добро пожаловать в ваш рабочий кабинет", "Le damos la bienvenida a su espacio", "Çalışma alanınıza hoş geldiniz", "Bem-vindo ao seu espaço de trabalho", "欢迎来到您的工作区", "Witamy w Twoim panelu", "Mirë se vini në hapësirën tuaj të punës"],
  ["A quick tour of credits, file requests and support. You can skip it at any time.", "Een korte rondleiding over credits, bestandsaanvragen en ondersteuning. U kunt deze op elk moment overslaan.", "Eine kurze Einführung zu Credits, Dateianfragen und Support. Sie können sie jederzeit überspringen.", "Un aperçu rapide des crédits, des demandes de fichiers et de l’assistance. Vous pouvez le passer à tout moment.", "Una breve guida a crediti, richieste di file e assistenza. Puoi saltarla in qualsiasi momento.", "Краткое знакомство с кредитами, запросами файлов и поддержкой. Обучение можно пропустить в любой момент.", "Una guía rápida sobre créditos, solicitudes de archivos y asistencia. Puede omitirla en cualquier momento.", "Krediler, dosya talepleri ve destek hakkında kısa bir tanıtım. İstediğiniz zaman atlayabilirsiniz.", "Uma breve apresentação dos créditos, pedidos de ficheiros e apoio. Pode saltá-la a qualquer momento.", "快速了解积分、文件请求和支持功能。您可以随时跳过。", "Krótki przewodnik po kredytach, zgłoszeniach plików i pomocy. Możesz go pominąć w dowolnym momencie.", "Një udhëzues i shkurtër për kreditet, kërkesat e skedarëve dhe mbështetjen. Mund ta kaloni në çdo moment."],
  ["1. Prepare your original file", "1. Houd uw originele bestand gereed", "1. Originaldatei vorbereiten", "1. Préparez votre fichier d’origine", "1. Prepara il file originale", "1. Подготовьте исходный файл", "1. Prepare su archivo original", "1. Orijinal dosyanızı hazırlayın", "1. Prepare o ficheiro original", "1. 准备原始文件", "1. Przygotuj oryginalny plik", "1. Përgatitni skedarin origjinal"],
  ["Keep the original ECU or TCU read ready. You can add your vehicle, controller and service details when creating a request.", "Houd het originele uitleesbestand van de ECU of TCU gereed. Bij het maken van een aanvraag kunt u voertuig-, regeleenheid- en servicegegevens toevoegen.", "Halten Sie die Original-Auslesedatei der ECU oder TCU bereit. Fahrzeug-, Steuergeräte- und Servicedetails können Sie beim Erstellen einer Anfrage ergänzen.", "Préparez la lecture d’origine de l’ECU ou de la TCU. Vous pourrez ajouter les informations du véhicule, du calculateur et du service lors de la création d’une demande.", "Tieni pronta la lettura originale della ECU o della TCU. Durante la creazione della richiesta puoi aggiungere i dettagli del veicolo, della centralina e del servizio.", "Подготовьте исходный файл считывания ECU или TCU. Данные автомобиля, блока управления и услуги можно добавить при создании запроса.", "Tenga preparada la lectura original de la ECU o TCU. Puede añadir los datos del vehículo, la unidad de control y el servicio al crear una solicitud.", "ECU veya TCU’dan okunan orijinal dosyayı hazır bulundurun. Talep oluştururken araç, kontrol ünitesi ve hizmet bilgilerini ekleyebilirsiniz.", "Tenha pronta a leitura original da ECU ou TCU. Pode adicionar os dados do veículo, da unidade de controlo e do serviço ao criar um pedido.", "请准备好从 ECU 或 TCU 读取的原始文件。创建请求时，您可以添加车辆、控制器和服务详情。", "Przygotuj oryginalny odczyt ECU lub TCU. Dane pojazdu, sterownika i usługi możesz dodać podczas tworzenia zgłoszenia.", "Mbani gati leximin origjinal të ECU ose TCU. Të dhënat e automjetit, njësisë së kontrollit dhe shërbimit mund t’i shtoni kur krijoni një kërkesë."],
  ["2. Choose your credits", "2. Kies uw credits", "2. Credits auswählen", "2. Choisissez vos crédits", "2. Scegli i tuoi crediti", "2. Выберите количество кредитов", "2. Elija sus créditos", "2. Kredilerinizi seçin", "2. Escolha os seus créditos", "2. 选择积分", "2. Wybierz kredyty", "2. Zgjidhni kreditet"],
  ["Open Buy Credits to compare the available packages or enter an amount. Your account prices are shown before payment.", "Open Credits kopen om de beschikbare pakketten te vergelijken of een aantal in te voeren. De prijzen voor uw account worden vóór de betaling getoond.", "Öffnen Sie Credits kaufen, um verfügbare Pakete zu vergleichen oder eine Menge einzugeben. Ihre Kontopreise werden vor der Zahlung angezeigt.", "Ouvrez Acheter des crédits pour comparer les forfaits disponibles ou saisir une quantité. Les tarifs de votre compte sont affichés avant le paiement.", "Apri Acquista crediti per confrontare i pacchetti disponibili o inserire una quantità. I prezzi del tuo account vengono mostrati prima del pagamento.", "Откройте «Купить кредиты», чтобы сравнить доступные пакеты или указать количество. Цены для вашего аккаунта отображаются до оплаты.", "Abra Comprar créditos para comparar los paquetes disponibles o introducir una cantidad. Los precios de su cuenta se muestran antes del pago.", "Mevcut paketleri karşılaştırmak veya bir miktar girmek için Kredi Satın Al bölümünü açın. Hesabınıza ait fiyatlar ödemeden önce gösterilir.", "Abra Comprar créditos para comparar os pacotes disponíveis ou introduzir uma quantidade. Os preços da sua conta são apresentados antes do pagamento.", "打开“购买积分”，比较可用套餐或输入数量。付款前会显示适用于您账户的价格。", "Otwórz Kup kredyty, aby porównać dostępne pakiety lub wpisać ilość. Ceny dla Twojego konta zobaczysz przed płatnością.", "Hapni Bli kredite për të krahasuar paketat e disponueshme ose për të vendosur një sasi. Çmimet e llogarisë suaj shfaqen përpara pagesës."],
  ["3. Create a file request", "3. Maak een bestandsaanvraag", "3. Dateianfrage erstellen", "3. Créez une demande de fichier", "3. Crea una richiesta di file", "3. Создайте запрос файла", "3. Cree una solicitud de archivo", "3. Dosya talebi oluşturun", "3. Crie um pedido de ficheiro", "3. 创建文件请求", "3. Utwórz zgłoszenie pliku", "3. Krijoni një kërkesë skedari"],
  ["Open New File Request, select your vehicle and services, then upload your original file and review the details.", "Open Nieuwe bestandsaanvraag, selecteer uw voertuig en services, upload vervolgens uw originele bestand en controleer de gegevens.", "Öffnen Sie Neue Dateianfrage, wählen Sie Fahrzeug und Services aus, laden Sie Ihre Originaldatei hoch und prüfen Sie die Angaben.", "Ouvrez Nouvelle demande de fichier, sélectionnez votre véhicule et les services, puis envoyez votre fichier d’origine et vérifiez les informations.", "Apri Nuova richiesta di file, seleziona il veicolo e i servizi, poi carica il file originale e controlla i dettagli.", "Откройте «Новый запрос файла», выберите автомобиль и услуги, затем загрузите исходный файл и проверьте данные.", "Abra Nueva solicitud de archivo, seleccione su vehículo y los servicios, después suba el archivo original y revise los datos.", "Yeni Dosya Talebi bölümünü açın, aracınızı ve hizmetleri seçin; ardından orijinal dosyanızı yükleyip bilgileri kontrol edin.", "Abra Novo pedido de ficheiro, selecione o veículo e os serviços, depois carregue o ficheiro original e reveja os dados.", "打开“新建文件请求”，选择车辆和服务，然后上传原始文件并核对详情。", "Otwórz Nowe zgłoszenie pliku, wybierz pojazd i usługi, następnie prześlij oryginalny plik i sprawdź szczegóły.", "Hapni Kërkesë e re skedari, zgjidhni automjetin dhe shërbimet, pastaj ngarkoni skedarin origjinal dhe kontrolloni të dhënat."],
  ["4. Follow progress and get help", "4. Volg de voortgang en krijg hulp", "4. Fortschritt verfolgen und Hilfe erhalten", "4. Suivez l’avancement et obtenez de l’aide", "4. Segui l’avanzamento e ricevi assistenza", "4. Следите за ходом работы и получайте помощь", "4. Siga el progreso y obtenga ayuda", "4. Süreci takip edin ve destek alın", "4. Acompanhe o progresso e obtenha apoio", "4. 跟踪进度并获取帮助", "4. Śledź postęp i uzyskaj pomoc", "4. Ndiqni ecurinë dhe merrni ndihmë"],
  ["Open an order to see its status, exchange messages and download the finished file when it is ready.", "Open een bestelling om de status te bekijken, berichten uit te wisselen en het voltooide bestand te downloaden zodra het gereed is.", "Öffnen Sie einen Auftrag, um seinen Status zu sehen, Nachrichten auszutauschen und die fertige Datei herunterzuladen, sobald sie bereitsteht.", "Ouvrez une commande pour voir son statut, échanger des messages et télécharger le fichier terminé lorsqu’il est prêt.", "Apri un ordine per visualizzarne lo stato, scambiare messaggi e scaricare il file completato quando è pronto.", "Откройте заказ, чтобы узнать его статус, обменяться сообщениями и скачать готовый файл, когда он будет доступен.", "Abra un pedido para ver su estado, intercambiar mensajes y descargar el archivo terminado cuando esté listo.", "Durumunu görmek, mesajlaşmak ve hazır olduğunda tamamlanan dosyayı indirmek için bir siparişi açın.", "Abra um pedido para ver o estado, trocar mensagens e descarregar o ficheiro concluído quando estiver pronto.", "打开订单即可查看状态、收发消息，并在文件处理完成后下载。", "Otwórz zlecenie, aby sprawdzić jego status, wymieniać wiadomości i pobrać ukończony plik, gdy będzie gotowy.", "Hapni një porosi për të parë statusin, për të shkëmbyer mesazhe dhe për të shkarkuar skedarin e përfunduar kur të jetë gati."],
  ["Start tour", "Rondleiding starten", "Einführung starten", "Démarrer la visite", "Avvia la guida", "Начать знакомство", "Iniciar guía", "Tanıtımı başlat", "Iniciar apresentação", "开始导览", "Rozpocznij przewodnik", "Fillo udhëzuesin"],
  ["Skip tour", "Rondleiding overslaan", "Einführung überspringen", "Passer la visite", "Salta la guida", "Пропустить знакомство", "Omitir guía", "Tanıtımı atla", "Saltar apresentação", "跳过导览", "Pomiń przewodnik", "Kalo udhëzuesin"],
  ["Next step", "Volgende stap", "Nächster Schritt", "Étape suivante", "Passaggio successivo", "Следующий шаг", "Siguiente paso", "Sonraki adım", "Próximo passo", "下一步", "Następny krok", "Hapi tjetër"],
  ["Previous step", "Vorige stap", "Vorheriger Schritt", "Étape précédente", "Passaggio precedente", "Предыдущий шаг", "Paso anterior", "Önceki adım", "Passo anterior", "上一步", "Poprzedni krok", "Hapi i mëparshëm"],
  ["Finish tour", "Rondleiding afronden", "Einführung abschließen", "Terminer la visite", "Termina la guida", "Завершить знакомство", "Finalizar guía", "Tanıtımı bitir", "Concluir apresentação", "完成导览", "Zakończ przewodnik", "Përfundo udhëzuesin"],
  ["Saving your choice…", "Uw keuze wordt opgeslagen…", "Ihre Auswahl wird gespeichert…", "Enregistrement de votre choix…", "Salvataggio della scelta…", "Сохранение вашего выбора…", "Guardando su elección…", "Seçiminiz kaydediliyor…", "A guardar a sua escolha…", "正在保存您的选择…", "Zapisywanie Twojego wyboru…", "Po ruhet zgjedhja juaj…"],
  ["Your choice could not be saved. Please try again so the tour stays dismissed on your other devices.", "Uw keuze kon niet worden opgeslagen. Probeer het opnieuw, zodat de rondleiding ook op uw andere apparaten gesloten blijft.", "Ihre Auswahl konnte nicht gespeichert werden. Versuchen Sie es erneut, damit die Einführung auch auf Ihren anderen Geräten geschlossen bleibt.", "Votre choix n’a pas pu être enregistré. Réessayez pour que la visite reste fermée sur vos autres appareils.", "Non è stato possibile salvare la scelta. Riprova affinché la guida non riappaia sugli altri dispositivi.", "Не удалось сохранить ваш выбор. Повторите попытку, чтобы знакомство не появлялось на других ваших устройствах.", "No se ha podido guardar su elección. Inténtelo de nuevo para que la guía no vuelva a aparecer en sus otros dispositivos.", "Seçiminiz kaydedilemedi. Tanıtımın diğer cihazlarınızda da yeniden açılmaması için lütfen tekrar deneyin.", "Não foi possível guardar a sua escolha. Tente novamente para que a apresentação não volte a aparecer nos seus outros dispositivos.", "无法保存您的选择。请重试，以免导览在您的其他设备上再次出现。", "Nie udało się zapisać Twojego wyboru. Spróbuj ponownie, aby przewodnik nie pojawiał się na innych urządzeniach.", "Zgjedhja juaj nuk mund të ruhej. Provoni përsëri që udhëzuesi të mos rihapet në pajisjet tuaja të tjera."],
  ["Continue without saving", "Doorgaan zonder opslaan", "Ohne Speichern fortfahren", "Continuer sans enregistrer", "Continua senza salvare", "Продолжить без сохранения", "Continuar sin guardar", "Kaydetmeden devam et", "Continuar sem guardar", "不保存并继续", "Kontynuuj bez zapisywania", "Vazhdo pa ruajtur"],
  ["Tour progress", "Voortgang van de rondleiding", "Fortschritt der Einführung", "Progression de la visite", "Avanzamento della guida", "Ход знакомства", "Progreso de la guía", "Tanıtım ilerlemesi", "Progresso da apresentação", "导览进度", "Postęp przewodnika", "Ecuria e udhëzuesit"],
  ["Getting started", "Aan de slag", "Erste Schritte", "Premiers pas", "Primi passi", "Начало работы", "Primeros pasos", "İlk adımlar", "Primeiros passos", "入门指南", "Pierwsze kroki", "Hapat e parë"],
  ["Open Buy Credits", "Credits kopen openen", "Credits kaufen öffnen", "Ouvrir Acheter des crédits", "Apri Acquista crediti", "Открыть «Купить кредиты»", "Abrir Comprar créditos", "Kredi Satın Al bölümünü aç", "Abrir Comprar créditos", "打开购买积分", "Otwórz Kup kredyty", "Hap Bli kredite"],
  ["Open New File Request", "Nieuwe bestandsaanvraag openen", "Neue Dateianfrage öffnen", "Ouvrir Nouvelle demande de fichier", "Apri Nuova richiesta di file", "Открыть «Новый запрос файла»", "Abrir Nueva solicitud de archivo", "Yeni Dosya Talebi bölümünü aç", "Abrir Novo pedido de ficheiro", "打开新建文件请求", "Otwórz Nowe zgłoszenie pliku", "Hap Kërkesë e re skedari"],
  ["Open My Orders", "Mijn bestellingen openen", "Meine Aufträge öffnen", "Ouvrir Mes commandes", "Apri I miei ordini", "Открыть «Мои заказы»", "Abrir Mis pedidos", "Siparişlerim bölümünü aç", "Abrir Os meus pedidos", "打开我的订单", "Otwórz Moje zlecenia", "Hap Porositë e mia"],
  ["Retry", "Opnieuw proberen", "Wiederholen", "Réessayer", "Riprova", "Повторить", "Reintentar", "Tekrar dene", "Tentar novamente", "重试", "Ponów próbę", "Provo përsëri"],
] as const satisfies readonly TranslationRow[];

export type CustomerOnboardingSource = (typeof customerOnboardingRows)[number][0];

export const customerOnboardingExactTranslations: Readonly<Record<string, readonly string[]>> = Object.fromEntries(
  customerOnboardingRows.map(([source, ...translations]) => [source, translations]),
);

const customerOnboardingTranslations = Object.fromEntries(
  customerOnboardingRows.map(([source, ...translations]) => [
    source,
    Object.fromEntries([
      ["en", source],
      ...customerOnboardingLocaleOrder.map((locale, index) => [locale, translations[index]]),
    ]),
  ]),
) as Readonly<Record<CustomerOnboardingSource, Readonly<Record<LocaleCode, string>>>>;

export function customerOnboardingT(
  locale: LocaleCode,
  source: CustomerOnboardingSource,
): string {
  return customerOnboardingTranslations[source][locale];
}
