// This file is generated by scripts/generate-customer-workflow-client-translations.ts.
// Edit the master catalog or group source inventory, then regenerate it.

import type { LocaleCode } from "@/lib/i18nConfig";
import {
  createCustomerWorkflowClientTranslators,
} from "@/lib/i18n/customer-workflow-client-runtime";

export const customerWorkflowLocaleOrder = [
  "nl",
  "de",
  "fr",
  "it",
  "ru",
  "es",
  "tr",
  "pt",
  "zh",
  "pl",
  "sq"
] as const satisfies readonly Exclude<LocaleCode, "en">[];

export const customerWorkflowExactTranslations = {
  "Review required": [
    "Beoordeling vereist",
    "Prüfung erforderlich",
    "Vérification requise",
    "Verifica necessaria",
    "Требуется проверка",
    "Revisión necesaria",
    "İnceleme gerekli",
    "Revisão necessária",
    "需要复核",
    "Wymagana weryfikacja",
    "Kërkohet shqyrtim"
  ]
} as const satisfies Readonly<Record<string, readonly string[]>>;

export const customerWorkflowTemplateRows = [
  [
    "fileExpertEmptyFile",
    "The selected file is empty.",
    "Het geselecteerde bestand is leeg.",
    "Die ausgewählte Datei ist leer.",
    "Le fichier sélectionné est vide.",
    "Il file selezionato è vuoto.",
    "Выбранный файл пуст.",
    "El archivo seleccionado está vacío.",
    "Seçilen dosya boş.",
    "O ficheiro selecionado está vazio.",
    "所选文件为空。",
    "Wybrany plik jest pusty.",
    "Skedari i zgjedhur është bosh."
  ],
  [
    "fileExpertFieldBrand",
    "Vehicle brand",
    "Voertuigmerk",
    "Fahrzeugmarke",
    "Marque du véhicule",
    "Marca del veicolo",
    "Марка автомобиля",
    "Marca del vehículo",
    "Araç markası",
    "Marca do veículo",
    "车辆品牌",
    "Marka pojazdu",
    "Marka e automjetit"
  ],
  [
    "fileExpertFieldEcu",
    "ECU / TCU hint",
    "ECU-/TCU-aanwijzing",
    "ECU-/TCU-Hinweis",
    "Indication ECU / TCU",
    "Indicazione ECU / TCU",
    "Подсказка ECU / TCU",
    "Indicación de ECU / TCU",
    "ECU / TCU ipucu",
    "Indicação de ECU / TCU",
    "ECU / TCU 提示",
    "Wskazówka ECU / TCU",
    "Të dhëna ndihmëse për ECU / TCU"
  ],
  [
    "fileExpertFieldEngine",
    "Engine",
    "Motor",
    "Motor",
    "Moteur",
    "Motore",
    "Двигатель",
    "Motor",
    "Motor",
    "Motor",
    "发动机",
    "Silnik",
    "Motori"
  ],
  [
    "fileExpertFieldModel",
    "Model",
    "Model",
    "Modell",
    "Modèle",
    "Modello",
    "Модель",
    "Modelo",
    "Model",
    "Modelo",
    "车型",
    "Model",
    "Modeli"
  ],
  [
    "fileExpertFieldNotes",
    "Customer notes",
    "Klantnotities",
    "Kundennotizen",
    "Notes du client",
    "Note del cliente",
    "Примечания клиента",
    "Notas del cliente",
    "Müşteri notları",
    "Notas do cliente",
    "客户备注",
    "Uwagi klienta",
    "Shënimet e klientit"
  ],
  [
    "fileExpertFileTooLarge",
    "The file is too large. Maximum size: {size}.",
    "Het bestand is te groot. Maximale grootte: {size}.",
    "Die Datei ist zu groß. Maximale Größe: {size}.",
    "Le fichier est trop volumineux. Taille maximale : {size}.",
    "Il file è troppo grande. Dimensione massima: {size}.",
    "Файл слишком большой. Максимальный размер: {size}.",
    "El archivo es demasiado grande. Tamaño máximo: {size}.",
    "Dosya çok büyük. En fazla boyut: {size}.",
    "O ficheiro é demasiado grande. Tamanho máximo: {size}.",
    "文件过大。最大大小：{size}。",
    "Plik jest zbyt duży. Maksymalny rozmiar: {size}.",
    "Skedari është shumë i madh. Madhësia maksimale: {size}."
  ],
  [
    "fileExpertRequirements",
    "Allowed files: {extensions}. Maximum {size} per file.",
    "Toegestane bestanden: {extensions}. Maximaal {size} per bestand.",
    "Zulässige Dateien: {extensions}. Maximal {size} pro Datei.",
    "Fichiers autorisés : {extensions}. Maximum {size} par fichier.",
    "File consentiti: {extensions}. Massimo {size} per file.",
    "Разрешённые файлы: {extensions}. Не более {size} на файл.",
    "Archivos permitidos: {extensions}. Máximo {size} por archivo.",
    "İzin verilen dosyalar: {extensions}. Dosya başına en fazla {size}.",
    "Ficheiros permitidos: {extensions}. Máximo de {size} por ficheiro.",
    "允许的文件：{extensions}。每个文件最大 {size}。",
    "Dozwolone pliki: {extensions}. Maksymalnie {size} na plik.",
    "Skedarët e lejuar: {extensions}. Maksimumi {size} për skedar."
  ],
  [
    "fileExpertSelectFile",
    "Select at least one valid ORI or MOD file before starting the analysis.",
    "Selecteer minstens één geldig ORI- of MOD-bestand voordat u de analyse start.",
    "Wählen Sie vor Beginn der Analyse mindestens eine gültige ORI- oder MOD-Datei aus.",
    "Sélectionnez au moins un fichier ORI ou MOD valide avant de lancer l’analyse.",
    "Seleziona almeno un file ORI o MOD valido prima di avviare l’analisi.",
    "Перед запуском анализа выберите хотя бы один допустимый файл ORI или MOD.",
    "Seleccione al menos un archivo ORI o MOD válido antes de iniciar el análisis.",
    "Analizi başlatmadan önce en az bir geçerli ORI veya MOD dosyası seçin.",
    "Selecione pelo menos um ficheiro ORI ou MOD válido antes de iniciar a análise.",
    "开始分析前，请至少选择一个有效的 ORI 或 MOD 文件。",
    "Przed rozpoczęciem analizy wybierz co najmniej jeden prawidłowy plik ORI lub MOD.",
    "Zgjidhni të paktën një skedar ORI ose MOD të vlefshëm para nisjes së analizës."
  ],
  [
    "fileExpertTextLimit",
    "{field} must contain no more than {count} characters.",
    "{field} mag maximaal {count} tekens bevatten.",
    "{field} darf höchstens {count} Zeichen enthalten.",
    "{field} ne doit pas dépasser {count} caractères.",
    "{field} non può superare {count} caratteri.",
    "Поле «{field}» должно содержать не более {count} символов.",
    "{field} no puede superar los {count} caracteres.",
    "{field} en fazla {count} karakter içerebilir.",
    "{field} não pode ter mais de {count} carateres.",
    "{field}不得超过 {count} 个字符。",
    "Pole „{field}” może zawierać maksymalnie {count} znaków.",
    "{field} nuk mund të përmbajë më shumë se {count} karaktere."
  ],
  [
    "fileExpertUnsupportedFile",
    "Unsupported file type. Upload one of these formats: {extensions}.",
    "Niet-ondersteund bestandstype. Upload een van deze formaten: {extensions}.",
    "Nicht unterstützter Dateityp. Laden Sie eines dieser Formate hoch: {extensions}.",
    "Type de fichier non pris en charge. Téléversez l’un de ces formats : {extensions}.",
    "Tipo di file non supportato. Carica uno di questi formati: {extensions}.",
    "Тип файла не поддерживается. Загрузите один из следующих форматов: {extensions}.",
    "Tipo de archivo no compatible. Suba uno de estos formatos: {extensions}.",
    "Desteklenmeyen dosya türü. Şu biçimlerden birini yükleyin: {extensions}.",
    "Tipo de ficheiro não suportado. Carregue um destes formatos: {extensions}.",
    "不支持的文件类型。请上传以下格式之一：{extensions}。",
    "Nieobsługiwany typ pliku. Prześlij jeden z tych formatów: {extensions}.",
    "Lloj skedari i pambështetur. Ngarkoni një nga këto formate: {extensions}."
  ],
  [
    "fileExpertUploadFile",
    "Upload at least one valid ORI or MOD file.",
    "Upload minstens één geldig ORI- of MOD-bestand.",
    "Laden Sie mindestens eine gültige ORI- oder MOD-Datei hoch.",
    "Téléversez au moins un fichier ORI ou MOD valide.",
    "Carica almeno un file ORI o MOD valido.",
    "Загрузите хотя бы один допустимый файл ORI или MOD.",
    "Suba al menos un archivo ORI o MOD válido.",
    "En az bir geçerli ORI veya MOD dosyası yükleyin.",
    "Carregue pelo menos um ficheiro ORI ou MOD válido.",
    "请至少上传一个有效的 ORI 或 MOD 文件。",
    "Prześlij co najmniej jeden prawidłowy plik ORI lub MOD.",
    "Ngarkoni të paktën një skedar ORI ose MOD të vlefshëm."
  ],
  [
    "overLimit",
    "{count} over limit.",
    "{count} over limiet.",
    "{count} über dem Limit.",
    "{count} dépasse la limite.",
    "{count} oltre il limite.",
    "{count} превышает лимит.",
    "{count} por encima del límite.",
    "{count} limit aşıldı.",
    "{count} acima do limite.",
    "{count} 超出限制。",
    "{count} przekroczył limit.",
    "{count} mbi kufirin."
  ],
  [
    "remaining",
    "{count} remaining.",
    "{count} resterend.",
    "{count} übrig.",
    "{count} restants.",
    "{count} rimanenti.",
    "Осталось {count}.",
    "{count} restante.",
    "{count} kaldı.",
    "{count} restantes.",
    "还剩 {count} 个。",
    "Pozostało: {count}.",
    "{count} të mbetura."
  ]
] as const;

export type CustomerWorkflowTranslationKey = (typeof customerWorkflowTemplateRows)[number][0];

const translators = createCustomerWorkflowClientTranslators(
  customerWorkflowExactTranslations,
  customerWorkflowTemplateRows,
);

export function customerWorkflowExactT(locale: LocaleCode, source: string) {
  return translators.exactT(locale, source);
}

export function customerWorkflowT(
  locale: LocaleCode,
  key: CustomerWorkflowTranslationKey,
  values: Record<string, string | number> = {},
) {
  return translators.t(locale, key, values);
}
