// This file is generated by scripts/generate-customer-workflow-client-translations.ts.
// It contains only DOM-observer copy for the security surface.

import type { LocaleCode } from "@/lib/i18nConfig";

export const customerWorkflowLocaleOrder = [
  "nl",
  "de",
  "fr",
  "it",
  "ru",
  "es",
  "tr",
  "pt",
  "zh",
  "pl",
  "sq"
] as const satisfies readonly Exclude<LocaleCode, "en">[];

export const customerWorkflowExactTranslations = {
  "All other trusted devices were removed.": [
    "Alle andere vertrouwde apparaten zijn verwijderd.",
    "Alle anderen vertrauenswürdigen Geräte wurden entfernt.",
    "Tous les autres appareils de confiance ont été supprimés.",
    "Tutti gli altri dispositivi attendibili sono stati rimossi.",
    "Все остальные доверенные устройства были удалены.",
    "Se eliminaron todos los demás dispositivos confiables.",
    "Diğer tüm güvenilir cihazlar kaldırıldı.",
    "Todos os outros dispositivos fidedignos foram removidos.",
    "所有其他受信任的设备均已删除。",
    "Wszystkie inne zaufane urządzenia zostały usunięte.",
    "Të gjitha pajisjet e tjera të besuara u hoqën."
  ],
  "Current": [
    "Huidig",
    "Aktuell",
    "Actuel",
    "Attuale",
    "Текущее",
    "Actual",
    "Mevcut",
    "Atual",
    "当前",
    "Bieżące",
    "Aktuale"
  ],
  "Loading trusted devices...": [
    "Vertrouwde apparaten laden...",
    "Vertrauenswürdige Geräte werden geladen...",
    "Chargement des appareils approuvés...",
    "Caricamento dei dispositivi attendibili...",
    "Загрузка доверенных устройств...",
    "Cargando dispositivos de confianza...",
    "Güvenilir cihazlar yükleniyor...",
    "A carregar dispositivos de confiança...",
    "正在加载可信设备...",
    "Ładowanie zaufanych urządzeń...",
    "Po ngarkohen pajisjet e besuara..."
  ],
  "New devices require an e-mail security code. Devices you explicitly trust can sign in for 30 days without another code.": [
    "Nieuwe apparaten vereisen een beveiligingscode per e-mail. Apparaten die je expliciet vertrouwt, kunnen 30 dagen zonder extra code inloggen.",
    "Neue Geräte benötigen einen Sicherheitscode per E-Mail. Geräte, denen Sie ausdrücklich vertrauen, können sich 30 Tage lang ohne weiteren Code anmelden.",
    "Les nouveaux appareils nécessitent un code de sécurité envoyé par e-mail. Les appareils que vous approuvez explicitement peuvent se connecter pendant 30 jours sans autre code.",
    "I nuovi dispositivi richiedono un codice di sicurezza via e-mail. I dispositivi considerati esplicitamente attendibili possono accedere per 30 giorni senza un altro codice.",
    "Для новых устройств требуется код безопасности из электронной почты. Устройства, которым вы явно доверяете, могут входить в систему в течение 30 дней без повторного кода.",
    "Los nuevos dispositivos requieren un código de seguridad por correo electrónico. Los dispositivos que marques expresamente como de confianza podrán iniciar sesión durante 30 días sin otro código.",
    "Yeni cihazlarda e-posta güvenlik kodu gerekir. Açıkça güvendiğiniz cihazlar 30 gün boyunca başka bir kod olmadan giriş yapabilir.",
    "Os novos dispositivos requerem um código de segurança por e-mail. Os dispositivos em que confiar explicitamente podem iniciar sessão durante 30 dias sem outro código.",
    "新设备需要电子邮件安全码。您明确设为可信的设备可在 30 天内无需再次输入代码即可登录。",
    "Nowe urządzenia wymagają kodu bezpieczeństwa wysłanego e-mailem. Urządzenia oznaczone przez Ciebie jako zaufane mogą logować się przez 30 dni bez kolejnego kodu.",
    "Pajisjet e reja kërkojnë një kod sigurie me e-mail. Pajisjet që i shënoni qartë si të besuara mund të identifikohen për 30 ditë pa një kod tjetër."
  ],
  "No trusted devices are saved. You can select “Trust this device for 30 days” the next time you verify a login.": [
    "Er zijn geen vertrouwde apparaten opgeslagen. Bij je volgende aanmeldverificatie kun je ‘Dit apparaat 30 dagen vertrouwen’ selecteren.",
    "Es sind keine vertrauenswürdigen Geräte gespeichert. Bei der nächsten Anmeldebestätigung können Sie „Diesem Gerät 30 Tage vertrauen“ auswählen.",
    "Aucun appareil approuvé n’est enregistré. Lors de votre prochaine vérification de connexion, vous pourrez sélectionner « Faire confiance à cet appareil pendant 30 jours ».",
    "Non sono stati salvati dispositivi attendibili. Alla prossima verifica dell’accesso potrai selezionare “Considera attendibile questo dispositivo per 30 giorni”.",
    "Доверенные устройства не сохранены. При следующем подтверждении входа можно выбрать «Доверять этому устройству 30 дней».",
    "No hay dispositivos de confianza guardados. La próxima vez que verifiques un inicio de sesión podrás seleccionar «Confiar en este dispositivo durante 30 días».",
    "Kayıtlı güvenilir cihaz yok. Bir sonraki giriş doğrulamanızda “Bu cihaza 30 gün güven” seçeneğini işaretleyebilirsiniz.",
    "Não existem dispositivos de confiança guardados. Na próxima verificação de início de sessão, pode selecionar «Confiar neste dispositivo durante 30 dias».",
    "尚未保存任何可信设备。下次验证登录时，您可以选择“信任此设备 30 天”。",
    "Nie zapisano żadnych zaufanych urządzeń. Przy następnej weryfikacji logowania możesz wybrać opcję „Ufaj temu urządzeniu przez 30 dni”.",
    "Nuk është ruajtur asnjë pajisje e besuar. Herën tjetër që verifikoni një hyrje, mund të zgjidhni “Besoji kësaj pajisjeje për 30 ditë”."
  ],
  "Other devices could not be revoked.": [
    "Andere apparaten konden niet worden ingetrokken.",
    "Andere Geräte konnten nicht widerrufen werden.",
    "Les autres appareils ne pouvaient pas être révoqués.",
    "Non è stato possibile revocare altri dispositivi.",
    "Другие устройства не могут быть отозваны.",
    "Otros dispositivos no se pudieron revocar.",
    "Diğer cihazlar iptal edilemedi.",
    "Outros dispositivos não puderam ser revogados.",
    "其他设备无法撤销。",
    "Nie można odwołać innych urządzeń.",
    "Pajisjet e tjera nuk mund të anuloheshin."
  ],
  "Refresh": [
    "Vernieuwen",
    "Aktualisieren",
    "Actualiser",
    "Aggiorna",
    "Обновить",
    "Actualizar",
    "Yenile",
    "Atualizar",
    "刷新",
    "Odśwież",
    "Rifresko"
  ],
  "Revoke": [
    "Intrekken",
    "Widerrufen",
    "Révoquer",
    "Revoca",
    "Отозвать",
    "Revocar",
    "Güveni kaldır",
    "Revogar",
    "撤销信任",
    "Cofnij zaufanie",
    "Revoko"
  ],
  "Revoke all other devices": [
    "Alle andere apparaten intrekken",
    "Allen anderen Geräten das Vertrauen entziehen",
    "Révoquer tous les autres appareils",
    "Revoca tutti gli altri dispositivi",
    "Отозвать доверие ко всем остальным устройствам",
    "Revocar todos los demás dispositivos",
    "Diğer tüm cihazların güvenini kaldır",
    "Revogar todos os outros dispositivos",
    "撤销对所有其他设备的信任",
    "Cofnij zaufanie do wszystkich pozostałych urządzeń",
    "Revoko të gjitha pajisjet e tjera"
  ],
  "Revoking a saved device blocks its MG AutoTech customer-data access. If you suspect account theft, reset your password too.": [
    "Als je een opgeslagen apparaat intrekt, wordt de toegang tot MG AutoTech-klantgegevens geblokkeerd. Als je vermoedt dat je account is overgenomen, stel dan ook je wachtwoord opnieuw in.",
    "Wenn Sie einem gespeicherten Gerät das Vertrauen entziehen, wird dessen Zugriff auf MG AutoTech-Kundendaten gesperrt. Wenn Sie vermuten, dass Ihr Konto übernommen wurde, setzen Sie zusätzlich Ihr Passwort zurück.",
    "La révocation d’un appareil enregistré bloque son accès aux données client MG AutoTech. Si vous pensez que votre compte a été compromis, réinitialisez également votre mot de passe.",
    "La revoca di un dispositivo salvato ne blocca l’accesso ai dati cliente MG AutoTech. Se sospetti che il tuo account sia stato compromesso, reimposta anche la password.",
    "Отзыв сохранённого устройства блокирует его доступ к клиентским данным MG AutoTech. Если вы подозреваете взлом аккаунта, также сбросьте пароль.",
    "Revocar un dispositivo guardado bloque su acceso a los datos de cliente de MG AutoTech. Si sospechas que tu cuenta está comprometida, restablece también la contraseña.",
    "Kayıtlı bir cihazın güvenini kaldırmak, cihazın MG AutoTech müşteri verilerine erişimini engeller. Hesabınızın ele geçirildiğinden şüpheleniyorsanız parolanızı da sıfırlayın.",
    "Revogar um dispositivo guardado bloqueia o acesso deste aos dados de cliente da MG AutoTech. Se suspeitar que a conta foi comprometida, reponha também a palavra-passe.",
    "撤销已保存设备的信任后，该设备将无法访问 MG AutoTech 客户数据。如果您怀疑账户被盗，也请重置密码。",
    "Cofnięcie zaufania do zapisanego urządzenia blokuje jego dostęp do danych klientów MG AutoTech. Jeśli podejrzewasz przejęcie konta, zresetuj również hasło.",
    "Revokimi i një pajisjeje të ruajtur bllokon qasjen e saj në të dhënat e klientëve të MG AutoTech. Nëse dyshoni se llogaria është komprometuar, rivendosni edhe fjalëkalimin."
  ],
  "Security & trusted devices": [
    "Beveiliging en vertrouwde apparaten",
    "Sicherheit & vertrauenswürdige Geräte",
    "Sécurité et appareils approuvés",
    "Sicurezza e dispositivi attendibili",
    "Безопасность и доверенные устройства",
    "Seguridad y dispositivos de confianza",
    "Güvenlik ve güvenilir cihazlar",
    "Segurança e dispositivos de confiança",
    "安全与可信设备",
    "Bezpieczeństwo i zaufane urządzenia",
    "Siguria dhe pajisjet e besuara"
  ],
  "Trusted device could not be revoked.": [
    "Vertrouwd apparaat kan niet worden ingetrokken.",
    "Das vertrauenswürdige Gerät konnte nicht widerrufen werden.",
    "L'appareil de confiance n'a pas pu être révoqué.",
    "Impossibile revocare il dispositivo attendibile.",
    "Доверенное устройство не удалось отозвать.",
    "No se pudo revocar el dispositivo de confianza.",
    "Güvenilen cihaz iptal edilemedi.",
    "Não foi possível revogar o dispositivo fidedigno.",
    "无法撤销可信设备。",
    "Nie można unieważnić zaufanego urządzenia.",
    "Pajisja e besuar nuk mund të revokohej."
  ],
  "Trusted device removed.": [
    "Vertrouwd apparaat verwijderd.",
    "Vertrauenswürdiges Gerät entfernt.",
    "Appareil de confiance supprimé.",
    "Dispositivo attendibile rimosso.",
    "Доверенное устройство удалено.",
    "Dispositivo de confianza eliminado.",
    "Güvenilir cihaz kaldırıldı.",
    "Dispositivo fiável removido.",
    "可信设备已删除。",
    "Zaufane urządzenie zostało usunięte.",
    "Pajisja e besuar u hoq."
  ],
  "Trusted devices could not be loaded.": [
    "Vertrouwde apparaten konden niet worden geladen.",
    "Vertrauenswürdige Geräte konnten nicht geladen werden.",
    "Les appareils de confiance n'ont pas pu être chargés.",
    "Impossibile caricare i dispositivi attendibili.",
    "Не удалось загрузить доверенные устройства.",
    "No se pudieron cargar los dispositivos confiables.",
    "Güvenilen cihazlar yüklenemedi.",
    "Não foi possível carregar dispositivos fidedignos.",
    "无法加载受信任的设备。",
    "Nie można załadować zaufanych urządzeń.",
    "Pajisjet e besuara nuk mund të ngarkoheshin."
  ]
} as const satisfies Readonly<Record<string, readonly string[]>>;
