// This file is generated by scripts/generate-customer-workflow-client-translations.ts.
// Edit the master catalog or group source inventory, then regenerate it.

import type { LocaleCode } from "@/lib/i18nConfig";
import {
  createCustomerWorkflowClientTranslators,
} from "@/lib/i18n/customer-workflow-client-runtime";

export const customerWorkflowLocaleOrder = [
  "nl",
  "de",
  "fr",
  "it",
  "ru",
  "es",
  "tr",
  "pt",
  "zh",
  "pl",
  "sq"
] as const satisfies readonly Exclude<LocaleCode, "en">[];

export const customerWorkflowExactTranslations = {
  "Customer Dashboard": [
    "Klantdashboard",
    "Kunden-Dashboard",
    "Tableau de bord client",
    "Dashboard cliente",
    "Панель клиента",
    "Panel de cliente",
    "Müşteri paneli",
    "Painel do cliente",
    "客户面板",
    "Panel klienta",
    "Paneli i klientit"
  ],
  "Datalog Analysis Studio": [
    "Datalog-analysestudio",
    "Datalog-Analyse-Studio",
    "Studio d’analyse de datalogs",
    "Studio di analisi datalog",
    "Студия анализа логов",
    "Estudio de análisis de datalogs",
    "Datalog Analiz Stüdyosu",
    "Estúdio de análise de registos de dados",
    "数据日志分析工作室",
    "Studio analizy datalogów",
    "Studio e analizës së datalogëve"
  ],
  "Manage your MG AutoTech Vehicle Selector Widget subscription and installation.": [
    "Beheer uw abonnement en installatie van de MG AutoTech voertuigselector-widget.",
    "Verwalten Sie Ihr Abonnement und die Installation des MG AutoTech Fahrzeugauswahl-Widgets.",
    "Gérez l’abonnement et l’installation de votre widget de sélection de véhicules MG AutoTech.",
    "Gestisci l’abbonamento e l’installazione del widget di selezione veicoli MG AutoTech.",
    "Управляйте подпиской и установкой виджета подбора автомобилей MG AutoTech.",
    "Gestione la suscripción e instalación de su widget de selección de vehículos MG AutoTech.",
    "MG AutoTech araç seçici widget aboneliğinizi ve kurulumunuzu yönetin.",
    "Faça a gestão da subscrição e instalação do seu widget de seleção de veículos MG AutoTech.",
    "管理您的 MG AutoTech 车辆选择器小组件订阅和安装。",
    "Zarządzaj subskrypcją i instalacją widżetu wyboru pojazdu MG AutoTech.",
    "Menaxhoni abonimin dhe instalimin e widget-it për përzgjedhjen e automjeteve MG AutoTech."
  ],
  "Private browser-local multi-channel datalog review for MG AutoTech customers.": [
    "Private analyse van meerkanaalsdatalogs, lokaal in de browser, voor MG AutoTech-klanten.",
    "Private Mehrkanal-Datalog-Analyse direkt im Browser für MG AutoTech-Kunden.",
    "Analyse privée de datalogs multicanaux, réalisée localement dans le navigateur, pour les clients MG AutoTech.",
    "Analisi privata di datalog multicanale, eseguita localmente nel browser, per i clienti MG AutoTech.",
    "Приватный локальный анализ многоканальных логов в браузере для клиентов MG AutoTech.",
    "Análisis privado de datalogs multicanal, realizado localmente en el navegador, para clientes de MG AutoTech.",
    "MG AutoTech müşterileri için tarayıcıda yerel olarak çalışan özel çok kanallı datalog analizi.",
    "Análise privada de datalogs multicanal, executada localmente no navegador, para clientes MG AutoTech.",
    "面向 MG AutoTech 客户的私密多通道数据日志分析，全程在浏览器本地完成。",
    "Prywatna analiza wielokanałowych datalogów wykonywana lokalnie w przeglądarce dla klientów MG AutoTech.",
    "Analizë private e datalogëve me shumë kanale, e kryer lokalisht në shfletues, për klientët e MG AutoTech."
  ],
  "Secure MG AutoTech customer dashboard for file requests, credits and deliveries.": [
    "Beveiligd MG AutoTech-klantdashboard voor bestandsaanvragen, credits en leveringen.",
    "Sicheres MG AutoTech Kunden-Dashboard für Dateianfragen, Credits und Lieferungen.",
    "Tableau de bord client MG AutoTech sécurisé pour les demandes de fichiers, les crédits et les livraisons.",
    "Dashboard cliente MG AutoTech sicura per richieste di file, crediti e consegne.",
    "Безопасная панель клиента MG AutoTech для запросов файлов, кредитов и выдачи готовых файлов.",
    "Panel seguro para clientes de MG AutoTech, destinado a solicitudes de archivos, créditos y entregas.",
    "Dosya talepleri, krediler ve teslimatlar için güvenli MG AutoTech müşteri paneli.",
    "Painel de cliente seguro da MG AutoTech para pedidos de ficheiros, créditos e entregas.",
    "用于管理文件请求、积分和交付的安全 MG AutoTech 客户面板。",
    "Bezpieczny panel klienta MG AutoTech do obsługi zleceń plików, kredytów i dostaw.",
    "Panel i sigurt i klientit MG AutoTech për kërkesat e skedarëve, kreditë dhe dorëzimet."
  ],
  "Vehicle Widget Dashboard": [
    "Dashboard voor de voertuigwidget",
    "Dashboard für das Fahrzeug-Widget",
    "Tableau de bord du widget véhicule",
    "Dashboard del widget veicoli",
    "Панель управления виджетом автомобилей",
    "Panel del widget de vehículos",
    "Araç widget paneli",
    "Painel do widget de veículos",
    "车辆小组件面板",
    "Panel widżetu pojazdów",
    "Paneli i widget-it të automjeteve"
  ]
} as const satisfies Readonly<Record<string, readonly string[]>>;

export const customerWorkflowSourceStrings = Object.keys(customerWorkflowExactTranslations);

export const customerWorkflowTemplateRows = [] as const;

export type CustomerWorkflowTranslationKey = (typeof customerWorkflowTemplateRows)[number][0];

const translators = createCustomerWorkflowClientTranslators(
  customerWorkflowExactTranslations,
  customerWorkflowTemplateRows,
);

export function customerWorkflowExactT(locale: LocaleCode, source: string) {
  return translators.exactT(locale, source);
}

export function customerWorkflowT(
  locale: LocaleCode,
  key: CustomerWorkflowTranslationKey,
  values: Record<string, string | number> = {},
) {
  return translators.t(locale, key, values);
}
