// This file is generated by scripts/generate-customer-workflow-client-translations.ts.
// Edit the master catalog or group source inventory, then regenerate it.

import type { LocaleCode } from "@/lib/i18nConfig";
import {
  createCustomerWorkflowClientTranslators,
  translateCustomerNotification,
} from "@/lib/i18n/customer-workflow-client-runtime";
import type {
  CustomerNotificationI18nInput,
  CustomerWorkflowTemplateTranslator,
} from "@/lib/i18n/customer-workflow-client-runtime";

export const customerWorkflowLocaleOrder = [
  "nl",
  "de",
  "fr",
  "it",
  "ru",
  "es",
  "tr",
  "pt",
  "zh",
  "pl",
  "sq"
] as const satisfies readonly Exclude<LocaleCode, "en">[];

export const customerWorkflowExactTranslations = {} as const satisfies Readonly<Record<string, readonly string[]>>;

export const customerWorkflowTemplateRows = [
  [
    "notificationAdditionalUploadBody",
    "You can now upload another file inside this request.",
    "U kunt nu nog een bestand aan deze aanvraag toevoegen.",
    "Sie können jetzt eine weitere Datei in diesem Auftrag hochladen.",
    "Vous pouvez désormais ajouter un autre fichier à cette demande.",
    "Ora puoi caricare un altro file in questa richiesta.",
    "Теперь вы можете загрузить ещё один файл в эту заявку.",
    "Ya puede subir otro archivo a esta solicitud.",
    "Artık bu siparişe bir dosya daha yükleyebilirsiniz.",
    "Agora pode carregar outro ficheiro neste pedido.",
    "您现在可以在此请求中上传另一个文件。",
    "Możesz teraz przesłać kolejny plik do tego zlecenia.",
    "Tani mund të ngarkoni një skedar tjetër në këtë kërkesë."
  ],
  [
    "notificationAdditionalUploadTitle",
    "Additional file upload enabled",
    "Aanvullende bestandsupload ingeschakeld",
    "Zusätzlicher Datei-Upload freigeschaltet",
    "Téléversement de fichier supplémentaire activé",
    "Upload file aggiuntivo abilitato",
    "Дополнительная загрузка файла разрешена",
    "Carga adicional habilitada",
    "Ek dosya yükleme açıldı",
    "Carregamento adicional ativado",
    "已启用附加文件上传",
    "Włączono dodatkowe przesyłanie pliku",
    "U aktivizua ngarkimi shtesë"
  ],
  [
    "notificationFileReadyBody",
    "Your completed file is ready to download.",
    "Uw voltooide bestand kan worden gedownload.",
    "Ihre fertige Datei steht zum Download bereit.",
    "Votre fichier final est prêt à être téléchargé.",
    "Il file completato è pronto per il download.",
    "Готовый файл доступен для скачивания.",
    "El archivo terminado está listo para descargar.",
    "Tamamlanan dosyanız indirilmeye hazır.",
    "O ficheiro concluído está pronto para descarregar.",
    "已完成的文件可供下载。",
    "Gotowy plik jest dostępny do pobrania.",
    "Skedari juaj i përfunduar është gati për t’u shkarkuar."
  ],
  [
    "notificationFileReadyTitle",
    "Your file is ready",
    "Uw bestand is klaar",
    "Ihre Datei ist fertig",
    "Votre fichier est prêt",
    "Il tuo file è pronto",
    "Ваш файл готов",
    "Tu archivo está listo",
    "Dosyanız hazır",
    "O seu ficheiro está pronto",
    "您的文件已准备好",
    "Twój plik jest gotowy",
    "Skedari juaj është gati"
  ],
  [
    "notificationNewMessageTitle",
    "New message from MG AutoTech",
    "Nieuw bericht van MG AutoTech",
    "Neue Nachricht von MG AutoTech",
    "Nouveau message de MG AutoTech",
    "Nuovo messaggio da MG AutoTech",
    "Новое сообщение от MG AutoTech",
    "Nuevo mensaje de MG AutoTech",
    "MG AutoTech'ten yeni mesaj",
    "Nova mensagem da MG AutoTech",
    "来自 MG AutoTech 的新消息",
    "Nowa wiadomość od MG AutoTech",
    "Mesazh i ri nga MG AutoTech"
  ],
  [
    "notificationNewStatus",
    "New status: {status}",
    "Nieuwe status: {status}",
    "Neuer Status: {status}",
    "Nouveau statut : {status}",
    "Nuovo stato: {status}",
    "Новый статус: {status}",
    "Nuevo estado: {status}",
    "Yeni durum: {status}",
    "Novo estado: {status}",
    "新状态：{status}",
    "Nowy status: {status}",
    "Statusi i ri: {status}"
  ],
  [
    "notificationOrderStatusTitle",
    "Order status updated",
    "Orderstatus bijgewerkt",
    "Auftragsstatus aktualisiert",
    "Statut de la commande mis à jour",
    "Stato ordine aggiornato",
    "Статус заказа обновлён",
    "Estado del pedido actualizado",
    "Sipariş durumu güncellendi",
    "Estado do pedido atualizado",
    "订单状态已更新",
    "Status zlecenia zaktualizowany",
    "Statusi i porosisë u përditësua"
  ],
  [
    "notificationTypeAdditionalUpload",
    "Additional upload",
    "Extra upload",
    "Zusätzlicher Upload",
    "Envoi supplémentaire",
    "Caricamento aggiuntivo",
    "Дополнительная загрузка",
    "Carga adicional",
    "Ek yükleme",
    "Carregamento adicional",
    "附加上传",
    "Dodatkowe przesyłanie",
    "Ngarkim shtesë"
  ],
  [
    "notificationTypeAdminMessage",
    "Admin message",
    "Beheerdersbericht",
    "Admin-Nachricht",
    "Message de l’administrateur",
    "Messaggio dell’amministratore",
    "Сообщение администратора",
    "Mensaje del administrador",
    "Yönetici mesajı",
    "Mensagem do administrador",
    "管理员消息",
    "Wiadomość administratora",
    "Mesazh nga administratori"
  ],
  [
    "notificationTypeFileReady",
    "File ready",
    "Bestand gereed",
    "Datei fertig",
    "Fichier prêt",
    "File pronto",
    "Файл готов",
    "Archivo listo",
    "Dosya hazır",
    "Ficheiro pronto",
    "文件已就绪",
    "Plik gotowy",
    "Skedari gati"
  ],
  [
    "notificationTypeOrderStatus",
    "Order status",
    "Orderstatus",
    "Auftragsstatus",
    "Statut de la commande",
    "Stato dell’ordine",
    "Статус заказа",
    "Estado del pedido",
    "Sipariş durumu",
    "Estado do pedido",
    "订单状态",
    "Status zlecenia",
    "Statusi i porosisë"
  ],
  [
    "notificationTypeSystem",
    "System",
    "Systeem",
    "System",
    "Système",
    "Sistema",
    "Система",
    "Sistema",
    "Sistem",
    "Sistema",
    "系统",
    "System",
    "Sistemi"
  ],
  [
    "statusCancelled",
    "Cancelled",
    "Geannuleerd",
    "Abgesagt",
    "Annulé",
    "Annullato",
    "Отменено",
    "Cancelado",
    "İptal edildi",
    "Cancelado",
    "取消",
    "Anulowano",
    "Anuluar"
  ],
  [
    "statusCompleted",
    "Completed",
    "Voltooid",
    "Abgeschlossen",
    "Terminé",
    "Completato",
    "Завершено",
    "Completado",
    "Tamamlandı",
    "Concluído",
    "已完成",
    "Zakończono",
    "Përfunduar"
  ],
  [
    "statusCustomerInfoNeeded",
    "Customer information needed",
    "Klantgegevens vereist",
    "Kundeninformationen erforderlich",
    "Informations client requises",
    "Informazioni cliente necessarie",
    "Требуется информация от клиента",
    "Se necesita información del cliente",
    "Müşteri bilgisi gerekli",
    "Informações do cliente necessárias",
    "需要客户信息",
    "Wymagane informacje od klienta",
    "Nevojiten të dhëna nga klienti"
  ],
  [
    "statusFileCheck",
    "File check",
    "Bestandscontrole",
    "Dateiprüfung",
    "Vérification des fichiers",
    "Controllo file",
    "Проверка файла",
    "Verificación de archivos",
    "Dosya Kontrolü",
    "Verificação de ficheiro",
    "文件检查",
    "Kontrola pliku",
    "Kontrolli i skedarit"
  ],
  [
    "statusInProgress",
    "In progress",
    "In behandeling",
    "In Bearbeitung",
    "En cours",
    "In lavorazione",
    "В работе",
    "En curso",
    "İşlemde",
    "Em curso",
    "处理中",
    "W toku",
    "Në proces"
  ],
  [
    "statusNewRequest",
    "New request",
    "Nieuwe aanvraag",
    "Neue Anfrage",
    "Nouvelle demande",
    "Nuova richiesta",
    "Новая заявка",
    "Nueva solicitud",
    "Yeni talep",
    "Novo pedido",
    "新请求",
    "Nowe zlecenie",
    "Kërkesë e re"
  ],
  [
    "statusRevision",
    "Revision",
    "Revisie",
    "Revision",
    "Révision",
    "Revisione",
    "Доработка",
    "Revisión",
    "Revizyon",
    "Revisão",
    "修订",
    "Korekta",
    "Rishikim"
  ]
] as const;

export type CustomerWorkflowTranslationKey = (typeof customerWorkflowTemplateRows)[number][0];

const translators = createCustomerWorkflowClientTranslators(
  customerWorkflowExactTranslations,
  customerWorkflowTemplateRows,
);

export function customerWorkflowExactT(locale: LocaleCode, source: string) {
  return translators.exactT(locale, source);
}

export function customerWorkflowT(
  locale: LocaleCode,
  key: CustomerWorkflowTranslationKey,
  values: Record<string, string | number> = {},
) {
  return translators.t(locale, key, values);
}

export type { CustomerNotificationI18nInput };

export function localizeCustomerNotification(
  locale: LocaleCode,
  item: CustomerNotificationI18nInput,
) {
  return translateCustomerNotification(
    locale,
    item,
    customerWorkflowT as CustomerWorkflowTemplateTranslator,
  );
}
