import type { LocaleCode } from "@/lib/i18nConfig";

const widgetSiteAllLocaleOrder = [
  "en", "de", "nl", "fr", "it", "ru", "es", "tr", "pt", "zh", "pl", "sq",
] as const satisfies readonly LocaleCode[];

export const widgetSiteLocaleOrder = [
  "de", "nl", "fr", "it", "ru", "es", "tr", "pt", "zh", "pl", "sq",
] as const satisfies readonly Exclude<LocaleCode, "en">[];

type TranslationRow = readonly [
  key: string,
  en: string,
  de: string,
  nl: string,
  fr: string,
  it: string,
  ru: string,
  es: string,
  tr: string,
  pt: string,
  zh: string,
  pl: string,
  sq: string,
];

const widgetSiteRows = [
  ["login", "Login", "Anmelden", "Inloggen", "Connexion", "Accedi", "Войти", "Iniciar sesión", "Giriş yap", "Iniciar sessão", "登录", "Zaloguj się", "Hyr"],
  ["customerDashboard", "Customer dashboard", "Kundenportal", "Klantdashboard", "Espace client", "Area cliente", "Личный кабинет", "Panel de cliente", "Müşteri paneli", "Área de cliente", "客户面板", "Panel klienta", "Paneli i klientit"],
  ["vehicleWidget", "VEHICLE WIDGET", "FAHRZEUG-WIDGET", "VOERTUIGWIDGET", "WIDGET VÉHICULE", "WIDGET VEICOLI", "ВИДЖЕТ АВТОМОБИЛЕЙ", "WIDGET DE VEHÍCULOS", "ARAÇ WIDGET'I", "WIDGET DE VEÍCULOS", "车辆小组件", "WIDŻET POJAZDÓW", "WIDGET-I I AUTOMJETEVE"],
  ["widgetMetaOffer", "A hosted multilingual vehicle selector for tuning and workshop websites, available for €4.99 / month.", "Ein gehosteter mehrsprachiger Fahrzeugselektor für Tuning- und Werkstatt-Websites, verfügbar für 4,99 € pro Monat.", "Een gehoste meertalige voertuigselector voor tuning- en werkplaatswebsites, beschikbaar voor € 4,99 per maand.", "Un sélecteur de véhicules multilingue hébergé pour les sites de préparation automobile et d’ateliers, disponible à 4,99 € par mois.", "Un selettore di veicoli multilingue ospitato per siti di tuning e officine, disponibile a 4,99 € al mese.", "Размещённый многоязычный подбор автомобилей для сайтов тюнинга и мастерских за 4,99 € в месяц.", "Un selector de vehículos multilingüe alojado para sitios web de tuning y talleres, disponible por 4,99 € al mes.", "Tuning ve servis web siteleri için barındırılan çok dilli araç seçici; aylık 4,99 €.", "Um seletor de veículos multilingue alojado para sites de tuning e oficinas, disponível por 4,99 € por mês.", "面向汽车改装与维修厂网站的托管式多语言车辆选择器，每月 4.99 欧元。", "Hostowany wielojęzyczny selektor pojazdów dla stron tuningowych i warsztatowych, dostępny za 4,99 € miesięcznie.", "Një përzgjedhës shumëgjuhësh automjetesh i hostuar për faqet e tuningut dhe serviseve, i disponueshëm për 4,99 € në muaj."],
  ["widgetMetaEmbed", "Embed a hosted, multilingual vehicle selector on your tuning or workshop website for €4.99 / month.", "Binden Sie für 4,99 € pro Monat einen gehosteten, mehrsprachigen Fahrzeugselektor in Ihre Tuning- oder Werkstatt-Website ein.", "Integreer voor € 4,99 per maand een gehoste, meertalige voertuigselector in uw tuning- of werkplaatswebsite.", "Intégrez un sélecteur de véhicules multilingue hébergé à votre site de préparation automobile ou d’atelier pour 4,99 € par mois.", "Integra nel tuo sito di tuning o dell’officina un selettore di veicoli multilingue ospitato a 4,99 € al mese.", "Встройте размещённый многоязычный подбор автомобилей на сайт тюнинга или мастерской за 4,99 € в месяц.", "Integre en su sitio web de tuning o taller un selector de vehículos multilingüe alojado por 4,99 € al mes.", "Tuning veya servis web sitenize aylık 4,99 € karşılığında barındırılan çok dilli bir araç seçici ekleyin.", "Integre no seu site de tuning ou oficina um seletor de veículos multilingue alojado por 4,99 € por mês.", "只需每月 4.99 欧元，即可在您的汽车改装或维修厂网站中嵌入托管式多语言车辆选择器。", "Osadź na swojej stronie tuningowej lub warsztatowej hostowany wielojęzyczny selektor pojazdów za 4,99 € miesięcznie.", "Integroni në faqen tuaj të tuningut ose servisit një përzgjedhës shumëgjuhësh automjetesh të hostuar për 4,99 € në muaj."],
  ["widgetMetaLookup", "Hosted multilingual vehicle lookup for automotive websites.", "Gehostete mehrsprachige Fahrzeugsuche für Automotive-Websites.", "Gehoste meertalige voertuigzoekfunctie voor automotivewebsites.", "Recherche de véhicules multilingue hébergée pour les sites automobiles.", "Ricerca veicoli multilingue ospitata per siti automotive.", "Размещённый многоязычный поиск автомобилей для автомобильных сайтов.", "Búsqueda de vehículos multilingüe alojada para sitios web de automoción.", "Otomotiv web siteleri için barındırılan çok dilli araç arama.", "Pesquisa de veículos multilingue alojada para sites automóveis.", "面向汽车网站的托管式多语言车辆查询。", "Hostowana wielojęzyczna wyszukiwarka pojazdów dla stron motoryzacyjnych.", "Kërkim shumëgjuhësh automjetesh i hostuar për faqet automobilistike."],
  ["widgetMetaSelector", "Hosted multilingual vehicle selector for automotive tuning and workshop websites.", "Gehosteter mehrsprachiger Fahrzeugselektor für Tuning- und Werkstatt-Websites.", "Gehoste meertalige voertuigselector voor tuning- en werkplaatswebsites.", "Sélecteur de véhicules multilingue hébergé pour les sites de préparation automobile et d’ateliers.", "Selettore di veicoli multilingue ospitato per siti di tuning e officine.", "Размещённый многоязычный подбор автомобилей для сайтов тюнинга и мастерских.", "Selector de vehículos multilingüe alojado para sitios web de tuning y talleres.", "Otomotiv tuning ve servis web siteleri için barındırılan çok dilli araç seçici.", "Seletor de veículos multilingue alojado para sites de tuning automóvel e oficinas.", "面向汽车改装与维修厂网站的托管式多语言车辆选择器。", "Hostowany wielojęzyczny selektor pojazdów dla stron tuningu samochodowego i warsztatów.", "Përzgjedhës shumëgjuhësh automjetesh i hostuar për faqet e tuningut dhe serviseve automobilistike."],
  ["widgetMetaTitleShort", "Vehicle Selector Widget | MG AutoTech", "Fahrzeugauswahl-Widget | MG AutoTech", "Voertuigselector-widget | MG AutoTech", "Widget de sélection de véhicules | MG AutoTech", "Widget di selezione veicoli | MG AutoTech", "Виджет подбора автомобилей | MG AutoTech", "Widget de selección de vehículos | MG AutoTech", "Araç seçici widget'ı | MG AutoTech", "Widget de seleção de veículos | MG AutoTech", "车辆选择器小组件 | MG AutoTech", "Widżet wyboru pojazdu | MG AutoTech", "Widget për përzgjedhjen e automjeteve | MG AutoTech"],
  ["widgetMetaTitle", "Vehicle Selector Widget for Automotive Websites", "Fahrzeugauswahl-Widget für Automotive-Websites", "Voertuigselector-widget voor automotivewebsites", "Widget de sélection de véhicules pour sites automobiles", "Widget di selezione veicoli per siti automotive", "Виджет подбора автомобилей для автомобильных сайтов", "Widget de selección de vehículos para sitios web de automoción", "Otomotiv web siteleri için araç seçici widget'ı", "Widget de seleção de veículos para sites automóveis", "面向汽车网站的车辆选择器小组件", "Widżet wyboru pojazdu dla stron motoryzacyjnych", "Widget për përzgjedhjen e automjeteve për faqet automobilistike"],
  ["widgetMetaTitleBrand", "Vehicle Selector Widget for Automotive Websites | MG AutoTech", "Fahrzeugauswahl-Widget für Automotive-Websites | MG AutoTech", "Voertuigselector-widget voor automotivewebsites | MG AutoTech", "Widget de sélection de véhicules pour sites automobiles | MG AutoTech", "Widget di selezione veicoli per siti automotive | MG AutoTech", "Виджет подбора автомобилей для автомобильных сайтов | MG AutoTech", "Widget de selección de vehículos para sitios web de automoción | MG AutoTech", "Otomotiv web siteleri için araç seçici widget'ı | MG AutoTech", "Widget de seleção de veículos para sites automóveis | MG AutoTech", "面向汽车网站的车辆选择器小组件 | MG AutoTech", "Widżet wyboru pojazdu dla stron motoryzacyjnych | MG AutoTech", "Widget për përzgjedhjen e automjeteve për faqet automobilistike | MG AutoTech"],
  ["widgetDashboardMetaDescription", "Manage your MG AutoTech Vehicle Selector Widget subscription and installation.", "Verwalten Sie Ihr Abonnement und die Installation des MG AutoTech Fahrzeugauswahl-Widgets.", "Beheer uw abonnement en installatie van de MG AutoTech voertuigselector-widget.", "Gérez l’abonnement et l’installation de votre widget de sélection de véhicules MG AutoTech.", "Gestisci l’abbonamento e l’installazione del widget di selezione veicoli MG AutoTech.", "Управляйте подпиской и установкой виджета подбора автомобилей MG AutoTech.", "Gestione la suscripción e instalación de su widget de selección de vehículos MG AutoTech.", "MG AutoTech araç seçici widget aboneliğinizi ve kurulumunuzu yönetin.", "Faça a gestão da subscrição e instalação do seu widget de seleção de veículos MG AutoTech.", "管理您的 MG AutoTech 车辆选择器小组件订阅和安装。", "Zarządzaj subskrypcją i instalacją widżetu wyboru pojazdu MG AutoTech.", "Menaxhoni abonimin dhe instalimin e widget-it për përzgjedhjen e automjeteve MG AutoTech."],
  ["widgetDashboardMetaTitle", "Vehicle Widget Dashboard", "Dashboard für das Fahrzeug-Widget", "Dashboard voor de voertuigwidget", "Tableau de bord du widget véhicule", "Dashboard del widget veicoli", "Панель управления виджетом автомобилей", "Panel del widget de vehículos", "Araç widget paneli", "Painel do widget de veículos", "车辆小组件面板", "Panel widżetu pojazdów", "Paneli i widget-it të automjeteve"],
  ["hostedDataEyebrow", "Hosted vehicle data for your website", "Gehostete Fahrzeugdaten für Ihre Website", "Gehoste voertuiggegevens voor uw website", "Données de véhicules hébergées pour votre site", "Dati veicolo ospitati per il tuo sito", "Размещённые данные автомобилей для вашего сайта", "Datos de vehículos alojados para su sitio web", "Web siteniz için barındırılan araç verileri", "Dados de veículos alojados para o seu site", "为您的网站托管车辆数据", "Hostowane dane pojazdów dla Twojej strony", "Të dhëna automjetesh të hostuara për faqen tuaj"],
  ["salesTitle", "Professional Vehicle Selector for Your Website", "Professionelle Fahrzeugauswahl für Ihre Website", "Professionele voertuigselector voor uw website", "Sélecteur de véhicules professionnel pour votre site", "Selettore professionale di veicoli per il tuo sito", "Профессиональный подбор автомобиля для вашего сайта", "Selector profesional de vehículos para su sitio web", "Web siteniz için profesyonel araç seçici", "Seletor profissional de veículos para o seu site", "适用于您网站的专业车辆选择器", "Profesjonalny selektor pojazdów na Twoją stronę", "Përzgjedhës profesional automjetesh për faqen tuaj"],
  ["salesLead", "Add a maintained vehicle database to your tuning, workshop or automotive website. One code, one protected domain and automatic updates.", "Ergänzen Sie Ihre Tuning-, Werkstatt- oder Automotive-Website um eine gepflegte Fahrzeugdatenbank. Ein Code, eine geschützte Domain und automatische Updates.", "Voeg een onderhouden voertuigdatabase toe aan uw tuning-, werkplaats- of automotivewebsite. Eén code, één beveiligd domein en automatische updates.", "Ajoutez une base de données de véhicules tenue à jour à votre site de préparation, d’atelier ou automobile. Un seul code, un domaine protégé et des mises à jour automatiques.", "Aggiungi un database veicoli aggiornato al tuo sito di tuning, officina o automotive. Un solo codice, un dominio protetto e aggiornamenti automatici.", "Добавьте поддерживаемую базу автомобилей на сайт тюнинга, мастерской или автосервиса. Один код, один защищённый домен и автоматические обновления.", "Añada una base de datos de vehículos actualizada a su web de tuning, taller o automoción. Un código, un dominio protegido y actualizaciones automáticas.", "Tuning, servis veya otomotiv web sitenize düzenli güncellenen bir araç veritabanı ekleyin. Tek kod, korumalı tek alan adı ve otomatik güncellemeler.", "Adicione uma base de dados de veículos atualizada ao seu site de tuning, oficina ou automóvel. Um código, um domínio protegido e atualizações automáticas.", "为您的改装、维修厂或汽车网站添加持续维护的车辆数据库。只需一段代码、一个受保护域名，并可自动更新。", "Dodaj aktualizowaną bazę pojazdów do strony tuningu, warsztatu lub branży motoryzacyjnej. Jeden kod, jedna chroniona domena i automatyczne aktualizacje.", "Shtoni një bazë të mirëmbajtur automjetesh në faqen tuaj të tuningut, servisit ose automobilistike. Një kod, një domen i mbrojtur dhe përditësime automatike."],
  ["startMonthly", "Start now for {price} per month", "Jetzt für {price} pro Monat starten", "Start nu voor {price} per maand", "Commencer maintenant pour {price} par mois", "Inizia ora a {price} al mese", "Начать сейчас за {price} в месяц", "Empiece ahora por {price} al mes", "Şimdi aylık {price} ile başlayın", "Começar agora por {price} por mês", "立即开始，每月 {price}", "Zacznij teraz za {price} miesięcznie", "Filloni tani për {price} në muaj"],
  ["tryDemo", "Try the live demo", "Live-Demo testen", "Live demo proberen", "Essayer la démo en direct", "Prova la demo dal vivo", "Попробовать демоверсию", "Probar la demostración en directo", "Canlı demoyu deneyin", "Experimentar a demonstração ao vivo", "试用实时演示", "Wypróbuj demo na żywo", "Provoni demonstrimin drejtpërdrejt"],
  ["includedStarter", "Included in Starter", "Im Starter-Paket enthalten", "Inbegrepen bij Starter", "Inclus dans l’offre Starter", "Incluso nel piano Starter", "Включено в тариф Starter", "Incluido en Starter", "Başlangıç paketine dahil", "Incluído no plano Starter", "Starter 套餐已包含", "W cenie planu Starter", "Përfshihet në paketën Starter"],
  ["companyName", "Company name", "Firmenname", "Bedrijfsnaam", "Nom de l’entreprise", "Nome dell’azienda", "Название компании", "Nombre de la empresa", "Şirket adı", "Nome da empresa", "公司名称", "Nazwa firmy", "Emri i kompanisë"],
  ["emailAddress", "Email address", "E-Mail-Adresse", "E-mailadres", "Adresse e-mail", "Indirizzo e-mail", "Адрес электронной почты", "Correo electrónico", "E-posta adresi", "Endereço de e-mail", "电子邮箱", "Adres e-mail", "Adresa e emailit"],
  ["websiteDomain", "Website domain", "Website-Domain", "Websitedomein", "Domaine du site", "Dominio del sito", "Домен сайта", "Dominio del sitio web", "Web sitesi alan adı", "Domínio do site", "网站域名", "Domena strony", "Domeni i faqes"],
  ["preferredLanguage", "Preferred language", "Bevorzugte Sprache", "Voorkeurstaal", "Langue préférée", "Lingua preferita", "Предпочитаемый язык", "Idioma preferido", "Tercih edilen dil", "Idioma preferido", "首选语言", "Preferowany język", "Gjuha e preferuar"],
  ["startSubscription", "Start subscription", "Abonnement starten", "Abonnement starten", "Démarrer l’abonnement", "Avvia l’abbonamento", "Оформить подписку", "Iniciar suscripción", "Aboneliği başlat", "Iniciar subscrição", "开始订阅", "Rozpocznij subskrypcję", "Fillo abonimin"],
  ["noCoding", "No coding required", "Keine Programmierung erforderlich", "Geen programmeerkennis nodig", "Aucun code requis", "Non serve programmare", "Программирование не требуется", "No se necesita programar", "Kodlama gerekmez", "Sem programação", "无需编程", "Bez programowania", "Nuk kërkohet programim"],
  ["controlledB2b", "Built for controlled B2B integration", "Für kontrollierte B2B-Integration entwickelt", "Ontwikkeld voor gecontroleerde B2B-integratie", "Conçu pour une intégration B2B maîtrisée", "Progettato per un’integrazione B2B controllata", "Создано для контролируемой B2B-интеграции", "Creado para una integración B2B controlada", "Kontrollü B2B entegrasyonu için geliştirildi", "Criado para uma integração B2B controlada", "专为可控的 B2B 集成而设计", "Stworzone z myślą o kontrolowanej integracji B2B", "Ndërtuar për integrim të kontrolluar B2B"],
  ["verifiedBillingEmailRequired", "Please sign in with your verified billing email before starting a subscription.", "Bitte melden Sie sich vor Abschluss eines Abonnements mit Ihrer bestätigten Abrechnungs-E-Mail-Adresse an.", "Log in met uw geverifieerde facturatie-e-mailadres voordat u een abonnement start.", "Connectez-vous avec votre adresse e-mail de facturation vérifiée avant de souscrire.", "Accedi con l’indirizzo e-mail di fatturazione verificato prima di avviare un abbonamento.", "Перед оформлением подписки войдите с подтверждённым платёжным адресом электронной почты.", "Inicie sesión con su correo de facturación verificado antes de contratar una suscripción.", "Aboneliği başlatmadan önce doğrulanmış fatura e-posta adresinizle giriş yapın.", "Inicie sessão com o e-mail de faturação verificado antes de iniciar uma subscrição.", "开始订阅前，请使用已验证的账单邮箱登录。", "Przed rozpoczęciem subskrypcji zaloguj się zweryfikowanym adresem e-mail do rozliczeń.", "Para se të filloni abonimin, hyni me emailin e verifikuar të faturimit."],
  ["checkoutFailed", "Checkout could not be started.", "Der Bezahlvorgang konnte nicht gestartet werden.", "Het afrekenen kon niet worden gestart.", "Le paiement n’a pas pu être lancé.", "Non è stato possibile avviare il pagamento.", "Не удалось начать оформление оплаты.", "No se pudo iniciar el pago.", "Ödeme işlemi başlatılamadı.", "Não foi possível iniciar o pagamento.", "无法开始结账。", "Nie udało się rozpocząć płatności.", "Pagesa nuk mund të nisej."],
  ["subscriptionsUnavailable", "New widget subscriptions are currently unavailable.", "Neue Widget-Abonnements sind derzeit nicht verfügbar.", "Nieuwe widgetabonnementen zijn momenteel niet beschikbaar.", "Les nouveaux abonnements au widget sont actuellement indisponibles.", "I nuovi abbonamenti al widget non sono al momento disponibili.", "Новые подписки на виджет сейчас недоступны.", "Las nuevas suscripciones al widget no están disponibles en este momento.", "Yeni widget abonelikleri şu anda kullanılamıyor.", "As novas subscrições do widget estão temporariamente indisponíveis.", "目前无法新订阅此小组件。", "Nowe subskrypcje widżetu są obecnie niedostępne.", "Abonimet e reja të widget-it nuk janë aktualisht të disponueshme."],
  ["checkoutUnavailable", "Online checkout is currently unavailable. Please contact MG AutoTech.", "Die Online-Zahlung ist derzeit nicht verfügbar. Bitte kontaktieren Sie MG AutoTech.", "Online afrekenen is momenteel niet beschikbaar. Neem contact op met MG AutoTech.", "Le paiement en ligne est actuellement indisponible. Contactez MG AutoTech.", "Il pagamento online non è al momento disponibile. Contatta MG AutoTech.", "Онлайн-оплата сейчас недоступна. Свяжитесь с MG AutoTech.", "El pago en línea no está disponible en este momento. Contacte con MG AutoTech.", "Çevrim içi ödeme şu anda kullanılamıyor. Lütfen MG AutoTech ile iletişime geçin.", "O pagamento online está temporariamente indisponível. Contacte a MG AutoTech.", "目前无法在线结账，请联系 MG AutoTech。", "Płatność online jest obecnie niedostępna. Skontaktuj się z MG AutoTech.", "Pagesa online nuk është aktualisht e disponueshme. Kontaktoni MG AutoTech."],
  ["subscriptionsPreparing", "Widget subscriptions are being prepared.", "Widget-Abonnements werden vorbereitet.", "Widgetabonnementen worden voorbereid.", "Les abonnements au widget sont en cours de préparation.", "Gli abbonamenti al widget sono in preparazione.", "Подписки на виджет готовятся к запуску.", "Las suscripciones al widget se están preparando.", "Widget abonelikleri hazırlanıyor.", "As subscrições do widget estão a ser preparadas.", "小组件订阅正在准备中。", "Subskrypcje widżetu są przygotowywane.", "Abonimet e widget-it po përgatiten."],
  ["perMonth", "per month", "pro Monat", "per maand", "par mois", "al mese", "в месяц", "al mes", "aylık", "por mês", "每月", "miesięcznie", "në muaj"],
  ["hosted", "Hosted", "Gehostet", "Gehost", "Hébergé", "Ospitato", "Размещено", "Alojado", "Barındırılıyor", "Alojado", "托管服务", "Hostowane", "I hostuar"],
  ["oneWebsiteDomain", "1 website / domain", "1 Website / Domain", "1 website / domein", "1 site / domaine", "1 sito / dominio", "1 сайт / домен", "1 sitio web / dominio", "1 web sitesi / alan adı", "1 site / domínio", "1 个网站 / 域名", "1 strona / domena", "1 faqe / domen"],
  ["strictDomainAccess", "Strict domain-locked access", "Streng auf die Domain beschränkter Zugriff", "Strikt domeingebonden toegang", "Accès strictement limité au domaine", "Accesso strettamente vincolato al dominio", "Строгий доступ с привязкой к домену", "Acceso estrictamente vinculado al dominio", "Alan adına sıkı biçimde kilitli erişim", "Acesso estritamente limitado ao domínio", "严格限定域名访问", "Dostęp ściśle przypisany do domeny", "Akses i kufizuar rreptësisht sipas domenit"],
  ["automaticUpdates", "Automatic updates", "Automatische Updates", "Automatische updates", "Mises à jour automatiques", "Aggiornamenti automatici", "Автоматические обновления", "Actualizaciones automáticas", "Otomatik güncellemeler", "Atualizações automáticas", "自动更新", "Automatyczne aktualizacje", "Përditësime automatike"],
  ["noDatabaseMaintenance", "No database maintenance", "Keine Datenbankpflege", "Geen databaseonderhoud", "Aucune maintenance de base de données", "Nessuna manutenzione del database", "Без обслуживания базы данных", "Sin mantenimiento de la base de datos", "Veritabanı bakımı gerekmez", "Sem manutenção da base de dados", "无需维护数据库", "Bez obsługi bazy danych", "Pa mirëmbajtje të bazës së të dhënave"],
  ["scriptIframe", "Script + iframe", "Skript + iFrame", "Script + iframe", "Script + iframe", "Script + iframe", "Скрипт + iframe", "Script + iframe", "Script + iframe", "Script + iframe", "脚本 + iframe", "Skrypt + iframe", "Skript + iframe"],
  ["noNpmPackages", "Works without npm packages", "Funktioniert ohne npm-Pakete", "Werkt zonder npm-pakketten", "Fonctionne sans paquet npm", "Funziona senza pacchetti npm", "Работает без пакетов npm", "Funciona sin paquetes npm", "npm paketi olmadan çalışır", "Funciona sem pacotes npm", "无需 npm 包即可运行", "Działa bez pakietów npm", "Funksionon pa paketa npm"],
  ["mgHosted", "MG AutoTech hosted", "Von MG AutoTech gehostet", "Gehost door MG AutoTech", "Hébergé par MG AutoTech", "Ospitato da MG AutoTech", "Размещено MG AutoTech", "Alojado por MG AutoTech", "MG AutoTech tarafından barındırılır", "Alojado pela MG AutoTech", "由 MG AutoTech 托管", "Hostowane przez MG AutoTech", "I hostuar nga MG AutoTech"],
  ["controlledAccessLogs", "Controlled access and logs", "Kontrollierter Zugriff und Protokolle", "Gecontroleerde toegang en logboeken", "Accès et journaux contrôlés", "Accesso e registri controllati", "Контролируемый доступ и журналы", "Acceso y registros controlados", "Kontrollü erişim ve kayıtlar", "Acesso e registos controlados", "访问和日志可控", "Kontrolowany dostęp i dzienniki", "Akses dhe regjistra të kontrolluar"],
  ["interactiveDemo", "Interactive demo", "Interaktive Demo", "Interactieve demo", "Démo interactive", "Demo interattiva", "Интерактивная демонстрация", "Demostración interactiva", "Etkileşimli demo", "Demonstração interativa", "交互式演示", "Interaktywne demo", "Demonstrim interaktiv"],
  ["seeBeforeSubscribe", "See it before you subscribe.", "Vor dem Abonnieren ansehen.", "Bekijk het voordat u zich abonneert.", "Découvrez-le avant de vous abonner.", "Provalo prima di abbonarti.", "Посмотрите до оформления подписки.", "Pruébelo antes de suscribirse.", "Abone olmadan önce deneyin.", "Veja antes de subscrever.", "订阅前先体验。", "Zobacz przed wykupieniem subskrypcji.", "Shikojeni para se të abonoheni."],
  ["demoDescription", "Change the language, colour and display mode. Your customer dashboard provides the same controls with a production embed code.", "Ändern Sie Sprache, Farbe und Darstellung. Ihr Kundenportal bietet dieselben Einstellungen zusammen mit einem produktiven Einbettungscode.", "Wijzig taal, kleur en weergavemodus. Uw klantdashboard biedt dezelfde instellingen met een productieklare insluitcode.", "Modifiez la langue, la couleur et le mode d’affichage. Votre espace client propose les mêmes réglages avec un code d’intégration prêt pour la production.", "Modifica lingua, colore e modalità di visualizzazione. L’area cliente offre gli stessi controlli con un codice di integrazione pronto per la produzione.", "Измените язык, цвет и режим отображения. В личном кабинете доступны те же настройки и рабочий код встраивания.", "Cambie el idioma, el color y el modo de visualización. El panel de cliente ofrece los mismos controles con un código de inserción listo para producción.", "Dili, rengi ve görünüm modunu değiştirin. Müşteri paneliniz aynı kontrolleri canlı kullanım yerleştirme koduyla sunar.", "Altere o idioma, a cor e o modo de apresentação. A área de cliente oferece os mesmos controlos com um código de integração pronto para produção.", "更改语言、颜色和显示模式。客户面板提供相同控制项，并生成可用于正式环境的嵌入代码。", "Zmień język, kolor i tryb wyświetlania. Panel klienta udostępnia te same ustawienia wraz z produkcyjnym kodem osadzania.", "Ndryshoni gjuhën, ngjyrën dhe mënyrën e shfaqjes. Paneli i klientit ofron të njëjtat kontrolle me kodin e integrimit për prodhim."],
  ["language", "Language", "Sprache", "Taal", "Langue", "Lingua", "Язык", "Idioma", "Dil", "Idioma", "语言", "Język", "Gjuha"],
  ["theme", "Theme", "Design", "Thema", "Thème", "Tema", "Тема", "Tema", "Tema", "Tema", "主题", "Motyw", "Tema"],
  ["mainColour", "Main colour", "Hauptfarbe", "Hoofdkleur", "Couleur principale", "Colore principale", "Основной цвет", "Color principal", "Ana renk", "Cor principal", "主色", "Kolor główny", "Ngjyra kryesore"],
  ["light", "Light", "Hell", "Licht", "Clair", "Chiaro", "Светлая", "Claro", "Açık", "Claro", "浅色", "Jasny", "E çelët"],
  ["dark", "Dark", "Dunkel", "Donker", "Sombre", "Scuro", "Тёмная", "Oscuro", "Koyu", "Escuro", "深色", "Ciemny", "E errët"],
  ["auto", "Auto", "Automatisch", "Automatisch", "Automatique", "Automatico", "Автоматически", "Automático", "Otomatik", "Automático", "自动", "Automatyczny", "Automatik"],
  ["operationalControl", "Operational control is built in.", "Die operative Kontrolle ist integriert.", "Operationele controle is ingebouwd.", "Le contrôle opérationnel est intégré.", "Il controllo operativo è integrato.", "Операционный контроль встроен.", "El control operativo está integrado.", "Operasyon kontrolü sisteme dahildir.", "O controlo operacional está integrado.", "内置运营管控。", "Kontrola operacyjna jest wbudowana.", "Kontrolli operacional është i integruar."],
  ["secureStripePayments", "Secure payments by Stripe", "Sichere Zahlungen mit Stripe", "Veilige betalingen via Stripe", "Paiements sécurisés par Stripe", "Pagamenti sicuri con Stripe", "Безопасные платежи через Stripe", "Pagos seguros con Stripe", "Stripe ile güvenli ödemeler", "Pagamentos seguros com Stripe", "通过 Stripe 安全支付", "Bezpieczne płatności przez Stripe", "Pagesa të sigurta me Stripe"],
  ["hostedEu", "Hosted in the EU", "In der EU gehostet", "Gehost in de EU", "Hébergé dans l’UE", "Ospitato nell’UE", "Размещено в ЕС", "Alojado en la UE", "AB'de barındırılır", "Alojado na UE", "托管于欧盟", "Hostowane w UE", "I hostuar në BE"],
  ["automaticSubscriptionControl", "Automatic subscription control", "Automatische Abonnementsteuerung", "Automatisch abonnementsbeheer", "Gestion automatique de l’abonnement", "Gestione automatica dell’abbonamento", "Автоматическое управление подпиской", "Control automático de la suscripción", "Otomatik abonelik kontrolü", "Controlo automático da subscrição", "自动订阅管理", "Automatyczna obsługa subskrypcji", "Menaxhim automatik i abonimit"],
  ["domainLockedAccess", "Domain-locked access", "Domaingebundener Zugriff", "Domeingebonden toegang", "Accès limité au domaine", "Accesso vincolato al dominio", "Доступ с привязкой к домену", "Acceso vinculado al dominio", "Alan adına kilitli erişim", "Acesso limitado ao domínio", "域名锁定访问", "Dostęp przypisany do domeny", "Akses i lidhur me domenin"],
  ["noDatabaseExport", "No database export", "Kein Datenbankexport", "Geen database-export", "Aucun export de base de données", "Nessuna esportazione del database", "Без экспорта базы данных", "Sin exportación de la base de datos", "Veritabanı dışa aktarımı yok", "Sem exportação da base de dados", "不导出数据库", "Bez eksportu bazy danych", "Pa eksport të bazës së të dhënave"],
  ["oneDomainControl", "One domain. Full control. {price} per month.", "Eine Domain. Volle Kontrolle. {price} pro Monat.", "Eén domein. Volledige controle. {price} per maand.", "Un domaine. Contrôle total. {price} par mois.", "Un dominio. Controllo completo. {price} al mese.", "Один домен. Полный контроль. {price} в месяц.", "Un dominio. Control total. {price} al mes.", "Tek alan adı. Tam kontrol. Aylık {price}.", "Um domínio. Controlo total. {price} por mês.", "一个域名，全面掌控。每月 {price}。", "Jedna domena. Pełna kontrola. {price} miesięcznie.", "Një domen. Kontroll i plotë. {price} në muaj."],
  ["customerLanguages", "12 customer-facing languages", "12 Sprachen für Ihre Kunden", "12 talen voor klanten", "12 langues côté client", "12 lingue per i clienti", "12 языков для клиентов", "12 idiomas para clientes", "Müşterilere sunulan 12 dil", "12 idiomas para clientes", "支持 12 种客户界面语言", "12 języków dla klientów", "12 gjuhë për klientët"],
  ["automaticVehicleUpdates", "Automatic vehicle database updates", "Automatische Aktualisierung der Fahrzeugdatenbank", "Automatische updates van de voertuigdatabase", "Mises à jour automatiques de la base de véhicules", "Aggiornamenti automatici del database veicoli", "Автоматическое обновление базы автомобилей", "Actualizaciones automáticas de la base de vehículos", "Otomatik araç veritabanı güncellemeleri", "Atualizações automáticas da base de veículos", "车辆数据库自动更新", "Automatyczne aktualizacje bazy pojazdów", "Përditësime automatike të bazës së automjeteve"],
  ["liveCodePreview", "Live code generator and preview", "Live-Codegenerator und Vorschau", "Live codegenerator en voorbeeld", "Générateur de code et aperçu en direct", "Generatore di codice e anteprima dal vivo", "Генератор кода и предпросмотр в реальном времени", "Generador de código y vista previa en directo", "Canlı kod oluşturucu ve önizleme", "Gerador de código e pré-visualização em direto", "实时代码生成和预览", "Generator kodu i podgląd na żywo", "Gjenerues kodi dhe paraafishim drejtpërdrejt"],
  ["scriptIframeFallback", "Script embed and iframe fallback", "Skript-Einbettung mit iFrame-Fallback", "Scriptinsluiting met iframe als terugval", "Intégration par script avec solution iframe", "Integrazione tramite script con fallback iframe", "Встраивание скриптом и резервный iframe", "Inserción mediante script con iframe alternativo", "Script yerleştirme ve iframe yedeği", "Integração por script com alternativa iframe", "脚本嵌入及 iframe 兼容方案", "Osadzanie skryptem z rezerwowym iframe", "Integrim me skript dhe alternativë iframe"],
  ["domainValidationLogs", "Domain validation and access logs", "Domainprüfung und Zugriffsprotokolle", "Domeinvalidatie en toegangslogboeken", "Validation du domaine et journaux d’accès", "Convalida del dominio e registri di accesso", "Проверка домена и журналы доступа", "Validación del dominio y registros de acceso", "Alan adı doğrulaması ve erişim kayıtları", "Validação do domínio e registos de acesso", "域名验证和访问日志", "Walidacja domeny i dzienniki dostępu", "Verifikim domeni dhe regjistra aksesi"],
  ["stripeBillingPortal", "Stripe billing portal", "Stripe-Abrechnungsportal", "Stripe-facturatieportaal", "Portail de facturation Stripe", "Portale di fatturazione Stripe", "Платёжный портал Stripe", "Portal de facturación de Stripe", "Stripe faturalandırma portalı", "Portal de faturação Stripe", "Stripe 账单门户", "Portal rozliczeniowy Stripe", "Portali i faturimit Stripe"],
  ["cancelAnytime", "Cancel anytime", "Jederzeit kündbar", "Altijd opzegbaar", "Résiliable à tout moment", "Annullabile in qualsiasi momento", "Отмена в любое время", "Cancele cuando quiera", "İstediğiniz zaman iptal edin", "Cancele a qualquer momento", "可随时取消", "Anuluj w dowolnym momencie", "Anulojeni kur të dëshironi"],
  ["softwareTerms", "B2B hosted software subscription. By continuing, you accept the MG AutoTech terms and privacy policy.", "Gehostetes B2B-Software-Abonnement. Mit dem Fortfahren akzeptieren Sie die Geschäftsbedingungen und Datenschutzerklärung von MG AutoTech.", "Gehost B2B-softwareabonnement. Door verder te gaan accepteert u de voorwaarden en het privacybeleid van MG AutoTech.", "Abonnement à un logiciel B2B hébergé. En continuant, vous acceptez les conditions et la politique de confidentialité de MG AutoTech.", "Abbonamento a software B2B ospitato. Continuando accetti i termini e l’informativa sulla privacy di MG AutoTech.", "Подписка на размещённое B2B-программное обеспечение. Продолжая, вы принимаете условия и политику конфиденциальности MG AutoTech.", "Suscripción a software B2B alojado. Al continuar, acepta los términos y la política de privacidad de MG AutoTech.", "Barındırılan B2B yazılım aboneliği. Devam ederek MG AutoTech hüküm ve koşullarını ve gizlilik politikasını kabul edersiniz.", "Subscrição de software B2B alojado. Ao continuar, aceita os termos e a política de privacidade da MG AutoTech.", "B2B 托管软件订阅。继续即表示您接受 MG AutoTech 的条款和隐私政策。", "Subskrypcja hostowanego oprogramowania B2B. Kontynuując, akceptujesz warunki i politykę prywatności MG AutoTech.", "Abonim për softuer B2B të hostuar. Duke vazhduar, pranoni kushtet dhe politikën e privatësisë së MG AutoTech."],
  ["terms", "Terms", "Bedingungen", "Voorwaarden", "Conditions", "Termini", "Условия", "Términos", "Koşullar", "Termos", "条款", "Warunki", "Kushtet"],
  ["privacy", "Privacy", "Datenschutz", "Privacy", "Confidentialité", "Privacy", "Конфиденциальность", "Privacidad", "Gizlilik", "Privacidade", "隐私", "Prywatność", "Privatësia"],
  ["vehicleSelectorFooter", "MG AutoTech Vehicle Selector Widget", "MG AutoTech Fahrzeugauswahl-Widget", "MG AutoTech voertuigselector-widget", "Widget de sélection de véhicules MG AutoTech", "Widget selettore veicoli MG AutoTech", "Виджет подбора автомобилей MG AutoTech", "Widget selector de vehículos MG AutoTech", "MG AutoTech araç seçici widget'ı", "Widget seletor de veículos MG AutoTech", "MG AutoTech 车辆选择器小组件", "Widżet wyboru pojazdów MG AutoTech", "Widget-i MG AutoTech për përzgjedhjen e automjeteve"],
  ["workspaceSyncFailed", "Widget workspace could not be synced. Please try again.", "Der Widget-Arbeitsbereich konnte nicht synchronisiert werden. Bitte versuchen Sie es erneut.", "De widgetomgeving kon niet worden gesynchroniseerd. Probeer het opnieuw.", "L’espace de travail du widget n’a pas pu être synchronisé. Veuillez réessayer.", "Non è stato possibile sincronizzare l’area di lavoro del widget. Riprova.", "Не удалось синхронизировать рабочую область виджета. Повторите попытку.", "No se pudo sincronizar el espacio de trabajo del widget. Inténtelo de nuevo.", "Widget çalışma alanı eşitlenemedi. Lütfen tekrar deneyin.", "Não foi possível sincronizar a área de trabalho do widget. Tente novamente.", "无法同步小组件工作区，请重试。", "Nie udało się zsynchronizować obszaru widżetu. Spróbuj ponownie.", "Hapësira e widget-it nuk mund të sinkronizohej. Provoni përsëri."],
  ["billingSummaryLoadFailed", "Billing summary could not be loaded.", "Die Abrechnungsübersicht konnte nicht geladen werden.", "Het facturatieoverzicht kon niet worden geladen.", "Le récapitulatif de facturation n’a pas pu être chargé.", "Non è stato possibile caricare il riepilogo di fatturazione.", "Не удалось загрузить сводку по оплате.", "No se pudo cargar el resumen de facturación.", "Faturalandırma özeti yüklenemedi.", "Não foi possível carregar o resumo de faturação.", "无法加载账单摘要。", "Nie udało się wczytać podsumowania rozliczeń.", "Përmbledhja e faturimit nuk mund të ngarkohej."],
  ["billingSummaryRefreshFailed", "Billing summary could not be refreshed. The widget settings are still available.", "Die Abrechnungsübersicht konnte nicht aktualisiert werden. Die Widget-Einstellungen sind weiterhin verfügbar.", "Het facturatieoverzicht kon niet worden vernieuwd. De widgetinstellingen blijven beschikbaar.", "Le récapitulatif de facturation n’a pas pu être actualisé. Les paramètres du widget restent disponibles.", "Non è stato possibile aggiornare il riepilogo di fatturazione. Le impostazioni del widget restano disponibili.", "Не удалось обновить сводку по оплате. Настройки виджета по-прежнему доступны.", "No se pudo actualizar el resumen de facturación. Los ajustes del widget siguen disponibles.", "Faturalandırma özeti yenilenemedi. Widget ayarları hâlâ kullanılabilir.", "Não foi possível atualizar o resumo de faturação. As definições do widget continuam disponíveis.", "无法刷新账单摘要，但小组件设置仍可使用。", "Nie udało się odświeżyć podsumowania rozliczeń. Ustawienia widżetu są nadal dostępne.", "Përmbledhja e faturimit nuk mund të rifreskohej. Cilësimet e widget-it janë ende të disponueshme."],
  ["emailRequired", "Enter an enquiry email address before enabling email enquiries.", "Geben Sie eine E-Mail-Adresse für Anfragen ein, bevor Sie E-Mail-Anfragen aktivieren.", "Voer een e-mailadres voor aanvragen in voordat u e-mailaanvragen inschakelt.", "Saisissez une adresse e-mail de contact avant d’activer les demandes par e-mail.", "Inserisci un indirizzo e-mail per le richieste prima di attivare le richieste via e-mail.", "Укажите адрес электронной почты для заявок перед включением заявок по электронной почте.", "Introduzca un correo para consultas antes de activar las consultas por correo.", "E-posta taleplerini açmadan önce bir talep e-posta adresi girin.", "Introduza um endereço de e-mail para pedidos antes de ativar os pedidos por e-mail.", "启用邮件询价前，请输入询价邮箱。", "Przed włączeniem zapytań e-mail podaj adres do obsługi zapytań.", "Vendosni një adresë emaili për kërkesat para se të aktivizoni kërkesat me email."],
  ["whatsappRequired", "Enter a WhatsApp number before enabling WhatsApp enquiries.", "Geben Sie eine WhatsApp-Nummer ein, bevor Sie WhatsApp-Anfragen aktivieren.", "Voer een WhatsApp-nummer in voordat u WhatsApp-aanvragen inschakelt.", "Saisissez un numéro WhatsApp avant d’activer les demandes via WhatsApp.", "Inserisci un numero WhatsApp prima di attivare le richieste via WhatsApp.", "Укажите номер WhatsApp перед включением заявок через WhatsApp.", "Introduzca un número de WhatsApp antes de activar las consultas por WhatsApp.", "WhatsApp taleplerini açmadan önce bir WhatsApp numarası girin.", "Introduza um número de WhatsApp antes de ativar os pedidos por WhatsApp.", "启用 WhatsApp 询价前，请输入 WhatsApp 号码。", "Przed włączeniem zapytań przez WhatsApp podaj numer WhatsApp.", "Vendosni një numër WhatsApp para se të aktivizoni kërkesat me WhatsApp."],
  ["settingsSaveFailed", "Settings could not be saved.", "Die Einstellungen konnten nicht gespeichert werden.", "De instellingen konden niet worden opgeslagen.", "Les paramètres n’ont pas pu être enregistrés.", "Non è stato possibile salvare le impostazioni.", "Не удалось сохранить настройки.", "No se pudieron guardar los ajustes.", "Ayarlar kaydedilemedi.", "Não foi possível guardar as definições.", "无法保存设置。", "Nie udało się zapisać ustawień.", "Cilësimet nuk mund të ruheshin."],
  ["settingsSaved", "Widget settings saved.", "Widget-Einstellungen gespeichert.", "Widgetinstellingen opgeslagen.", "Paramètres du widget enregistrés.", "Impostazioni del widget salvate.", "Настройки виджета сохранены.", "Ajustes del widget guardados.", "Widget ayarları kaydedildi.", "Definições do widget guardadas.", "小组件设置已保存。", "Ustawienia widżetu zapisane.", "Cilësimet e widget-it u ruajtën."],
  ["billingProfileMissing", "No Stripe billing profile is linked to this widget yet. Start a widget subscription or contact MG AutoTech support.", "Mit diesem Widget ist noch kein Stripe-Abrechnungsprofil verknüpft. Starten Sie ein Widget-Abonnement oder kontaktieren Sie den MG AutoTech Support.", "Er is nog geen Stripe-facturatieprofiel aan deze widget gekoppeld. Start een widgetabonnement of neem contact op met MG AutoTech-support.", "Aucun profil de facturation Stripe n’est encore associé à ce widget. Souscrivez au widget ou contactez l’assistance MG AutoTech.", "A questo widget non è ancora collegato alcun profilo di fatturazione Stripe. Avvia un abbonamento o contatta l’assistenza MG AutoTech.", "К этому виджету ещё не привязан платёжный профиль Stripe. Оформите подписку на виджет или обратитесь в поддержку MG AutoTech.", "Todavía no hay ningún perfil de facturación de Stripe vinculado a este widget. Inicie una suscripción o contacte con el soporte de MG AutoTech.", "Bu widget'a henüz bir Stripe faturalandırma profili bağlı değil. Bir widget aboneliği başlatın veya MG AutoTech desteğiyle iletişime geçin.", "Ainda não existe um perfil de faturação Stripe associado a este widget. Inicie uma subscrição ou contacte o suporte da MG AutoTech.", "此小组件尚未关联 Stripe 账单资料。请开始订阅或联系 MG AutoTech 支持。", "Do tego widżetu nie jest jeszcze przypisany profil rozliczeniowy Stripe. Rozpocznij subskrypcję lub skontaktuj się z pomocą MG AutoTech.", "Ende nuk ka profil faturimi Stripe të lidhur me këtë widget. Filloni një abonim ose kontaktoni mbështetjen e MG AutoTech."],
  ["billingPortalFailed", "Billing portal could not be opened. If this widget was created manually, contact MG AutoTech support.", "Das Abrechnungsportal konnte nicht geöffnet werden. Falls dieses Widget manuell erstellt wurde, kontaktieren Sie den MG AutoTech Support.", "Het facturatieportaal kon niet worden geopend. Neem contact op met MG AutoTech-support als deze widget handmatig is aangemaakt.", "Le portail de facturation n’a pas pu être ouvert. Si ce widget a été créé manuellement, contactez l’assistance MG AutoTech.", "Non è stato possibile aprire il portale di fatturazione. Se il widget è stato creato manualmente, contatta l’assistenza MG AutoTech.", "Не удалось открыть платёжный портал. Если виджет создан вручную, обратитесь в поддержку MG AutoTech.", "No se pudo abrir el portal de facturación. Si este widget se creó manualmente, contacte con el soporte de MG AutoTech.", "Faturalandırma portalı açılamadı. Bu widget manuel oluşturulduysa MG AutoTech desteğiyle iletişime geçin.", "Não foi possível abrir o portal de faturação. Se este widget foi criado manualmente, contacte o suporte da MG AutoTech.", "无法打开账单门户。如果此小组件是手动创建的，请联系 MG AutoTech 支持。", "Nie udało się otworzyć portalu rozliczeniowego. Jeśli widżet utworzono ręcznie, skontaktuj się z pomocą MG AutoTech.", "Portali i faturimit nuk mund të hapej. Nëse widget-i u krijua manualisht, kontaktoni mbështetjen e MG AutoTech."],
  ["domainRequestAlreadyPending", "Your domain change request is already waiting for admin review.", "Ihre Anfrage zum Domainwechsel wartet bereits auf die Prüfung durch einen Administrator.", "Uw verzoek om het domein te wijzigen wacht al op beoordeling door een beheerder.", "Votre demande de changement de domaine est déjà en attente de validation par un administrateur.", "La richiesta di modifica del dominio è già in attesa di revisione da parte dell’amministratore.", "Ваш запрос на смену домена уже ожидает проверки администратором.", "Su solicitud de cambio de dominio ya está pendiente de revisión por un administrador.", "Alan adı değişikliği talebiniz zaten yönetici incelemesini bekliyor.", "O seu pedido de alteração de domínio já aguarda revisão por um administrador.", "您的域名变更请求已在等待管理员审核。", "Twoja prośba o zmianę domeny oczekuje już na weryfikację administratora.", "Kërkesa juaj për ndryshimin e domenit po pret tashmë shqyrtimin e administratorit."],
  ["requestFailed", "Request could not be sent.", "Die Anfrage konnte nicht gesendet werden.", "Het verzoek kon niet worden verzonden.", "La demande n’a pas pu être envoyée.", "Non è stato possibile inviare la richiesta.", "Не удалось отправить запрос.", "No se pudo enviar la solicitud.", "Talep gönderilemedi.", "Não foi possível enviar o pedido.", "无法发送请求。", "Nie udało się wysłać prośby.", "Kërkesa nuk mund të dërgohej."],
  ["domainRequestSent", "Domain change request sent for admin review.", "Die Anfrage zum Domainwechsel wurde zur Prüfung an einen Administrator gesendet.", "Het verzoek om het domein te wijzigen is ter beoordeling naar een beheerder gestuurd.", "La demande de changement de domaine a été envoyée pour validation par un administrateur.", "La richiesta di modifica del dominio è stata inviata per la revisione dell’amministratore.", "Запрос на смену домена отправлен администратору на проверку.", "La solicitud de cambio de dominio se ha enviado para revisión por un administrador.", "Alan adı değişikliği talebi yönetici incelemesine gönderildi.", "O pedido de alteração de domínio foi enviado para revisão por um administrador.", "域名变更请求已提交管理员审核。", "Prośba o zmianę domeny została wysłana do weryfikacji administratora.", "Kërkesa për ndryshimin e domenit iu dërgua administratorit për shqyrtim."],
  ["loadingWorkspace", "Loading widget workspace...", "Widget-Arbeitsbereich wird geladen...", "Widgetomgeving laden...", "Chargement de l’espace de travail du widget...", "Caricamento dell’area di lavoro del widget...", "Загрузка рабочей области виджета...", "Cargando el espacio de trabajo del widget...", "Widget çalışma alanı yükleniyor...", "A carregar a área de trabalho do widget...", "正在加载小组件工作区…", "Wczytywanie obszaru widżetu...", "Po ngarkohet hapësira e widget-it..."],
  ["workspaceSyncFailedTitle", "Widget workspace sync failed", "Synchronisierung des Widget-Arbeitsbereichs fehlgeschlagen", "Synchronisatie van de widgetomgeving mislukt", "Échec de la synchronisation de l’espace de travail du widget", "Sincronizzazione dell’area di lavoro del widget non riuscita", "Сбой синхронизации рабочей области виджета", "Error al sincronizar el espacio de trabajo del widget", "Widget çalışma alanı eşitlemesi başarısız oldu", "Falha ao sincronizar a área de trabalho do widget", "小组件工作区同步失败", "Synchronizacja obszaru widżetu nie powiodła się", "Sinkronizimi i hapësirës së widget-it dështoi"],
  ["subscriptionStatusUnchanged", "Your widget subscription status has not changed.", "Der Status Ihres Widget-Abonnements wurde nicht geändert.", "De status van uw widgetabonnement is niet gewijzigd.", "L’état de votre abonnement au widget n’a pas changé.", "Lo stato dell’abbonamento al widget non è cambiato.", "Статус подписки на виджет не изменился.", "El estado de su suscripción al widget no ha cambiado.", "Widget aboneliğinizin durumu değişmedi.", "O estado da subscrição do widget não foi alterado.", "您的小组件订阅状态未发生变化。", "Status subskrypcji widżetu nie uległ zmianie.", "Statusi i abonimit të widget-it nuk ka ndryshuar."],
  ["tryAgain", "Try again", "Erneut versuchen", "Opnieuw proberen", "Réessayer", "Riprova", "Повторить", "Intentar de nuevo", "Tekrar deneyin", "Tentar novamente", "重试", "Spróbuj ponownie", "Provo përsëri"],
  ["dashboard", "Dashboard", "Übersicht", "Dashboard", "Tableau de bord", "Dashboard", "Панель управления", "Panel", "Panel", "Painel", "控制面板", "Panel", "Paneli"],
  ["noWidgetSubscription", "No widget subscription is linked to this account.", "Mit diesem Konto ist kein Widget-Abonnement verknüpft.", "Er is geen widgetabonnement aan dit account gekoppeld.", "Aucun abonnement au widget n’est associé à ce compte.", "Nessun abbonamento al widget è collegato a questo account.", "К этой учётной записи не привязана подписка на виджет.", "No hay ninguna suscripción al widget vinculada a esta cuenta.", "Bu hesaba bağlı bir widget aboneliği yok.", "Não existe uma subscrição do widget associada a esta conta.", "此账户未关联小组件订阅。", "Z tym kontem nie jest powiązana subskrypcja widżetu.", "Nuk ka abonim widget-i të lidhur me këtë llogari."],
  ["viewPlans", "View plans", "Tarife ansehen", "Abonnementen bekijken", "Voir les offres", "Vedi i piani", "Посмотреть тарифы", "Ver planes", "Paketleri görüntüle", "Ver planos", "查看套餐", "Zobacz plany", "Shiko paketat"],
  ["vehicleSelectorWidget", "Vehicle Selector Widget", "Fahrzeugauswahl-Widget", "Voertuigselector-widget", "Widget de sélection de véhicules", "Widget selettore veicoli", "Виджет подбора автомобилей", "Widget selector de vehículos", "Araç seçici widget", "Widget seletor de veículos", "车辆选择器小组件", "Widżet wyboru pojazdów", "Widget për përzgjedhjen e automjeteve"],
  ["widgetCodeGenerator", "Vehicle Lookup Code Generator", "Fahrzeugauswahl-Codegenerator", "Codegenerator voor de voertuigselector", "Générateur de code du sélecteur de véhicules", "Generatore di codice del selettore veicoli", "Генератор кода подбора автомобиля", "Generador de código del selector de vehículos", "Araç seçici kod oluşturucu", "Gerador de código do seletor de veículos", "车辆查询代码生成器", "Generator kodu selektora pojazdów", "Gjeneruesi i kodit për përzgjedhjen e automjeteve"],
  ["lastSettingsShown", "Your last loaded widget settings are still shown.", "Ihre zuletzt geladenen Widget-Einstellungen werden weiterhin angezeigt.", "De laatst geladen widgetinstellingen worden nog steeds weergegeven.", "Les derniers paramètres du widget chargés restent affichés.", "Le ultime impostazioni del widget caricate sono ancora visualizzate.", "Последние загруженные настройки виджета по-прежнему отображаются.", "Se siguen mostrando los últimos ajustes cargados del widget.", "Son yüklenen widget ayarlarınız gösterilmeye devam ediyor.", "As últimas definições carregadas do widget continuam visíveis.", "仍显示上次加载的小组件设置。", "Nadal wyświetlane są ostatnio wczytane ustawienia widżetu.", "Cilësimet e fundit të ngarkuara të widget-it po shfaqen ende."],
  ["retrySync", "Retry sync", "Synchronisierung wiederholen", "Opnieuw synchroniseren", "Relancer la synchronisation", "Riprova la sincronizzazione", "Повторить синхронизацию", "Reintentar sincronización", "Eşitlemeyi yeniden dene", "Repetir sincronização", "重新同步", "Ponów synchronizację", "Riprovo sinkronizimin"],
  ["installationReadiness", "Installation readiness", "Installationsbereitschaft", "Installatiegereedheid", "État de préparation de l’installation", "Stato di preparazione dell’installazione", "Готовность к установке", "Preparación de la instalación", "Kurulum hazırlığı", "Preparação da instalação", "安装准备情况", "Gotowość instalacji", "Gatishmëria e instalimit"],
  ["stepsComplete", "{done} of {total} steps complete", "{done} von {total} Schritten abgeschlossen", "{done} van {total} stappen voltooid", "{done} étapes sur {total} terminées", "{done} passaggi su {total} completati", "Выполнено шагов: {done} из {total}", "{done} de {total} pasos completados", "{total} adımdan {done} tanesi tamamlandı", "{done} de {total} passos concluídos", "已完成 {done}/{total} 个步骤", "Ukończono {done} z {total} kroków", "{done} nga {total} hapa të përfunduar"],
  ["ready", "Ready", "Bereit", "Gereed", "Prêt", "Pronto", "Готово", "Listo", "Hazır", "Pronto", "就绪", "Gotowe", "Gati"],
  ["setup", "Setup", "Einrichtung", "Instellen", "Configuration", "Configurazione", "Настройка", "Configuración", "Kurulum", "Configuração", "设置", "Konfiguracja", "Konfigurimi"],
  ["subscription", "Subscription", "Abonnement", "Abonnement", "Abonnement", "Abbonamento", "Подписка", "Suscripción", "Abonelik", "Subscrição", "订阅", "Subskrypcja", "Abonimi"],
  ["approvedDomain", "Approved domain", "Bestätigte Domain", "Goedgekeurd domein", "Domaine approuvé", "Dominio approvato", "Одобренный домен", "Dominio aprobado", "Onaylı alan adı", "Domínio aprovado", "已批准域名", "Zatwierdzona domena", "Domeni i miratuar"],
  ["installationKey", "Installation key", "Installationsschlüssel", "Installatiesleutel", "Clé d’installation", "Chiave di installazione", "Ключ установки", "Clave de instalación", "Kurulum anahtarı", "Chave de instalação", "安装密钥", "Klucz instalacyjny", "Çelësi i instalimit"],
  ["leadChannel", "Lead channel", "Anfragekanal", "Leadkanaal", "Canal de contact", "Canale dei contatti", "Канал заявок", "Canal de contactos", "Talep kanalı", "Canal de contactos", "线索渠道", "Kanał zapytań", "Kanali i kërkesave"],
  ["loadsThisMonth", "Loads this month", "Aufrufe in diesem Monat", "Laadbeurten deze maand", "Chargements ce mois-ci", "Caricamenti questo mese", "Загрузки в этом месяце", "Cargas este mes", "Bu ayki yüklemeler", "Carregamentos este mês", "本月加载次数", "Wczytania w tym miesiącu", "Ngarkime këtë muaj"],
  ["lastLiveLoad", "Last live load: {value}", "Letzter Live-Aufruf: {value}", "Laatst live geladen: {value}", "Dernier chargement en direct : {value}", "Ultimo caricamento live: {value}", "Последняя рабочая загрузка: {value}", "Última carga en directo: {value}", "Son canlı yükleme: {value}", "Último carregamento em produção: {value}", "上次正式环境加载：{value}", "Ostatnie wczytanie produkcyjne: {value}", "Ngarkimi i fundit aktiv: {value}"],
  ["notDetected", "not detected yet", "noch nicht erkannt", "nog niet gedetecteerd", "pas encore détecté", "non ancora rilevato", "пока не обнаружено", "aún no detectado", "henüz algılanmadı", "ainda não detetado", "尚未检测到", "jeszcze nie wykryto", "nuk është zbuluar ende"],
  ["leadsThisMonth", "Leads this month", "Anfragen in diesem Monat", "Leads deze maand", "Prospects ce mois-ci", "Contatti questo mese", "Заявки в этом месяце", "Contactos este mes", "Bu ayki talepler", "Contactos este mês", "本月线索", "Zapytania w tym miesiącu", "Kërkesa këtë muaj"],
  ["deliveryFailures", "{count} delivery failures", "{count} Zustellfehler", "{count} afleverfouten", "{count} échecs d’envoi", "{count} errori di consegna", "Ошибок доставки: {count}", "{count} errores de entrega", "{count} teslimat hatası", "{count} falhas de entrega", "{count} 次发送失败", "Błędy dostarczenia: {count}", "{count} dështime në dërgim"],
  ["configurePublish", "Configure, preview and publish.", "Konfigurieren, prüfen und veröffentlichen.", "Configureren, bekijken en publiceren.", "Configurez, prévisualisez et publiez.", "Configura, visualizza in anteprima e pubblica.", "Настройте, проверьте и опубликуйте.", "Configure, previsualice y publique.", "Yapılandırın, önizleyin ve yayınlayın.", "Configure, pré-visualize e publique.", "配置、预览并发布。", "Skonfiguruj, sprawdź i opublikuj.", "Konfiguroni, paraafishoni dhe publikoni."],
  ["planStatusLoads", "Plan: {plan} · Status: {status} · {limit} loads/month", "Tarif: {plan} · Status: {status} · {limit} Aufrufe/Monat", "Plan: {plan} · Status: {status} · {limit} laadbeurten/maand", "Offre : {plan} · État : {status} · {limit} chargements/mois", "Piano: {plan} · Stato: {status} · {limit} caricamenti/mese", "Тариф: {plan} · Статус: {status} · {limit} загрузок/месяц", "Plan: {plan} · Estado: {status} · {limit} cargas/mes", "Plan: {plan} · Durum: {status} · Aylık {limit} yükleme", "Plano: {plan} · Estado: {status} · {limit} carregamentos/mês", "套餐：{plan} · 状态：{status} · 每月 {limit} 次加载", "Plan: {plan} · Status: {status} · {limit} wczytań/miesiąc", "Paketa: {plan} · Statusi: {status} · {limit} ngarkime/muaj"],
  ["saveSettings", "Save settings", "Einstellungen speichern", "Instellingen opslaan", "Enregistrer les paramètres", "Salva impostazioni", "Сохранить настройки", "Guardar ajustes", "Ayarları kaydet", "Guardar definições", "保存设置", "Zapisz ustawienia", "Ruaj cilësimet"],
  ["widgetSettings", "Widget settings", "Widget-Einstellungen", "Widgetinstellingen", "Paramètres du widget", "Impostazioni del widget", "Настройки виджета", "Ajustes del widget", "Widget ayarları", "Definições do widget", "小组件设置", "Ustawienia widżetu", "Cilësimet e widget-it"],
  ["themeMode", "Theme mode", "Darstellung", "Themamodus", "Mode d’affichage", "Modalità tema", "Режим темы", "Modo de tema", "Tema modu", "Modo do tema", "主题模式", "Tryb motywu", "Mënyra e temës"],
  ["widgetTitle", "Widget title", "Widget-Titel", "Widgettitel", "Titre du widget", "Titolo del widget", "Заголовок виджета", "Título del widget", "Widget başlığı", "Título do widget", "小组件标题", "Tytuł widżetu", "Titulli i widget-it"],
  ["buttonText", "Button text", "Button-Text", "Knoptekst", "Texte du bouton", "Testo del pulsante", "Текст кнопки", "Texto del botón", "Düğme metni", "Texto do botão", "按钮文字", "Tekst przycisku", "Teksti i butonit"],
  ["buttonTextColour", "Button text colour", "Button-Textfarbe", "Tekstkleur van de knop", "Couleur du texte du bouton", "Colore del testo del pulsante", "Цвет текста кнопки", "Color del texto del botón", "Düğme metni rengi", "Cor do texto do botão", "按钮文字颜色", "Kolor tekstu przycisku", "Ngjyra e tekstit të butonit"],
  ["highlightColour", "Highlight colour", "Akzentfarbe", "Accentkleur", "Couleur d’accent", "Colore di evidenziazione", "Цвет выделения", "Color de realce", "Vurgu rengi", "Cor de destaque", "高亮颜色", "Kolor wyróżnienia", "Ngjyra e theksimit"],
  ["otherSettings", "Other settings", "Weitere Einstellungen", "Overige instellingen", "Autres paramètres", "Altre impostazioni", "Другие настройки", "Otros ajustes", "Diğer ayarlar", "Outras definições", "其他设置", "Pozostałe ustawienia", "Cilësime të tjera"],
  ["enabledLanguages", "Enabled languages", "Aktivierte Sprachen", "Ingeschakelde talen", "Langues activées", "Lingue abilitate", "Включённые языки", "Idiomas habilitados", "Etkin diller", "Idiomas ativos", "已启用语言", "Aktywne języki", "Gjuhët e aktivizuara"],
  ["showBranding", "Show MG AutoTech branding", "MG AutoTech Branding anzeigen", "MG AutoTech-branding tonen", "Afficher la marque MG AutoTech", "Mostra il marchio MG AutoTech", "Показывать бренд MG AutoTech", "Mostrar la marca MG AutoTech", "MG AutoTech markasını göster", "Mostrar a marca MG AutoTech", "显示 MG AutoTech 品牌", "Pokaż oznaczenie MG AutoTech", "Shfaq markën MG AutoTech"],
  ["brandingIncluded", "MG AutoTech branding is included in this plan.", "Das MG AutoTech Branding ist in diesem Tarif enthalten.", "MG AutoTech-branding is inbegrepen bij dit abonnement.", "La marque MG AutoTech est incluse dans cette offre.", "Il marchio MG AutoTech è incluso in questo piano.", "Бренд MG AutoTech включён в этот тариф.", "La marca MG AutoTech está incluida en este plan.", "MG AutoTech markası bu plana dahildir.", "A marca MG AutoTech está incluída neste plano.", "此套餐包含 MG AutoTech 品牌标识。", "Oznaczenie MG AutoTech jest zawarte w tym planie.", "Marka MG AutoTech përfshihet në këtë paketë."],
  ["contactChannels", "Contact channels", "Kontaktkanäle", "Contactkanalen", "Canaux de contact", "Canali di contatto", "Каналы связи", "Canales de contacto", "İletişim kanalları", "Canais de contacto", "联系渠道", "Kanały kontaktu", "Kanalet e kontaktit"],
  ["contactDescription", "Choose how visitors can contact your business from the widget.", "Legen Sie fest, wie Besucher Ihr Unternehmen über das Widget kontaktieren können.", "Kies hoe bezoekers via de widget contact kunnen opnemen met uw bedrijf.", "Choisissez comment les visiteurs peuvent contacter votre entreprise depuis le widget.", "Scegli come i visitatori possono contattare la tua attività dal widget.", "Выберите, как посетители смогут связаться с вашей компанией через виджет.", "Elija cómo pueden contactar los visitantes con su empresa desde el widget.", "Ziyaretçilerin widget üzerinden işletmenizle nasıl iletişime geçeceğini seçin.", "Escolha como os visitantes podem contactar a sua empresa através do widget.", "选择访客通过小组件联系您企业的方式。", "Wybierz, w jaki sposób odwiedzający mogą kontaktować się z firmą przez widżet.", "Zgjidhni si mund ta kontaktojnë vizitorët biznesin tuaj nga widget-i."],
  ["enableEmail", "Email enquiry form", "Anfrageformular per E-Mail", "Aanvraagformulier per e-mail", "Formulaire de demande par e-mail", "Modulo di richiesta via e-mail", "Форма заявки по электронной почте", "Formulario de consulta por correo", "E-posta talep formu", "Formulário de pedido por e-mail", "邮件询价表单", "Formularz zapytania e-mail", "Formular kërkese me email"],
  ["enableWhatsapp", "WhatsApp enquiries", "WhatsApp-Anfragen", "Aanvragen via WhatsApp", "Demandes via WhatsApp", "Richieste via WhatsApp", "Заявки через WhatsApp", "Consultas por WhatsApp", "WhatsApp talepleri", "Pedidos por WhatsApp", "WhatsApp 询价", "Zapytania przez WhatsApp", "Kërkesa me WhatsApp"],
  ["enquiryEmail", "Email address for enquiries", "E-Mail-Adresse für Anfragen", "E-mailadres voor aanvragen", "Adresse e-mail pour les demandes", "Indirizzo e-mail per le richieste", "Электронная почта для заявок", "Correo para consultas", "Talepler için e-posta adresi", "Endereço de e-mail para pedidos", "询价邮箱", "Adres e-mail do zapytań", "Adresa e emailit për kërkesa"],
  ["whatsappNumber", "WhatsApp number", "WhatsApp-Nummer", "WhatsApp-nummer", "Numéro WhatsApp", "Numero WhatsApp", "Номер WhatsApp", "Número de WhatsApp", "WhatsApp numarası", "Número de WhatsApp", "WhatsApp 号码", "Numer WhatsApp", "Numri WhatsApp"],
  ["offerButtonHidden", "The offer button is hidden while both contact channels are disabled.", "Der Angebotsbutton bleibt ausgeblendet, solange beide Kontaktkanäle deaktiviert sind.", "De offerteknop is verborgen zolang beide contactkanalen zijn uitgeschakeld.", "Le bouton de demande d’offre reste masqué tant que les deux canaux de contact sont désactivés.", "Il pulsante per richiedere un’offerta resta nascosto finché entrambi i canali di contatto sono disattivati.", "Кнопка запроса предложения скрыта, пока оба канала связи отключены.", "El botón de solicitud de oferta permanece oculto mientras ambos canales de contacto estén desactivados.", "Her iki iletişim kanalı da kapalıyken teklif düğmesi gizlenir.", "O botão de pedido de proposta fica oculto enquanto ambos os canais de contacto estiverem desativados.", "两个联系渠道均关闭时，询价按钮将隐藏。", "Przycisk zapytania ofertowego jest ukryty, gdy oba kanały kontaktu są wyłączone.", "Butoni i ofertës fshihet kur të dy kanalet e kontaktit janë çaktivizuar."],
  ["domainChangeRequest", "Request domain change", "Domainwechsel beantragen", "Domeinwijziging aanvragen", "Demander un changement de domaine", "Richiedi modifica del dominio", "Запросить смену домена", "Solicitar cambio de dominio", "Alan adı değişikliği iste", "Pedir alteração de domínio", "申请更改域名", "Poproś o zmianę domeny", "Kërko ndryshim domeni"],
  ["domainChangeDescription", "The active domain cannot be changed directly. Send a request for admin approval.", "Die aktive Domain kann nicht direkt geändert werden. Senden Sie eine Anfrage zur Freigabe durch einen Administrator.", "Het actieve domein kan niet rechtstreeks worden gewijzigd. Stuur een verzoek ter goedkeuring door een beheerder.", "Le domaine actif ne peut pas être modifié directement. Envoyez une demande pour validation par un administrateur.", "Il dominio attivo non può essere modificato direttamente. Invia una richiesta per l’approvazione dell’amministratore.", "Активный домен нельзя изменить напрямую. Отправьте запрос на одобрение администратору.", "El dominio activo no se puede cambiar directamente. Envíe una solicitud para que la apruebe un administrador.", "Etkin alan adı doğrudan değiştirilemez. Yönetici onayı için talep gönderin.", "O domínio ativo não pode ser alterado diretamente. Envie um pedido para aprovação por um administrador.", "无法直接更改当前域名。请提交请求，等待管理员批准。", "Aktywnej domeny nie można zmienić bezpośrednio. Wyślij prośbę do zatwierdzenia przez administratora.", "Domeni aktiv nuk mund të ndryshohet drejtpërdrejt. Dërgoni një kërkesë për miratim nga administratori."],
  ["pendingAdminReview", "Pending admin review", "Prüfung durch Administrator ausstehend", "Wacht op beoordeling door beheerder", "Validation par un administrateur en attente", "In attesa di revisione dell’amministratore", "Ожидает проверки администратором", "Pendiente de revisión por administrador", "Yönetici incelemesi bekleniyor", "A aguardar revisão por um administrador", "等待管理员审核", "Oczekuje na weryfikację administratora", "Në pritje të shqyrtimit nga administratori"],
  ["newRequestAfterResolution", "A new request can be sent after this one is approved or rejected.", "Nach Annahme oder Ablehnung dieser Anfrage kann eine neue gesendet werden.", "Nadat dit verzoek is goedgekeurd of afgewezen, kunt u een nieuw verzoek sturen.", "Une nouvelle demande pourra être envoyée après l’approbation ou le refus de celle-ci.", "Dopo l’approvazione o il rifiuto di questa richiesta sarà possibile inviarne una nuova.", "Новый запрос можно отправить после одобрения или отклонения текущего.", "Podrá enviar una nueva solicitud cuando esta se apruebe o rechace.", "Bu talep onaylandıktan veya reddedildikten sonra yeni bir talep gönderebilirsiniz.", "Poderá enviar um novo pedido depois de este ser aprovado ou rejeitado.", "此请求获批或被拒后，才能提交新请求。", "Nową prośbę można wysłać po zatwierdzeniu lub odrzuceniu bieżącej.", "Një kërkesë e re mund të dërgohet pasi kjo të miratohet ose refuzohet."],
  ["send", "Send", "Senden", "Verzenden", "Envoyer", "Invia", "Отправить", "Enviar", "Gönder", "Enviar", "发送", "Wyślij", "Dërgo"],
  ["livePreview", "Live preview", "Live-Vorschau", "Live voorbeeld", "Aperçu en direct", "Anteprima dal vivo", "Предпросмотр в реальном времени", "Vista previa en directo", "Canlı önizleme", "Pré-visualização em direto", "实时预览", "Podgląd na żywo", "Paraafishim drejtpërdrejt"],
  ["live", "Live", "Live", "Live", "En direct", "Live", "В работе", "En directo", "Canlı", "Em direto", "实时", "Na żywo", "Drejtpërdrejt"],
  ["installation", "Installation", "Installation", "Installatie", "Installation", "Installazione", "Установка", "Instalación", "Kurulum", "Instalação", "安装", "Instalacja", "Instalimi"],
  ["embedCode", "Your embed code", "Ihr Einbettungscode", "Uw insluitcode", "Votre code d’intégration", "Il tuo codice di integrazione", "Ваш код встраивания", "Su código de inserción", "Yerleştirme kodunuz", "O seu código de integração", "您的嵌入代码", "Twój kod osadzania", "Kodi juaj i integrimit"],
  ["integrationMethod", "Use one integration method. Script embed is recommended; iframe is the compatibility fallback.", "Verwenden Sie eine Integrationsmethode. Die Skript-Einbettung wird empfohlen; der iFrame dient als Kompatibilitätslösung.", "Gebruik één integratiemethode. Scriptinsluiting wordt aanbevolen; iframe is de compatibiliteitsoplossing.", "Utilisez une seule méthode d’intégration. Le script est recommandé ; l’iframe sert de solution de compatibilité.", "Usa un solo metodo di integrazione. È consigliato lo script; l’iframe è l’alternativa per la compatibilità.", "Используйте один способ интеграции. Рекомендуется встраивание скриптом, а iframe служит вариантом совместимости.", "Use un único método de integración. Se recomienda el script; el iframe es la alternativa de compatibilidad.", "Tek bir entegrasyon yöntemi kullanın. Script yerleştirme önerilir; iframe uyumluluk yedeğidir.", "Utilize um único método de integração. Recomendamos o script; o iframe é a alternativa de compatibilidade.", "请选择一种集成方式。建议使用脚本嵌入；iframe 可作为兼容方案。", "Użyj jednej metody integracji. Zalecane jest osadzanie skryptem, a iframe stanowi opcję zgodności.", "Përdorni një mënyrë integrimi. Rekomandohet integrimi me skript; iframe është alternativa për pajtueshmëri."],
  ["scriptEmbed", "Script embed", "Skript-Einbettung", "Scriptinsluiting", "Intégration par script", "Integrazione tramite script", "Встраивание скриптом", "Inserción mediante script", "Script yerleştirme", "Integração por script", "脚本嵌入", "Osadzanie skryptem", "Integrim me skript"],
  ["iframeFallback", "Iframe fallback", "iFrame-Fallback", "Iframe-terugval", "Solution iframe", "Fallback iframe", "Резервный iframe", "Iframe alternativo", "Iframe yedeği", "Alternativa iframe", "iframe 兼容方案", "Rezerwowy iframe", "Alternativë iframe"],
  ["needSupport", "Do you need support?", "Benötigen Sie Unterstützung?", "Hulp nodig?", "Besoin d’aide ?", "Hai bisogno di assistenza?", "Нужна помощь?", "¿Necesita ayuda?", "Desteğe mi ihtiyacınız var?", "Precisa de ajuda?", "需要帮助吗？", "Potrzebujesz pomocy?", "Keni nevojë për ndihmë?"],
  ["supportText", "We are here to help if you run into any difficulties. If you would like MG AutoTech to help embed this widget into your website, contact us with your website details.", "Wir helfen Ihnen bei allen Schwierigkeiten. Wenn MG AutoTech das Widget in Ihre Website einbinden soll, kontaktieren Sie uns mit den Angaben zu Ihrer Website.", "Wij helpen u graag bij problemen. Wilt u dat MG AutoTech de widget op uw website insluit, neem dan contact op met de gegevens van uw website.", "Nous sommes à votre disposition en cas de difficulté. Si vous souhaitez que MG AutoTech intègre ce widget à votre site, contactez-nous avec les informations de votre site.", "Siamo a disposizione in caso di difficoltà. Se vuoi che MG AutoTech integri il widget nel tuo sito, contattaci con i dati del sito.", "Мы поможем при любых затруднениях. Если вы хотите, чтобы MG AutoTech встроила виджет на ваш сайт, свяжитесь с нами и укажите данные сайта.", "Estamos aquí para ayudarle si tiene alguna dificultad. Si desea que MG AutoTech integre el widget en su web, contacte con nosotros e indique los datos del sitio.", "Bir sorun yaşarsanız yardımcı olmak için buradayız. MG AutoTech'in widget'ı web sitenize yerleştirmesini isterseniz site bilgilerinizle bize ulaşın.", "Estamos disponíveis para ajudar se tiver dificuldades. Se pretender que a MG AutoTech integre o widget no seu site, contacte-nos com os dados do site.", "如遇任何问题，我们随时提供帮助。如果希望 MG AutoTech 协助将此小组件嵌入您的网站，请联系我们并提供网站信息。", "Pomożemy w razie trudności. Jeśli chcesz, aby MG AutoTech osadziło widżet na Twojej stronie, skontaktuj się z nami i podaj dane witryny.", "Jemi këtu për t'ju ndihmuar nëse hasni vështirësi. Nëse dëshironi që MG AutoTech ta integrojë widget-in në faqen tuaj, na kontaktoni me të dhënat e faqes."],
  ["emailSupport", "Email support", "E-Mail-Support", "E-mailondersteuning", "Assistance par e-mail", "Assistenza via e-mail", "Поддержка по электронной почте", "Soporte por correo", "E-posta desteği", "Suporte por e-mail", "邮件支持", "Pomoc e-mail", "Mbështetje me email"],
  ["advanced", "Advanced", "Erweitert", "Geavanceerd", "Avancé", "Avanzato", "Дополнительно", "Avanzado", "Gelişmiş", "Avançado", "高级", "Zaawansowane", "Të avancuara"],
  ["selectedVehicleData", "Get vehicle data once selected", "Fahrzeugdaten nach der Auswahl empfangen", "Ontvang de voertuiggegevens na selectie", "Récupérer les données du véhicule sélectionné", "Ottieni i dati del veicolo dopo la selezione", "Получать данные после выбора автомобиля", "Obtenga los datos del vehículo seleccionado", "Araç seçildiğinde verileri alın", "Obter os dados após selecionar o veículo", "选择车辆后获取其数据", "Pobierz dane po wybraniu pojazdu", "Merrni të dhënat pasi të zgjidhet automjeti"],
  ["advancedDescription", "Use JavaScript to collect the selected vehicle data after a visitor completes the selection. This is useful if you want to pass the vehicle data into your contact form.", "Verwenden Sie JavaScript, um die ausgewählten Fahrzeugdaten nach Abschluss der Auswahl zu übernehmen. So können Sie die Fahrzeugdaten an Ihr Kontaktformular weitergeben.", "Gebruik JavaScript om de geselecteerde voertuiggegevens op te halen zodra een bezoeker de selectie voltooit. Zo kunt u de voertuiggegevens doorgeven aan uw contactformulier.", "Utilisez JavaScript pour récupérer les données du véhicule une fois la sélection terminée. Vous pourrez ainsi les transmettre à votre formulaire de contact.", "Usa JavaScript per acquisire i dati del veicolo al termine della selezione. In questo modo puoi passarli al modulo di contatto.", "Используйте JavaScript, чтобы получить данные выбранного автомобиля после завершения выбора посетителем. Эти данные можно передать в контактную форму.", "Use JavaScript para obtener los datos del vehículo cuando el visitante termine la selección. Así podrá enviarlos a su formulario de contacto.", "Ziyaretçi seçimini tamamladığında seçilen araç verilerini JavaScript ile alın. Böylece araç verilerini iletişim formunuza aktarabilirsiniz.", "Utilize JavaScript para recolher os dados do veículo depois de o visitante concluir a seleção. Assim poderá enviá-los para o formulário de contacto.", "访客完成选择后，可使用 JavaScript 获取所选车辆数据，并将其传递到您的联系表单。", "Użyj JavaScript, aby pobrać dane pojazdu po zakończeniu wyboru przez odwiedzającego. Możesz następnie przekazać je do formularza kontaktowego.", "Përdorni JavaScript për të marrë të dhënat e automjetit pasi vizitori të përfundojë përzgjedhjen. Kështu mund t'i kaloni ato në formularin tuaj të kontaktit."],
  ["javascriptListener", "JavaScript listener", "JavaScript-Listener", "JavaScript-listener", "Écouteur JavaScript", "Listener JavaScript", "Обработчик JavaScript", "Listener de JavaScript", "JavaScript dinleyicisi", "Listener JavaScript", "JavaScript 监听器", "Nasłuchiwanie JavaScript", "Dëgjues JavaScript"],
  ["copy", "Copy", "Kopieren", "Kopiëren", "Copier", "Copia", "Копировать", "Copiar", "Kopyala", "Copiar", "复制", "Kopiuj", "Kopjo"],
  ["copied", "Copied", "Kopiert", "Gekopieerd", "Copié", "Copiato", "Скопировано", "Copiado", "Kopyalandı", "Copiado", "已复制", "Skopiowano", "U kopjua"],
  ["subscriptionInactiveTitle", "Widget subscription inactive", "Widget-Abonnement inaktiv", "Widgetabonnement inactief", "Abonnement au widget inactif", "Abbonamento al widget inattivo", "Подписка на виджет неактивна", "Suscripción al widget inactiva", "Widget aboneliği etkin değil", "Subscrição do widget inativa", "小组件订阅未启用", "Subskrypcja widżetu nieaktywna", "Abonimi i widget-it joaktiv"],
  ["subscriptionInactiveDescription", "Your widget subscription is currently inactive. Please update your subscription to reactivate your widget.", "Ihr Widget-Abonnement ist derzeit inaktiv. Aktualisieren Sie Ihr Abonnement, um das Widget wieder zu aktivieren.", "Uw widgetabonnement is momenteel inactief. Werk uw abonnement bij om de widget opnieuw te activeren.", "Votre abonnement au widget est actuellement inactif. Mettez-le à jour pour réactiver le widget.", "L’abbonamento al widget è attualmente inattivo. Aggiornalo per riattivare il widget.", "Подписка на виджет сейчас неактивна. Обновите подписку, чтобы снова включить виджет.", "La suscripción al widget está inactiva. Actualícela para reactivar el widget.", "Widget aboneliğiniz şu anda etkin değil. Widget'ı yeniden etkinleştirmek için aboneliğinizi güncelleyin.", "A subscrição do widget está inativa. Atualize-a para reativar o widget.", "您的小组件订阅目前未启用。请更新订阅以重新启用小组件。", "Subskrypcja widżetu jest obecnie nieaktywna. Zaktualizuj ją, aby ponownie uruchomić widżet.", "Abonimi i widget-it është aktualisht joaktiv. Përditësojeni abonimin për ta riaktivizuar widget-in."],
  ["manageSubscription", "Manage subscription", "Abonnement verwalten", "Abonnement beheren", "Gérer l’abonnement", "Gestisci abbonamento", "Управление подпиской", "Gestionar suscripción", "Aboneliği yönet", "Gerir subscrição", "管理订阅", "Zarządzaj subskrypcją", "Menaxho abonimin"],
  ["billingOverview", "Billing overview", "Abrechnungsübersicht", "Facturatieoverzicht", "Aperçu de la facturation", "Riepilogo di fatturazione", "Обзор оплаты", "Resumen de facturación", "Faturalandırma özeti", "Resumo de faturação", "账单概览", "Podsumowanie rozliczeń", "Përmbledhja e faturimit"],
  ["billingOverviewDescription", "Track the linked Stripe subscription, latest paid invoice and upcoming renewal from one safe customer view.", "Verfolgen Sie das verknüpfte Stripe-Abonnement, die zuletzt bezahlte Rechnung und die nächste Verlängerung in einer sicheren Kundenansicht.", "Bekijk het gekoppelde Stripe-abonnement, de laatst betaalde factuur en de komende verlenging in één veilige klantweergave.", "Suivez l’abonnement Stripe associé, la dernière facture payée et le prochain renouvellement dans une vue client sécurisée.", "Controlla l’abbonamento Stripe collegato, l’ultima fattura pagata e il prossimo rinnovo da un’unica vista cliente sicura.", "Отслеживайте привязанную подписку Stripe, последний оплаченный счёт и предстоящее продление в безопасном интерфейсе клиента.", "Consulte la suscripción de Stripe vinculada, la última factura pagada y la próxima renovación desde una vista segura para clientes.", "Bağlı Stripe aboneliğini, son ödenen faturayı ve yaklaşan yenilemeyi güvenli tek bir müşteri görünümünden takip edin.", "Acompanhe a subscrição Stripe associada, a última fatura paga e a próxima renovação numa vista segura para o cliente.", "在安全的客户视图中查看关联的 Stripe 订阅、最近支付的账单和下次续订。", "Śledź powiązaną subskrypcję Stripe, ostatnią opłaconą fakturę i nadchodzące odnowienie w jednym bezpiecznym widoku klienta.", "Ndiqni abonimin e lidhur Stripe, faturën e fundit të paguar dhe rinovimin e ardhshëm në një pamje të sigurt për klientin."],
  ["notAvailable", "Not available", "Nicht verfügbar", "Niet beschikbaar", "Indisponible", "Non disponibile", "Недоступно", "No disponible", "Mevcut değil", "Indisponível", "暂无", "Niedostępne", "Nuk disponohet"],
  ["dateNotAvailable", "Date not available", "Datum nicht verfügbar", "Datum niet beschikbaar", "Date indisponible", "Data non disponibile", "Дата недоступна", "Fecha no disponible", "Tarih mevcut değil", "Data indisponível", "日期不可用", "Data niedostępna", "Data nuk disponohet"],
  ["today", "Today", "Heute", "Vandaag", "Aujourd’hui", "Oggi", "Сегодня", "Hoy", "Bugün", "Hoje", "今天", "Dzisiaj", "Sot"],
  ["tomorrow", "Tomorrow", "Morgen", "Morgen", "Demain", "Domani", "Завтра", "Mañana", "Yarın", "Amanhã", "明天", "Jutro", "Nesër"],
  ["inDays", "In {count} days", "In {count} Tagen", "Over {count} dagen", "Dans {count} jours", "Tra {count} giorni", "Через {count} дней", "Dentro de {count} días", "{count} gün sonra", "Daqui a {count} dias", "{count} 天后", "Za {count} dni", "Pas {count} ditësh"],
  ["notLinked", "Not linked", "Nicht verknüpft", "Niet gekoppeld", "Non associé", "Non collegato", "Не привязано", "No vinculado", "Bağlı değil", "Não associado", "未关联", "Niepowiązane", "Nuk është i lidhur"],
  ["widgetSubscription", "Widget Subscription", "Widget-Abonnement", "Widgetabonnement", "Abonnement au widget", "Abbonamento al widget", "Подписка на виджет", "Suscripción al widget", "Widget aboneliği", "Subscrição do widget", "小组件订阅", "Subskrypcja widżetu", "Abonimi i widget-it"],
  ["liveStripe", "Live Stripe", "Live-Stripe", "Live Stripe", "Stripe en direct", "Stripe live", "Stripe в реальном времени", "Stripe en directo", "Canlı Stripe", "Stripe em direto", "Stripe 实时数据", "Stripe na żywo", "Stripe drejtpërdrejt"],
  ["localFallback", "Local fallback", "Lokaler Fallback", "Lokale terugval", "Données locales de secours", "Fallback locale", "Локальные резервные данные", "Datos locales alternativos", "Yerel yedek", "Alternativa local", "本地备用数据", "Lokalne dane zastępcze", "Alternativë lokale"],
  ["unlinked", "Unlinked", "Nicht verknüpft", "Niet gekoppeld", "Non associé", "Non collegato", "Не привязано", "No vinculado", "Bağlı değil", "Não associado", "未关联", "Niepowiązane", "I palidhur"],
  ["plan", "Plan", "Tarif", "Plan", "Offre", "Piano", "Тариф", "Plan", "Plan", "Plano", "套餐", "Plan", "Paketa"],
  ["planWhiteLabel", "White label", "Eigenmarke", "Eigen merk", "Marque blanche", "Marchio bianco", "Под вашим брендом", "Marca blanca", "Kendi markanızla", "Marca branca", "白标", "Własna marka", "Me markën tuaj"],
  ["lastPayment", "Last payment", "Letzte Zahlung", "Laatste betaling", "Dernier paiement", "Ultimo pagamento", "Последний платёж", "Último pago", "Son ödeme", "Último pagamento", "最近付款", "Ostatnia płatność", "Pagesa e fundit"],
  ["nextPayment", "Next payment", "Nächste Zahlung", "Volgende betaling", "Prochain paiement", "Prossimo pagamento", "Следующий платёж", "Próximo pago", "Sonraki ödeme", "Próximo pagamento", "下次付款", "Następna płatność", "Pagesa e ardhshme"],
  ["daysRemaining", "Days remaining", "Verbleibende Tage", "Resterende dagen", "Jours restants", "Giorni rimanenti", "Осталось дней", "Días restantes", "Kalan gün", "Dias restantes", "剩余天数", "Pozostałe dni", "Ditë të mbetura"],
  ["currentPlan", "Current plan", "Aktueller Tarif", "Huidig abonnement", "Offre actuelle", "Piano attuale", "Текущий тариф", "Plan actual", "Mevcut plan", "Plano atual", "当前套餐", "Bieżący plan", "Paketa aktuale"],
  ["subscriptionEnds", "Subscription ends", "Abonnement endet", "Abonnement eindigt", "Fin de l’abonnement", "Fine abbonamento", "Подписка заканчивается", "Fin de la suscripción", "Abonelik bitişi", "Fim da subscrição", "订阅结束", "Koniec subskrypcji", "Përfundimi i abonimit"],
  ["perBillingPeriod", "{amount} per billing period", "{amount} pro Abrechnungszeitraum", "{amount} per facturatieperiode", "{amount} par période de facturation", "{amount} per periodo di fatturazione", "{amount} за расчётный период", "{amount} por periodo de facturación", "Fatura dönemi başına {amount}", "{amount} por período de faturação", "每个账单周期 {amount}", "{amount} za okres rozliczeniowy", "{amount} për periudhë faturimi"],
  ["currentPeriodEnds", "Current period ends {date}", "Aktueller Zeitraum endet am {date}", "Huidige periode eindigt op {date}", "La période en cours se termine le {date}", "Il periodo attuale termina il {date}", "Текущий период заканчивается {date}", "El periodo actual termina el {date}", "Mevcut dönem {date} tarihinde sona eriyor", "O período atual termina em {date}", "当前周期结束于 {date}", "Bieżący okres kończy się {date}", "Periudha aktuale përfundon më {date}"],
  ["customerSafeBilling", "Customer-safe billing view only. Exact payment method and invoice internals stay inside Stripe.", "Dies ist nur eine sichere Kundenansicht der Abrechnung. Genaue Zahlungsmethode und Rechnungsdetails verbleiben bei Stripe.", "Dit is alleen een veilige facturatieweergave voor klanten. De exacte betaalmethode en factuurgegevens blijven binnen Stripe.", "Cette vue de facturation est sécurisée pour le client. Le moyen de paiement exact et les détails des factures restent dans Stripe.", "Questa è una vista di fatturazione sicura per il cliente. Il metodo di pagamento esatto e i dettagli delle fatture restano in Stripe.", "Это безопасное представление оплаты для клиента. Точный способ оплаты и внутренние данные счетов остаются в Stripe.", "Esta es una vista de facturación segura para el cliente. El método de pago exacto y los detalles de las facturas permanecen en Stripe.", "Bu yalnızca müşteriye güvenli faturalandırma görünümüdür. Kesin ödeme yöntemi ve fatura ayrıntıları Stripe içinde kalır.", "Esta é apenas uma vista de faturação segura para o cliente. O método de pagamento exato e os detalhes das faturas permanecem no Stripe.", "此处仅显示客户安全的账单信息，具体付款方式和账单内部详情保留在 Stripe 中。", "To bezpieczny widok rozliczeń dla klienta. Dokładna metoda płatności i szczegóły faktur pozostają w Stripe.", "Kjo është vetëm një pamje faturimi e sigurt për klientin. Mënyra e saktë e pagesës dhe hollësitë e faturës mbeten brenda Stripe."],
  ["refresh", "Refresh", "Aktualisieren", "Vernieuwen", "Actualiser", "Aggiorna", "Обновить", "Actualizar", "Yenile", "Atualizar", "刷新", "Odśwież", "Rifresko"],
  ["viewWidgetPlans", "View widget plans", "Widget-Tarife ansehen", "Widgetabonnementen bekijken", "Voir les offres du widget", "Vedi i piani del widget", "Посмотреть тарифы виджета", "Ver planes del widget", "Widget paketlerini görüntüle", "Ver planos do widget", "查看小组件套餐", "Zobacz plany widżetu", "Shiko paketat e widget-it"],
  ["contactSupport", "Contact support", "Support kontaktieren", "Contact opnemen met support", "Contacter l’assistance", "Contatta l’assistenza", "Связаться с поддержкой", "Contactar con soporte", "Destekle iletişime geç", "Contactar o suporte", "联系支持", "Skontaktuj się z pomocą", "Kontakto mbështetjen"],
  ["billingDetailsUnavailable", "Live Stripe billing details could not be loaded. Open the billing portal for exact invoice data.", "Die aktuellen Stripe-Abrechnungsdetails konnten nicht geladen werden. Öffnen Sie das Abrechnungsportal für genaue Rechnungsdaten.", "De actuele Stripe-facturatiegegevens konden niet worden geladen. Open het facturatieportaal voor de exacte factuurgegevens.", "Les informations de facturation Stripe en direct n’ont pas pu être chargées. Ouvrez le portail de facturation pour consulter les données exactes des factures.", "Non è stato possibile caricare i dati di fatturazione Stripe aggiornati. Apri il portale di fatturazione per i dati esatti delle fatture.", "Не удалось загрузить актуальные платёжные данные Stripe. Откройте платёжный портал для точных данных счетов.", "No se pudieron cargar los datos de facturación de Stripe en directo. Abra el portal de facturación para consultar los datos exactos de las facturas.", "Canlı Stripe faturalandırma ayrıntıları yüklenemedi. Kesin fatura verileri için faturalandırma portalını açın.", "Não foi possível carregar os dados de faturação Stripe em direto. Abra o portal de faturação para consultar os dados exatos das faturas.", "无法加载 Stripe 实时账单详情。请打开账单门户查看准确账单数据。", "Nie udało się wczytać bieżących danych rozliczeniowych Stripe. Otwórz portal rozliczeniowy, aby zobaczyć dokładne dane faktur.", "Hollësitë e faturimit Stripe nuk mund të ngarkoheshin. Hapni portalin e faturimit për të dhënat e sakta të faturës."],
  ["noActiveStripeDetails", "No active Stripe subscription details were found for this widget.", "Für dieses Widget wurden keine aktiven Stripe-Abonnementdetails gefunden.", "Er zijn geen gegevens van een actief Stripe-abonnement voor deze widget gevonden.", "Aucune information d’abonnement Stripe actif n’a été trouvée pour ce widget.", "Non sono stati trovati dati di un abbonamento Stripe attivo per questo widget.", "Для этого виджета не найдены данные активной подписки Stripe.", "No se encontraron datos de una suscripción de Stripe activa para este widget.", "Bu widget için etkin Stripe abonelik ayrıntısı bulunamadı.", "Não foram encontrados dados de uma subscrição Stripe ativa para este widget.", "未找到此小组件的有效 Stripe 订阅详情。", "Nie znaleziono danych aktywnej subskrypcji Stripe dla tego widżetu.", "Nuk u gjetën hollësi të abonimit aktiv Stripe për këtë widget."],
  ["subscriptionScheduledEnd", "This subscription is scheduled to end at the current period boundary.", "Dieses Abonnement endet planmäßig zum Ende des aktuellen Zeitraums.", "Dit abonnement eindigt volgens planning aan het einde van de huidige periode.", "Cet abonnement doit prendre fin à l’issue de la période en cours.", "Questo abbonamento terminerà alla fine del periodo corrente.", "Подписка завершится в конце текущего периода.", "Esta suscripción está programada para finalizar al término del periodo actual.", "Bu abonelik mevcut dönemin sonunda sona erecek şekilde planlandı.", "Esta subscrição está agendada para terminar no fim do período atual.", "此订阅计划在当前周期结束时终止。", "Ta subskrypcja zakończy się z końcem bieżącego okresu.", "Ky abonim është planifikuar të përfundojë në fund të periudhës aktuale."],
  ["billingSummaryApiFailed", "Widget subscription summary could not be loaded.", "Die Widget-Abonnementübersicht konnte nicht geladen werden.", "Het overzicht van het widgetabonnement kon niet worden geladen.", "Le récapitulatif de l’abonnement au widget n’a pas pu être chargé.", "Non è stato possibile caricare il riepilogo dell’abbonamento al widget.", "Не удалось загрузить сводку подписки на виджет.", "No se pudo cargar el resumen de la suscripción al widget.", "Widget abonelik özeti yüklenemedi.", "Não foi possível carregar o resumo da subscrição do widget.", "无法加载小组件订阅摘要。", "Nie udało się wczytać podsumowania subskrypcji widżetu.", "Përmbledhja e abonimit të widget-it nuk mund të ngarkohej."],
  ["statusActive", "Active", "Aktiv", "Actief", "Actif", "Attivo", "Активна", "Activa", "Etkin", "Ativo", "有效", "Aktywna", "Aktiv"],
  ["statusTrialing", "Trialing", "Testphase", "Proefperiode", "Période d’essai", "Periodo di prova", "Пробный период", "Periodo de prueba", "Deneme süresi", "Período experimental", "试用期", "Okres próbny", "Periudhë prove"],
  ["statusPending", "Pending", "Ausstehend", "In afwachting", "En attente", "In attesa", "Ожидает", "Pendiente", "Bekliyor", "Pendente", "待处理", "Oczekuje", "Në pritje"],
  ["statusPastDue", "Past due", "Überfällig", "Achterstallig", "Paiement en retard", "Pagamento scaduto", "Просрочена", "Pago vencido", "Ödeme gecikmiş", "Pagamento em atraso", "逾期", "Płatność zaległa", "Pagesë e vonuar"],
  ["statusSuspended", "Suspended", "Gesperrt", "Opgeschort", "Suspendu", "Sospeso", "Приостановлена", "Suspendida", "Askıya alındı", "Suspenso", "已暂停", "Zawieszona", "Pezulluar"],
  ["statusCancelled", "Cancelled", "Gekündigt", "Geannuleerd", "Résilié", "Annullato", "Отменена", "Cancelada", "İptal edildi", "Cancelado", "已取消", "Anulowana", "Anuluar"],
  ["statusInactive", "Inactive", "Inaktiv", "Inactief", "Inactif", "Inattivo", "Неактивна", "Inactiva", "Etkin değil", "Inativo", "未启用", "Nieaktywna", "Joaktiv"],
  ["statusApproved", "Approved", "Bestätigt", "Goedgekeurd", "Approuvé", "Approvato", "Одобрено", "Aprobado", "Onaylandı", "Aprovado", "已批准", "Zatwierdzone", "Miratuar"],
  ["statusRejected", "Rejected", "Abgelehnt", "Afgewezen", "Refusé", "Rifiutato", "Отклонено", "Rechazado", "Reddedildi", "Rejeitado", "已拒绝", "Odrzucone", "Refuzuar"],
  ["close", "Close", "Schließen", "Sluiten", "Fermer", "Chiudi", "Закрыть", "Cerrar", "Kapat", "Fechar", "关闭", "Zamknij", "Mbyll"],
] as const satisfies readonly TranslationRow[];

export type WidgetSiteTranslationKey = (typeof widgetSiteRows)[number][0];
type WidgetSiteDictionary = Record<WidgetSiteTranslationKey, string>;

function dictionaryFor(locale: LocaleCode): WidgetSiteDictionary {
  const localeIndex = widgetSiteAllLocaleOrder.indexOf(locale);
  const result = Object.create(null) as WidgetSiteDictionary;

  for (const row of widgetSiteRows) {
    result[row[0]] = row[localeIndex + 1];
  }

  return result;
}

export const widgetSiteTranslations = Object.fromEntries(
  widgetSiteAllLocaleOrder.map((locale) => [locale, dictionaryFor(locale)]),
) as Record<LocaleCode, WidgetSiteDictionary>;

function interpolate(template: string, values?: Record<string, string | number>) {
  if (!values) return template;

  return template.replace(/\{([a-zA-Z0-9_]+)\}/g, (match, key: string) =>
    Object.prototype.hasOwnProperty.call(values, key) ? String(values[key]) : match,
  );
}

export function widgetSiteT(
  locale: LocaleCode,
  key: WidgetSiteTranslationKey,
  values?: Record<string, string | number>,
) {
  return interpolate(widgetSiteTranslations[locale][key], values);
}

export function translateWidgetSiteExact(
  locale: LocaleCode,
  value: unknown,
  fallbackKey: WidgetSiteTranslationKey,
) {
  if (typeof value !== "string" || !value.trim()) return widgetSiteT(locale, fallbackKey);

  const row = widgetSiteRows.find((entry) => entry[1] === value.trim());
  return row ? row[widgetSiteAllLocaleOrder.indexOf(locale) + 1] : widgetSiteT(locale, fallbackKey);
}

const statusTranslationKeys: Record<string, WidgetSiteTranslationKey> = {
  active: "statusActive",
  trialing: "statusTrialing",
  pending: "statusPending",
  past_due: "statusPastDue",
  suspended: "statusSuspended",
  cancelled: "statusCancelled",
  canceled: "statusCancelled",
  inactive: "statusInactive",
  approved: "statusApproved",
  rejected: "statusRejected",
};

export function widgetSiteStatusLabel(locale: LocaleCode, value: string | null | undefined) {
  if (!value) return widgetSiteT(locale, "notAvailable");
  const normalized = value.trim().toLowerCase();
  const key = statusTranslationKeys[normalized];
  return key
    ? widgetSiteT(locale, key)
    : value.replace(/_/g, " ").replace(/\b\w/g, (character) => character.toUpperCase());
}

export function widgetSitePlanLabel(locale: LocaleCode, value: string | null | undefined) {
  if (!value) return widgetSiteT(locale, "notAvailable");
  const normalized = value.trim().toLowerCase();
  if (normalized === "starter") return "Starter";
  if (normalized === "pro") return "Pro";
  if (normalized === "white_label") return widgetSiteT(locale, "planWhiteLabel");
  return value;
}

export type WidgetSiteTranslationTuple = readonly [
  de: string,
  nl: string,
  fr: string,
  it: string,
  ru: string,
  es: string,
  tr: string,
  pt: string,
  zh: string,
  pl: string,
  sq: string,
];

export const widgetSiteExactTranslations = Object.fromEntries(
  widgetSiteRows.map(([, source, de, nl, fr, it, ru, es, tr, pt, zh, pl, sq]) => [
    source,
    [de, nl, fr, it, ru, es, tr, pt, zh, pl, sq] satisfies WidgetSiteTranslationTuple,
  ] as const),
) as Record<string, WidgetSiteTranslationTuple>;

export const widgetSiteSourceCount = widgetSiteRows.length;
