import { isWidgetLanguage, type WidgetLanguage } from "@/lib/widget/types";

export const widgetTranslationKeys = [
  "vehicleLookupCodeGenerator", "widgetSettings", "themeMode", "mainColour",
  "buttonTextColour", "differenceColour", "otherSettings", "language",
  "enabledLanguages", "emailAddressForEnquiries", "whatsappNumber", "websiteDomain",
  "livePreview", "yourEmbedCodeIs", "copy", "copied", "subscriptionInactive",
  "manageSubscription", "doYouNeedSupport", "supportText", "advanced",
  "getVehicleDataOnceSelected", "advancedDescription", "selectVehicle",
  "selectVehicleType", "selectMake", "selectModel", "selectYear", "selectEngine",
  "searchPlaceholder", "noResults", "loading", "unavailable", "poweredBy",
  "startSubscription", "monthlyPrice", "cancelAnytime", "easyIntegration",
  "languagesIncluded", "showTuningOptions", "contactSupport", "manageBilling",
  "domainLocked", "domainChangeRequest",
] as const;

export type WidgetTranslationKey = (typeof widgetTranslationKeys)[number];
type WidgetDictionary = Record<WidgetTranslationKey, string>;

const en: WidgetDictionary = {
  vehicleLookupCodeGenerator: "Vehicle Lookup Code Generator", widgetSettings: "Widget settings",
  themeMode: "Theme mode", mainColour: "Main colour", buttonTextColour: "Button text colour",
  differenceColour: "Highlight colour", otherSettings: "Other settings", language: "Language",
  enabledLanguages: "Enabled languages", emailAddressForEnquiries: "Email address for enquiries",
  whatsappNumber: "WhatsApp number", websiteDomain: "Website domain", livePreview: "Live preview",
  yourEmbedCodeIs: "Your embed code", copy: "Copy", copied: "Copied", subscriptionInactive: "Your widget subscription is currently inactive. Please update your subscription to reactivate your widget.",
  manageSubscription: "Manage subscription", doYouNeedSupport: "Do you need support?",
  supportText: "We are here to help if you run into any difficulties. If you would like MG AutoTech to help embed this widget into your website, contact us with your website details.",
  advanced: "Advanced", getVehicleDataOnceSelected: "Get vehicle data once selected",
  advancedDescription: "Use JavaScript to collect the selected vehicle data after a visitor completes the selection. This is useful if you want to pass the vehicle data into your contact form.",
  selectVehicle: "Select a vehicle", selectVehicleType: "Select vehicle type", selectMake: "Select manufacturer",
  selectModel: "Select model", selectYear: "Select year / generation", selectEngine: "Select engine",
  searchPlaceholder: "Search vehicles", noResults: "No results", loading: "Loading...",
  unavailable: "Vehicle selector temporarily unavailable.", poweredBy: "Powered by MG AutoTech",
  startSubscription: "Start for EUR 4.99/month", monthlyPrice: "per month", cancelAnytime: "Cancel anytime",
  easyIntegration: "Easy script or iframe integration", languagesIncluded: "12 languages included",
  showTuningOptions: "Show tuning options", contactSupport: "Contact support", manageBilling: "Manage billing",
  domainLocked: "Domain locked", domainChangeRequest: "Request domain change",
};

function dictionary(values: Partial<WidgetDictionary>): WidgetDictionary {
  return { ...en, ...values };
}

export const widgetTranslations: Record<WidgetLanguage, WidgetDictionary> = {
  en,
  de: dictionary({ vehicleLookupCodeGenerator: "Fahrzeugauswahl-Codegenerator", widgetSettings: "Widget-Einstellungen", themeMode: "Darstellung", mainColour: "Hauptfarbe", buttonTextColour: "Button-Textfarbe", differenceColour: "Akzentfarbe", otherSettings: "Weitere Einstellungen", language: "Sprache", enabledLanguages: "Aktivierte Sprachen", emailAddressForEnquiries: "E-Mail-Adresse fuer Anfragen", whatsappNumber: "WhatsApp-Nummer", websiteDomain: "Website-Domain", livePreview: "Live-Vorschau", yourEmbedCodeIs: "Ihr Einbettungscode", copy: "Kopieren", copied: "Kopiert", subscriptionInactive: "Ihr Widget-Abonnement ist derzeit inaktiv. Aktualisieren Sie Ihr Abonnement, um das Widget wieder zu aktivieren.", manageSubscription: "Abonnement verwalten", doYouNeedSupport: "Benötigen Sie Unterstützung?", supportText: "Wir helfen Ihnen bei technischen Fragen. Wenn MG AutoTech das Widget in Ihre Website einbauen soll, senden Sie uns bitte Ihre Website-Daten.", advanced: "Erweitert", getVehicleDataOnceSelected: "Fahrzeugdaten nach der Auswahl empfangen", advancedDescription: "Mit JavaScript können Sie die ausgewählten Fahrzeugdaten übernehmen und zum Beispiel an Ihr Kontaktformular weitergeben.", selectVehicle: "Fahrzeug auswählen", selectVehicleType: "Fahrzeugtyp auswählen", selectMake: "Hersteller auswählen", selectModel: "Modell auswählen", selectYear: "Baujahr / Generation auswählen", selectEngine: "Motor auswählen", searchPlaceholder: "Fahrzeuge suchen", noResults: "Keine Ergebnisse", loading: "Wird geladen...", unavailable: "Die Fahrzeugauswahl ist vorübergehend nicht verfügbar.", poweredBy: "Bereitgestellt von MG AutoTech", startSubscription: "Für 4,99 EUR/Monat starten", monthlyPrice: "pro Monat", cancelAnytime: "Jederzeit kündbar", easyIntegration: "Einfache Script- oder iFrame-Integration", languagesIncluded: "12 Sprachen inklusive", showTuningOptions: "Tuning-Optionen anzeigen", contactSupport: "Support kontaktieren", manageBilling: "Zahlungen verwalten", domainLocked: "Domain geschützt", domainChangeRequest: "Domainwechsel beantragen" }),
  tr: dictionary({ vehicleLookupCodeGenerator: "Araç Seçici Kod Oluşturucu", widgetSettings: "Widget ayarları", themeMode: "Tema modu", mainColour: "Ana renk", buttonTextColour: "Buton yazı rengi", differenceColour: "Vurgu rengi", otherSettings: "Diğer ayarlar", language: "Dil", enabledLanguages: "Etkin diller", emailAddressForEnquiries: "Talepler için e-posta", whatsappNumber: "WhatsApp numarası", websiteDomain: "Web sitesi alan adı", livePreview: "Canlı önizleme", yourEmbedCodeIs: "Yerleştirme kodunuz", copy: "Kopyala", copied: "Kopyalandı", subscriptionInactive: "Widget aboneliğiniz şu anda etkin değil. Yeniden etkinleştirmek için aboneliğinizi güncelleyin.", manageSubscription: "Aboneliği yönet", doYouNeedSupport: "Desteğe mi ihtiyacınız var?", supportText: "Herhangi bir sorun yaşarsanız yardımcı oluruz. MG AutoTech'in widget'ı sitenize eklemesini isterseniz web sitesi bilgilerinizle bize ulaşın.", advanced: "Gelişmiş", getVehicleDataOnceSelected: "Seçilen araç verisini alın", advancedDescription: "Ziyaretçi seçimi tamamladığında araç verisini JavaScript ile alıp iletişim formunuza aktarabilirsiniz.", selectVehicle: "Araç seçin", selectVehicleType: "Araç tipi seçin", selectMake: "Marka seçin", selectModel: "Model seçin", selectYear: "Yıl / nesil seçin", selectEngine: "Motor seçin", searchPlaceholder: "Araç ara", noResults: "Sonuç bulunamadı", loading: "Yükleniyor...", unavailable: "Araç seçici geçici olarak kullanılamıyor.", poweredBy: "MG AutoTech tarafından sunulur", startSubscription: "Aylık 4,99 EUR ile başla", monthlyPrice: "aylık", cancelAnytime: "İstediğiniz zaman iptal edin", easyIntegration: "Kolay script veya iframe entegrasyonu", languagesIncluded: "12 dil dahil", showTuningOptions: "Tuning seçeneklerini göster", contactSupport: "Destekle iletişime geç", manageBilling: "Ödemeleri yönet", domainLocked: "Alan adı kilitli", domainChangeRequest: "Alan adı değişikliği iste" }),
  fr: dictionary({ vehicleLookupCodeGenerator: "Générateur de sélecteur de véhicule", widgetSettings: "Paramètres du widget", themeMode: "Mode d’affichage", mainColour: "Couleur principale", buttonTextColour: "Couleur du texte du bouton", differenceColour: "Couleur d’accent", otherSettings: "Autres paramètres", language: "Langue", enabledLanguages: "Langues activées", emailAddressForEnquiries: "E-mail pour les demandes", whatsappNumber: "Numéro WhatsApp", websiteDomain: "Domaine du site", livePreview: "Aperçu en direct", yourEmbedCodeIs: "Votre code d’intégration", copy: "Copier", copied: "Copié", subscriptionInactive: "Votre abonnement au widget est actuellement inactif. Mettez-le à jour pour réactiver le widget.", manageSubscription: "Gérer l’abonnement", doYouNeedSupport: "Besoin d’aide ?", supportText: "Nous sommes à votre disposition. Pour demander à MG AutoTech d’intégrer le widget, contactez-nous avec les informations de votre site.", advanced: "Avancé", getVehicleDataOnceSelected: "Récupérer les données du véhicule sélectionné", advancedDescription: "Utilisez JavaScript pour transmettre le véhicule sélectionné à votre formulaire de contact.", selectVehicle: "Sélectionner un véhicule", selectVehicleType: "Sélectionner le type de véhicule", selectMake: "Sélectionner la marque", selectModel: "Sélectionner le modèle", selectYear: "Sélectionner l’année / génération", selectEngine: "Sélectionner le moteur", searchPlaceholder: "Rechercher un véhicule", noResults: "Aucun résultat", loading: "Chargement...", unavailable: "Le sélecteur de véhicule est temporairement indisponible.", poweredBy: "Propulsé par MG AutoTech", startSubscription: "Démarrer à 4,99 EUR/mois", monthlyPrice: "par mois", cancelAnytime: "Résiliable à tout moment", easyIntegration: "Intégration simple par script ou iframe", languagesIncluded: "12 langues incluses", showTuningOptions: "Afficher les options de préparation", contactSupport: "Contacter l’assistance", manageBilling: "Gérer la facturation", domainLocked: "Domaine verrouillé", domainChangeRequest: "Demander un changement de domaine" }),
  es: dictionary({ vehicleLookupCodeGenerator: "Generador del selector de vehículos", widgetSettings: "Ajustes del widget", themeMode: "Modo de tema", mainColour: "Color principal", buttonTextColour: "Color del texto del botón", differenceColour: "Color de realce", otherSettings: "Otros ajustes", language: "Idioma", enabledLanguages: "Idiomas habilitados", emailAddressForEnquiries: "Correo para consultas", whatsappNumber: "Número de WhatsApp", websiteDomain: "Dominio del sitio web", livePreview: "Vista previa", yourEmbedCodeIs: "Código de inserción", copy: "Copiar", copied: "Copiado", subscriptionInactive: "La suscripción del widget está inactiva. Actualícela para reactivar el servicio.", manageSubscription: "Gestionar suscripción", doYouNeedSupport: "¿Necesita ayuda?", supportText: "Estamos para ayudarle. Si desea que MG AutoTech integre el widget, contáctenos con los datos de su sitio.", advanced: "Avanzado", getVehicleDataOnceSelected: "Obtener los datos del vehículo seleccionado", advancedDescription: "Use JavaScript para enviar los datos del vehículo seleccionado a su formulario de contacto.", selectVehicle: "Seleccionar vehículo", selectVehicleType: "Seleccionar tipo de vehículo", selectMake: "Seleccionar marca", selectModel: "Seleccionar modelo", selectYear: "Seleccionar año / generación", selectEngine: "Seleccionar motor", searchPlaceholder: "Buscar vehículos", noResults: "Sin resultados", loading: "Cargando...", unavailable: "El selector de vehículos no está disponible temporalmente.", poweredBy: "Desarrollado por MG AutoTech", startSubscription: "Empezar por 4,99 EUR/mes", monthlyPrice: "al mes", cancelAnytime: "Cancele cuando quiera", easyIntegration: "Integración sencilla mediante script o iframe", languagesIncluded: "12 idiomas incluidos", showTuningOptions: "Mostrar opciones de tuning", contactSupport: "Contactar con soporte", manageBilling: "Gestionar facturación", domainLocked: "Dominio bloqueado", domainChangeRequest: "Solicitar cambio de dominio" }),
  it: dictionary({ vehicleLookupCodeGenerator: "Generatore selettore veicolo", widgetSettings: "Impostazioni widget", themeMode: "Modalità tema", mainColour: "Colore principale", buttonTextColour: "Colore testo pulsante", differenceColour: "Colore evidenza", otherSettings: "Altre impostazioni", language: "Lingua", enabledLanguages: "Lingue abilitate", emailAddressForEnquiries: "E-mail per le richieste", whatsappNumber: "Numero WhatsApp", websiteDomain: "Dominio del sito", livePreview: "Anteprima dal vivo", yourEmbedCodeIs: "Codice di incorporamento", copy: "Copia", copied: "Copiato", subscriptionInactive: "L’abbonamento del widget non è attivo. Aggiornalo per riattivare il servizio.", manageSubscription: "Gestisci abbonamento", doYouNeedSupport: "Hai bisogno di assistenza?", supportText: "Siamo a disposizione. Se vuoi che MG AutoTech integri il widget, contattaci con i dati del sito.", advanced: "Avanzate", getVehicleDataOnceSelected: "Ricevi i dati del veicolo selezionato", advancedDescription: "Usa JavaScript per trasferire i dati del veicolo selezionato al modulo di contatto.", selectVehicle: "Seleziona un veicolo", selectVehicleType: "Seleziona tipo di veicolo", selectMake: "Seleziona marca", selectModel: "Seleziona modello", selectYear: "Seleziona anno / generazione", selectEngine: "Seleziona motore", searchPlaceholder: "Cerca veicoli", noResults: "Nessun risultato", loading: "Caricamento...", unavailable: "Il selettore veicolo è temporaneamente non disponibile.", poweredBy: "Offerto da MG AutoTech", startSubscription: "Inizia a 4,99 EUR/mese", monthlyPrice: "al mese", cancelAnytime: "Annulla in qualsiasi momento", easyIntegration: "Facile integrazione script o iframe", languagesIncluded: "12 lingue incluse", showTuningOptions: "Mostra opzioni tuning", contactSupport: "Contatta assistenza", manageBilling: "Gestisci pagamenti", domainLocked: "Dominio bloccato", domainChangeRequest: "Richiedi cambio dominio" }),
  nl: dictionary({ vehicleLookupCodeGenerator: "Voertuigselector-codegenerator", widgetSettings: "Widgetinstellingen", themeMode: "Themamodus", mainColour: "Hoofdkleur", buttonTextColour: "Tekstkleur knop", differenceColour: "Accentkleur", otherSettings: "Overige instellingen", language: "Taal", enabledLanguages: "Ingeschakelde talen", emailAddressForEnquiries: "E-mailadres voor aanvragen", whatsappNumber: "WhatsApp-nummer", websiteDomain: "Websitedomein", livePreview: "Live voorbeeld", yourEmbedCodeIs: "Uw insluitcode", copy: "Kopiëren", copied: "Gekopieerd", subscriptionInactive: "Uw widgetabonnement is momenteel inactief. Werk het abonnement bij om de widget opnieuw te activeren.", manageSubscription: "Abonnement beheren", doYouNeedSupport: "Hulp nodig?", supportText: "Wij helpen u graag. Wilt u dat MG AutoTech de widget inbouwt, neem dan contact op met uw websitegegevens.", advanced: "Geavanceerd", getVehicleDataOnceSelected: "Ontvang de geselecteerde voertuiggegevens", advancedDescription: "Gebruik JavaScript om het geselecteerde voertuig aan uw contactformulier door te geven.", selectVehicle: "Kies een voertuig", selectVehicleType: "Kies voertuigtype", selectMake: "Kies merk", selectModel: "Kies model", selectYear: "Kies jaar / generatie", selectEngine: "Kies motor", searchPlaceholder: "Voertuigen zoeken", noResults: "Geen resultaten", loading: "Laden...", unavailable: "De voertuigselector is tijdelijk niet beschikbaar.", poweredBy: "Mogelijk gemaakt door MG AutoTech", startSubscription: "Start voor 4,99 EUR/maand", monthlyPrice: "per maand", cancelAnytime: "Altijd opzegbaar", easyIntegration: "Eenvoudige script- of iframe-integratie", languagesIncluded: "12 talen inbegrepen", showTuningOptions: "Toon tuningopties", contactSupport: "Support contacteren", manageBilling: "Facturatie beheren", domainLocked: "Domein vergrendeld", domainChangeRequest: "Domeinwijziging aanvragen" }),
  pl: dictionary({ vehicleLookupCodeGenerator: "Generator selektora pojazdów", widgetSettings: "Ustawienia widżetu", themeMode: "Tryb motywu", mainColour: "Kolor główny", buttonTextColour: "Kolor tekstu przycisku", differenceColour: "Kolor wyróżnienia", otherSettings: "Pozostałe ustawienia", language: "Język", enabledLanguages: "Aktywne języki", emailAddressForEnquiries: "E-mail do zapytań", whatsappNumber: "Numer WhatsApp", websiteDomain: "Domena strony", livePreview: "Podgląd na żywo", yourEmbedCodeIs: "Kod osadzania", copy: "Kopiuj", copied: "Skopiowano", subscriptionInactive: "Subskrypcja widżetu jest nieaktywna. Zaktualizuj ją, aby ponownie uruchomić widżet.", manageSubscription: "Zarządzaj subskrypcją", doYouNeedSupport: "Potrzebujesz pomocy?", supportText: "Chętnie pomożemy. Jeśli MG AutoTech ma osadzić widżet, prześlij nam dane swojej strony.", advanced: "Zaawansowane", getVehicleDataOnceSelected: "Pobierz dane wybranego pojazdu", advancedDescription: "Użyj JavaScript, aby przekazać wybrany pojazd do formularza kontaktowego.", selectVehicle: "Wybierz pojazd", selectVehicleType: "Wybierz typ pojazdu", selectMake: "Wybierz markę", selectModel: "Wybierz model", selectYear: "Wybierz rok / generację", selectEngine: "Wybierz silnik", searchPlaceholder: "Szukaj pojazdów", noResults: "Brak wyników", loading: "Ładowanie...", unavailable: "Selektor pojazdów jest chwilowo niedostępny.", poweredBy: "Obsługiwane przez MG AutoTech", startSubscription: "Zacznij za 4,99 EUR/miesiąc", monthlyPrice: "miesięcznie", cancelAnytime: "Anuluj w dowolnym momencie", easyIntegration: "Łatwa integracja przez skrypt lub iframe", languagesIncluded: "12 języków w cenie", showTuningOptions: "Pokaż opcje tuningu", contactSupport: "Skontaktuj się z pomocą", manageBilling: "Zarządzaj płatnościami", domainLocked: "Domena zablokowana", domainChangeRequest: "Poproś o zmianę domeny" }),
  ro: dictionary({ vehicleLookupCodeGenerator: "Generator selector auto", widgetSettings: "Setări widget", themeMode: "Mod temă", mainColour: "Culoare principală", buttonTextColour: "Culoare text buton", differenceColour: "Culoare de accent", otherSettings: "Alte setări", language: "Limbă", enabledLanguages: "Limbi active", emailAddressForEnquiries: "E-mail pentru solicitări", whatsappNumber: "Număr WhatsApp", websiteDomain: "Domeniul site-ului", livePreview: "Previzualizare live", yourEmbedCodeIs: "Codul de integrare", copy: "Copiază", copied: "Copiat", subscriptionInactive: "Abonamentul widgetului este inactiv. Actualizați abonamentul pentru reactivare.", manageSubscription: "Gestionează abonamentul", doYouNeedSupport: "Aveți nevoie de ajutor?", supportText: "Suntem aici pentru a vă ajuta. Dacă doriți ca MG AutoTech să integreze widgetul, trimiteți-ne detaliile site-ului.", advanced: "Avansat", getVehicleDataOnceSelected: "Preluați datele vehiculului selectat", advancedDescription: "Folosiți JavaScript pentru a trimite vehiculul selectat către formularul de contact.", selectVehicle: "Selectați un vehicul", selectVehicleType: "Selectați tipul vehiculului", selectMake: "Selectați marca", selectModel: "Selectați modelul", selectYear: "Selectați anul / generația", selectEngine: "Selectați motorul", searchPlaceholder: "Căutați vehicule", noResults: "Niciun rezultat", loading: "Se încarcă...", unavailable: "Selectorul auto este temporar indisponibil.", poweredBy: "Furnizat de MG AutoTech", startSubscription: "Începeți cu 4,99 EUR/lună", monthlyPrice: "pe lună", cancelAnytime: "Anulați oricând", easyIntegration: "Integrare simplă prin script sau iframe", languagesIncluded: "12 limbi incluse", showTuningOptions: "Afișați opțiunile de tuning", contactSupport: "Contactați asistența", manageBilling: "Gestionați facturarea", domainLocked: "Domeniu blocat", domainChangeRequest: "Solicitați schimbarea domeniului" }),
  pt: dictionary({ vehicleLookupCodeGenerator: "Gerador do seletor de veículos", widgetSettings: "Definições do widget", themeMode: "Modo do tema", mainColour: "Cor principal", buttonTextColour: "Cor do texto do botão", differenceColour: "Cor de destaque", otherSettings: "Outras definições", language: "Idioma", enabledLanguages: "Idiomas ativos", emailAddressForEnquiries: "E-mail para pedidos", whatsappNumber: "Número de WhatsApp", websiteDomain: "Domínio do site", livePreview: "Pré-visualização", yourEmbedCodeIs: "Código de incorporação", copy: "Copiar", copied: "Copiado", subscriptionInactive: "A subscrição do widget está inativa. Atualize-a para reativar o serviço.", manageSubscription: "Gerir subscrição", doYouNeedSupport: "Precisa de ajuda?", supportText: "Estamos disponíveis para ajudar. Se desejar que a MG AutoTech integre o widget, envie-nos os dados do seu site.", advanced: "Avançado", getVehicleDataOnceSelected: "Obter dados do veículo selecionado", advancedDescription: "Use JavaScript para enviar o veículo selecionado para o seu formulário de contacto.", selectVehicle: "Selecionar veículo", selectVehicleType: "Selecionar tipo de veículo", selectMake: "Selecionar marca", selectModel: "Selecionar modelo", selectYear: "Selecionar ano / geração", selectEngine: "Selecionar motor", searchPlaceholder: "Pesquisar veículos", noResults: "Sem resultados", loading: "A carregar...", unavailable: "O seletor de veículos está temporariamente indisponível.", poweredBy: "Fornecido pela MG AutoTech", startSubscription: "Começar por 4,99 EUR/mês", monthlyPrice: "por mês", cancelAnytime: "Cancele a qualquer momento", easyIntegration: "Integração fácil por script ou iframe", languagesIncluded: "12 idiomas incluídos", showTuningOptions: "Mostrar opções de tuning", contactSupport: "Contactar suporte", manageBilling: "Gerir faturação", domainLocked: "Domínio bloqueado", domainChangeRequest: "Pedir alteração de domínio" }),
  ru: dictionary({ vehicleLookupCodeGenerator: "Генератор виджета подбора автомобиля", widgetSettings: "Настройки виджета", themeMode: "Режим темы", mainColour: "Основной цвет", buttonTextColour: "Цвет текста кнопки", differenceColour: "Акцентный цвет", otherSettings: "Другие настройки", language: "Язык", enabledLanguages: "Доступные языки", emailAddressForEnquiries: "E-mail для запросов", whatsappNumber: "Номер WhatsApp", websiteDomain: "Домен сайта", livePreview: "Предпросмотр", yourEmbedCodeIs: "Код для вставки", copy: "Копировать", copied: "Скопировано", subscriptionInactive: "Подписка на виджет неактивна. Обновите подписку, чтобы снова включить виджет.", manageSubscription: "Управление подпиской", doYouNeedSupport: "Нужна помощь?", supportText: "Мы готовы помочь. Если вы хотите, чтобы MG AutoTech установил виджет, отправьте нам данные вашего сайта.", advanced: "Расширенные возможности", getVehicleDataOnceSelected: "Получать данные выбранного автомобиля", advancedDescription: "Используйте JavaScript, чтобы передать выбранный автомобиль в контактную форму.", selectVehicle: "Выберите автомобиль", selectVehicleType: "Выберите тип автомобиля", selectMake: "Выберите марку", selectModel: "Выберите модель", selectYear: "Выберите год / поколение", selectEngine: "Выберите двигатель", searchPlaceholder: "Поиск автомобилей", noResults: "Ничего не найдено", loading: "Загрузка...", unavailable: "Подбор автомобиля временно недоступен.", poweredBy: "Работает на MG AutoTech", startSubscription: "Подключить за 4,99 EUR/месяц", monthlyPrice: "в месяц", cancelAnytime: "Отмена в любое время", easyIntegration: "Простая интеграция через script или iframe", languagesIncluded: "12 языков включено", showTuningOptions: "Показать варианты тюнинга", contactSupport: "Связаться с поддержкой", manageBilling: "Управление оплатой", domainLocked: "Домен закреплён", domainChangeRequest: "Запросить смену домена" }),
  ar: dictionary({ vehicleLookupCodeGenerator: "مولد كود اختيار المركبة", widgetSettings: "إعدادات الأداة", themeMode: "نمط العرض", mainColour: "اللون الرئيسي", buttonTextColour: "لون نص الزر", differenceColour: "لون التمييز", otherSettings: "إعدادات أخرى", language: "اللغة", enabledLanguages: "اللغات المفعلة", emailAddressForEnquiries: "البريد الإلكتروني للاستفسارات", whatsappNumber: "رقم واتساب", websiteDomain: "نطاق الموقع", livePreview: "معاينة مباشرة", yourEmbedCodeIs: "كود التضمين", copy: "نسخ", copied: "تم النسخ", subscriptionInactive: "اشتراك الأداة غير نشط حالياً. حدّث الاشتراك لإعادة تشغيلها.", manageSubscription: "إدارة الاشتراك", doYouNeedSupport: "هل تحتاج إلى دعم؟", supportText: "نحن هنا للمساعدة. إذا أردت من MG AutoTech تضمين الأداة في موقعك، تواصل معنا وأرسل تفاصيل الموقع.", advanced: "متقدم", getVehicleDataOnceSelected: "الحصول على بيانات المركبة بعد اختيارها", advancedDescription: "استخدم JavaScript لنقل بيانات المركبة المختارة إلى نموذج التواصل في موقعك.", selectVehicle: "اختر مركبة", selectVehicleType: "اختر نوع المركبة", selectMake: "اختر الشركة المصنعة", selectModel: "اختر الطراز", selectYear: "اختر السنة / الجيل", selectEngine: "اختر المحرك", searchPlaceholder: "البحث عن مركبة", noResults: "لا توجد نتائج", loading: "جارٍ التحميل...", unavailable: "أداة اختيار المركبة غير متاحة مؤقتاً.", poweredBy: "مقدم من MG AutoTech", startSubscription: "ابدأ مقابل 4.99 EUR شهرياً", monthlyPrice: "شهرياً", cancelAnytime: "يمكن الإلغاء في أي وقت", easyIntegration: "دمج سهل عبر script أو iframe", languagesIncluded: "12 لغة مشمولة", showTuningOptions: "عرض خيارات التعديل", contactSupport: "التواصل مع الدعم", manageBilling: "إدارة الفوترة", domainLocked: "النطاق مقيد", domainChangeRequest: "طلب تغيير النطاق" }),
};

export const widgetVehicleTypeLabels: Record<WidgetLanguage, string> = {
  de: "PKW / Transporter", en: "Car / Light commercial", tr: "Otomobil / Hafif ticari",
  fr: "Voiture / Utilitaire léger", es: "Turismo / Comercial ligero", it: "Auto / Veicolo commerciale leggero",
  nl: "Personenauto / Lichte bedrijfswagen", pl: "Samochód / Lekki pojazd użytkowy",
  ro: "Autoturism / Utilitară ușoară", pt: "Automóvel / Comercial ligeiro",
  ru: "Легковой / Лёгкий коммерческий", ar: "سيارة / مركبة تجارية خفيفة",
};

export function normalizeWidgetLanguage(value: unknown, fallback: WidgetLanguage = "en") {
  const code = typeof value === "string" ? value.toLowerCase().split(/[-_]/)[0] : "";
  return isWidgetLanguage(code) ? code : fallback;
}

export function widgetT(language: WidgetLanguage, key: WidgetTranslationKey) {
  return widgetTranslations[language]?.[key] ?? widgetTranslations.en[key] ?? key;
}
