import { isWidgetLanguage, type WidgetLanguage } from "@/lib/widget/types";

export const widgetTranslationKeys = [
  "vehicleLookupCodeGenerator", "widgetSettings", "themeMode", "mainColour",
  "buttonTextColour", "differenceColour", "otherSettings", "language",
  "enabledLanguages", "emailAddressForEnquiries", "whatsappNumber", "websiteDomain",
  "livePreview", "yourEmbedCodeIs", "copy", "copied", "subscriptionInactive",
  "manageSubscription", "doYouNeedSupport", "supportText", "advanced",
  "getVehicleDataOnceSelected", "advancedDescription", "selectVehicle",
  "selectVehicleType", "selectMake", "selectModel", "selectYear", "selectEngine",
  "searchPlaceholder", "noResults", "loading", "unavailable", "poweredBy",
  "startSubscription", "monthlyPrice", "cancelAnytime", "easyIntegration",
  "languagesIncluded", "showTuningOptions", "contactSupport", "manageBilling",
  "domainLocked", "domainChangeRequest",
] as const;

export type WidgetTranslationKey = (typeof widgetTranslationKeys)[number];
type WidgetDictionary = Record<WidgetTranslationKey, string>;

const en: WidgetDictionary = {
  vehicleLookupCodeGenerator: "Vehicle Lookup Code Generator", widgetSettings: "Widget settings",
  themeMode: "Theme mode", mainColour: "Main colour", buttonTextColour: "Button text colour",
  differenceColour: "Highlight colour", otherSettings: "Other settings", language: "Language",
  enabledLanguages: "Enabled languages", emailAddressForEnquiries: "Email address for enquiries",
  whatsappNumber: "WhatsApp number", websiteDomain: "Website domain", livePreview: "Live preview",
  yourEmbedCodeIs: "Your embed code", copy: "Copy", copied: "Copied", subscriptionInactive: "Your widget subscription is currently inactive. Please update your subscription to reactivate your widget.",
  manageSubscription: "Manage subscription", doYouNeedSupport: "Do you need support?",
  supportText: "We are here to help if you run into any difficulties. If you would like MG AutoTech to help embed this widget into your website, contact us with your website details.",
  advanced: "Advanced", getVehicleDataOnceSelected: "Get vehicle data once selected",
  advancedDescription: "Use JavaScript to collect the selected vehicle data after a visitor completes the selection. This is useful if you want to pass the vehicle data into your contact form.",
  selectVehicle: "Select a vehicle", selectVehicleType: "Select vehicle type", selectMake: "Select manufacturer",
  selectModel: "Select model", selectYear: "Select year / generation", selectEngine: "Select engine",
  searchPlaceholder: "Search vehicles", noResults: "No results", loading: "Loading...",
  unavailable: "Vehicle selector temporarily unavailable.", poweredBy: "Powered by MG AutoTech",
  startSubscription: "Start for EUR 4.99/month", monthlyPrice: "per month", cancelAnytime: "Cancel anytime",
  easyIntegration: "Easy script or iframe integration", languagesIncluded: "12 languages included",
  showTuningOptions: "Show tuning options", contactSupport: "Contact support", manageBilling: "Manage billing",
  domainLocked: "Domain locked", domainChangeRequest: "Request domain change",
};

function dictionary(values: Partial<WidgetDictionary>): WidgetDictionary {
  return { ...en, ...values };
}

export const widgetTranslations: Record<WidgetLanguage, WidgetDictionary> = {
  en,
  de: dictionary({ vehicleLookupCodeGenerator: "Fahrzeugauswahl-Codegenerator", widgetSettings: "Widget-Einstellungen", themeMode: "Darstellung", mainColour: "Hauptfarbe", buttonTextColour: "Button-Textfarbe", differenceColour: "Akzentfarbe", otherSettings: "Weitere Einstellungen", language: "Sprache", enabledLanguages: "Aktivierte Sprachen", emailAddressForEnquiries: "E-Mail-Adresse fuer Anfragen", whatsappNumber: "WhatsApp-Nummer", websiteDomain: "Website-Domain", livePreview: "Live-Vorschau", yourEmbedCodeIs: "Ihr Einbettungscode", copy: "Kopieren", copied: "Kopiert", subscriptionInactive: "Ihr Widget-Abonnement ist derzeit inaktiv. Aktualisieren Sie Ihr Abonnement, um das Widget wieder zu aktivieren.", manageSubscription: "Abonnement verwalten", doYouNeedSupport: "Benötigen Sie Unterstützung?", supportText: "Wir helfen Ihnen bei technischen Fragen. Wenn MG AutoTech das Widget in Ihre Website einbauen soll, senden Sie uns bitte Ihre Website-Daten.", advanced: "Erweitert", getVehicleDataOnceSelected: "Fahrzeugdaten nach der Auswahl empfangen", advancedDescription: "Mit JavaScript können Sie die ausgewählten Fahrzeugdaten übernehmen und zum Beispiel an Ihr Kontaktformular weitergeben.", selectVehicle: "Fahrzeug auswählen", selectVehicleType: "Fahrzeugtyp auswählen", selectMake: "Hersteller auswählen", selectModel: "Modell auswählen", selectYear: "Baujahr / Generation auswählen", selectEngine: "Motor auswählen", searchPlaceholder: "Fahrzeuge suchen", noResults: "Keine Ergebnisse", loading: "Wird geladen...", unavailable: "Die Fahrzeugauswahl ist vorübergehend nicht verfügbar.", poweredBy: "Bereitgestellt von MG AutoTech", startSubscription: "Für 4,99 EUR/Monat starten", monthlyPrice: "pro Monat", cancelAnytime: "Jederzeit kündbar", easyIntegration: "Einfache Script- oder iFrame-Integration", languagesIncluded: "12 Sprachen inklusive", showTuningOptions: "Tuning-Optionen anzeigen", contactSupport: "Support kontaktieren", manageBilling: "Zahlungen verwalten", domainLocked: "Domain geschützt", domainChangeRequest: "Domainwechsel beantragen" }),
  tr: dictionary({ vehicleLookupCodeGenerator: "Araç Seçici Kod Oluşturucu", widgetSettings: "Widget ayarları", themeMode: "Tema modu", mainColour: "Ana renk", buttonTextColour: "Buton yazı rengi", differenceColour: "Vurgu rengi", otherSettings: "Diğer ayarlar", language: "Dil", enabledLanguages: "Etkin diller", emailAddressForEnquiries: "Talepler için e-posta", whatsappNumber: "WhatsApp numarası", websiteDomain: "Web sitesi alan adı", livePreview: "Canlı önizleme", yourEmbedCodeIs: "Yerleştirme kodunuz", copy: "Kopyala", copied: "Kopyalandı", subscriptionInactive: "Widget aboneliğiniz şu anda etkin değil. Yeniden etkinleştirmek için aboneliğinizi güncelleyin.", manageSubscription: "Aboneliği yönet", doYouNeedSupport: "Desteğe mi ihtiyacınız var?", supportText: "Herhangi bir sorun yaşarsanız yardımcı oluruz. MG AutoTech'in widget'ı sitenize eklemesini isterseniz web sitesi bilgilerinizle bize ulaşın.", advanced: "Gelişmiş", getVehicleDataOnceSelected: "Seçilen araç verisini alın", advancedDescription: "Ziyaretçi seçimi tamamladığında araç verisini JavaScript ile alıp iletişim formunuza aktarabilirsiniz.", selectVehicle: "Araç seçin", selectVehicleType: "Araç tipi seçin", selectMake: "Marka seçin", selectModel: "Model seçin", selectYear: "Yıl / nesil seçin", selectEngine: "Motor seçin", searchPlaceholder: "Araç ara", noResults: "Sonuç bulunamadı", loading: "Yükleniyor...", unavailable: "Araç seçici geçici olarak kullanılamıyor.", poweredBy: "MG AutoTech tarafından sunulur", startSubscription: "Aylık 4,99 EUR ile başla", monthlyPrice: "aylık", cancelAnytime: "İstediğiniz zaman iptal edin", easyIntegration: "Kolay script veya iframe entegrasyonu", languagesIncluded: "12 dil dahil", showTuningOptions: "Tuning seçeneklerini göster", contactSupport: "Destekle iletişime geç", manageBilling: "Ödemeleri yönet", domainLocked: "Alan adı kilitli", domainChangeRequest: "Alan adı değişikliği iste" }),
  fr: dictionary({ vehicleLookupCodeGenerator: "Générateur de sélecteur de véhicule", widgetSettings: "Paramètres du widget", themeMode: "Mode d’affichage", mainColour: "Couleur principale", buttonTextColour: "Couleur du texte du bouton", differenceColour: "Couleur d’accent", otherSettings: "Autres paramètres", language: "Langue", enabledLanguages: "Langues activées", emailAddressForEnquiries: "E-mail pour les demandes", whatsappNumber: "Numéro WhatsApp", websiteDomain: "Domaine du site", livePreview: "Aperçu en direct", yourEmbedCodeIs: "Votre code d’intégration", copy: "Copier", copied: "Copié", subscriptionInactive: "Votre abonnement au widget est actuellement inactif. Mettez-le à jour pour réactiver le widget.", manageSubscription: "Gérer l’abonnement", doYouNeedSupport: "Besoin d’aide ?", supportText: "Nous sommes à votre disposition. Pour demander à MG AutoTech d’intégrer le widget, contactez-nous avec les informations de votre site.", advanced: "Avancé", getVehicleDataOnceSelected: "Récupérer les données du véhicule sélectionné", advancedDescription: "Utilisez JavaScript pour transmettre le véhicule sélectionné à votre formulaire de contact.", selectVehicle: "Sélectionner un véhicule", selectVehicleType: "Sélectionner le type de véhicule", selectMake: "Sélectionner la marque", selectModel: "Sélectionner le modèle", selectYear: "Sélectionner l’année / génération", selectEngine: "Sélectionner le moteur", searchPlaceholder: "Rechercher un véhicule", noResults: "Aucun résultat", loading: "Chargement...", unavailable: "Le sélecteur de véhicule est temporairement indisponible.", poweredBy: "Propulsé par MG AutoTech", startSubscription: "Démarrer à 4,99 EUR/mois", monthlyPrice: "par mois", cancelAnytime: "Résiliable à tout moment", easyIntegration: "Intégration simple par script ou iframe", languagesIncluded: "12 langues incluses", showTuningOptions: "Afficher les options de préparation", contactSupport: "Contacter l’assistance", manageBilling: "Gérer la facturation", domainLocked: "Domaine verrouillé", domainChangeRequest: "Demander un changement de domaine" }),
  es: dictionary({ vehicleLookupCodeGenerator: "Generador del selector de vehículos", widgetSettings: "Ajustes del widget", themeMode: "Modo de tema", mainColour: "Color principal", buttonTextColour: "Color del texto del botón", differenceColour: "Color de realce", otherSettings: "Otros ajustes", language: "Idioma", enabledLanguages: "Idiomas habilitados", emailAddressForEnquiries: "Correo para consultas", whatsappNumber: "Número de WhatsApp", websiteDomain: "Dominio del sitio web", livePreview: "Vista previa", yourEmbedCodeIs: "Código de inserción", copy: "Copiar", copied: "Copiado", subscriptionInactive: "La suscripción del widget está inactiva. Actualícela para reactivar el servicio.", manageSubscription: "Gestionar suscripción", doYouNeedSupport: "¿Necesita ayuda?", supportText: "Estamos para ayudarle. Si desea que MG AutoTech integre el widget, contáctenos con los datos de su sitio.", advanced: "Avanzado", getVehicleDataOnceSelected: "Obtener los datos del vehículo seleccionado", advancedDescription: "Use JavaScript para enviar los datos del vehículo seleccionado a su formulario de contacto.", selectVehicle: "Seleccionar vehículo", selectVehicleType: "Seleccionar tipo de vehículo", selectMake: "Seleccionar marca", selectModel: "Seleccionar modelo", selectYear: "Seleccionar año / generación", selectEngine: "Seleccionar motor", searchPlaceholder: "Buscar vehículos", noResults: "Sin resultados", loading: "Cargando...", unavailable: "El selector de vehículos no está disponible temporalmente.", poweredBy: "Desarrollado por MG AutoTech", startSubscription: "Empezar por 4,99 EUR/mes", monthlyPrice: "al mes", cancelAnytime: "Cancele cuando quiera", easyIntegration: "Integración sencilla mediante script o iframe", languagesIncluded: "12 idiomas incluidos", showTuningOptions: "Mostrar opciones de tuning", contactSupport: "Contactar con soporte", manageBilling: "Gestionar facturación", domainLocked: "Dominio bloqueado", domainChangeRequest: "Solicitar cambio de dominio" }),
  it: dictionary({ vehicleLookupCodeGenerator: "Generatore selettore veicolo", widgetSettings: "Impostazioni widget", themeMode: "Modalità tema", mainColour: "Colore principale", buttonTextColour: "Colore testo pulsante", differenceColour: "Colore evidenza", otherSettings: "Altre impostazioni", language: "Lingua", enabledLanguages: "Lingue abilitate", emailAddressForEnquiries: "E-mail per le richieste", whatsappNumber: "Numero WhatsApp", websiteDomain: "Dominio del sito", livePreview: "Anteprima dal vivo", yourEmbedCodeIs: "Codice di incorporamento", copy: "Copia", copied: "Copiato", subscriptionInactive: "L’abbonamento del widget non è attivo. Aggiornalo per riattivare il servizio.", manageSubscription: "Gestisci abbonamento", doYouNeedSupport: "Hai bisogno di assistenza?", supportText: "Siamo a disposizione. Se vuoi che MG AutoTech integri il widget, contattaci con i dati del sito.", advanced: "Avanzate", getVehicleDataOnceSelected: "Ricevi i dati del veicolo selezionato", advancedDescription: "Usa JavaScript per trasferire i dati del veicolo selezionato al modulo di contatto.", selectVehicle: "Seleziona un veicolo", selectVehicleType: "Seleziona tipo di veicolo", selectMake: "Seleziona marca", selectModel: "Seleziona modello", selectYear: "Seleziona anno / generazione", selectEngine: "Seleziona motore", searchPlaceholder: "Cerca veicoli", noResults: "Nessun risultato", loading: "Caricamento...", unavailable: "Il selettore veicolo è temporaneamente non disponibile.", poweredBy: "Offerto da MG AutoTech", startSubscription: "Inizia a 4,99 EUR/mese", monthlyPrice: "al mese", cancelAnytime: "Annulla in qualsiasi momento", easyIntegration: "Facile integrazione script o iframe", languagesIncluded: "12 lingue incluse", showTuningOptions: "Mostra opzioni tuning", contactSupport: "Contatta assistenza", manageBilling: "Gestisci pagamenti", domainLocked: "Dominio bloccato", domainChangeRequest: "Richiedi cambio dominio" }),
  nl: dictionary({ vehicleLookupCodeGenerator: "Voertuigselector-codegenerator", widgetSettings: "Widgetinstellingen", themeMode: "Themamodus", mainColour: "Hoofdkleur", buttonTextColour: "Tekstkleur knop", differenceColour: "Accentkleur", otherSettings: "Overige instellingen", language: "Taal", enabledLanguages: "Ingeschakelde talen", emailAddressForEnquiries: "E-mailadres voor aanvragen", whatsappNumber: "WhatsApp-nummer", websiteDomain: "Websitedomein", livePreview: "Live voorbeeld", yourEmbedCodeIs: "Uw insluitcode", copy: "Kopiëren", copied: "Gekopieerd", subscriptionInactive: "Uw widgetabonnement is momenteel inactief. Werk het abonnement bij om de widget opnieuw te activeren.", manageSubscription: "Abonnement beheren", doYouNeedSupport: "Hulp nodig?", supportText: "Wij helpen u graag. Wilt u dat MG AutoTech de widget inbouwt, neem dan contact op met uw websitegegevens.", advanced: "Geavanceerd", getVehicleDataOnceSelected: "Ontvang de geselecteerde voertuiggegevens", advancedDescription: "Gebruik JavaScript om het geselecteerde voertuig aan uw contactformulier door te geven.", selectVehicle: "Kies een voertuig", selectVehicleType: "Kies voertuigtype", selectMake: "Kies merk", selectModel: "Kies model", selectYear: "Kies jaar / generatie", selectEngine: "Kies motor", searchPlaceholder: "Voertuigen zoeken", noResults: "Geen resultaten", loading: "Laden...", unavailable: "De voertuigselector is tijdelijk niet beschikbaar.", poweredBy: "Mogelijk gemaakt door MG AutoTech", startSubscription: "Start voor 4,99 EUR/maand", monthlyPrice: "per maand", cancelAnytime: "Altijd opzegbaar", easyIntegration: "Eenvoudige script- of iframe-integratie", languagesIncluded: "12 talen inbegrepen", showTuningOptions: "Toon tuningopties", contactSupport: "Support contacteren", manageBilling: "Facturatie beheren", domainLocked: "Domein vergrendeld", domainChangeRequest: "Domeinwijziging aanvragen" }),
  pl: dictionary({ vehicleLookupCodeGenerator: "Generator selektora pojazdów", widgetSettings: "Ustawienia widżetu", themeMode: "Tryb motywu", mainColour: "Kolor główny", buttonTextColour: "Kolor tekstu przycisku", differenceColour: "Kolor wyróżnienia", otherSettings: "Pozostałe ustawienia", language: "Język", enabledLanguages: "Aktywne języki", emailAddressForEnquiries: "E-mail do zapytań", whatsappNumber: "Numer WhatsApp", websiteDomain: "Domena strony", livePreview: "Podgląd na żywo", yourEmbedCodeIs: "Kod osadzania", copy: "Kopiuj", copied: "Skopiowano", subscriptionInactive: "Subskrypcja widżetu jest nieaktywna. Zaktualizuj ją, aby ponownie uruchomić widżet.", manageSubscription: "Zarządzaj subskrypcją", doYouNeedSupport: "Potrzebujesz pomocy?", supportText: "Chętnie pomożemy. Jeśli MG AutoTech ma osadzić widżet, prześlij nam dane swojej strony.", advanced: "Zaawansowane", getVehicleDataOnceSelected: "Pobierz dane wybranego pojazdu", advancedDescription: "Użyj JavaScript, aby przekazać wybrany pojazd do formularza kontaktowego.", selectVehicle: "Wybierz pojazd", selectVehicleType: "Wybierz typ pojazdu", selectMake: "Wybierz markę", selectModel: "Wybierz model", selectYear: "Wybierz rok / generację", selectEngine: "Wybierz silnik", searchPlaceholder: "Szukaj pojazdów", noResults: "Brak wyników", loading: "Ładowanie...", unavailable: "Selektor pojazdów jest chwilowo niedostępny.", poweredBy: "Obsługiwane przez MG AutoTech", startSubscription: "Zacznij za 4,99 EUR/miesiąc", monthlyPrice: "miesięcznie", cancelAnytime: "Anuluj w dowolnym momencie", easyIntegration: "Łatwa integracja przez skrypt lub iframe", languagesIncluded: "12 języków w cenie", showTuningOptions: "Pokaż opcje tuningu", contactSupport: "Skontaktuj się z pomocą", manageBilling: "Zarządzaj płatnościami", domainLocked: "Domena zablokowana", domainChangeRequest: "Poproś o zmianę domeny" }),
  ro: dictionary({ vehicleLookupCodeGenerator: "Generator selector auto", widgetSettings: "Setări widget", themeMode: "Mod temă", mainColour: "Culoare principală", buttonTextColour: "Culoare text buton", differenceColour: "Culoare de accent", otherSettings: "Alte setări", language: "Limbă", enabledLanguages: "Limbi active", emailAddressForEnquiries: "E-mail pentru solicitări", whatsappNumber: "Număr WhatsApp", websiteDomain: "Domeniul site-ului", livePreview: "Previzualizare live", yourEmbedCodeIs: "Codul de integrare", copy: "Copiază", copied: "Copiat", subscriptionInactive: "Abonamentul widgetului este inactiv. Actualizați abonamentul pentru reactivare.", manageSubscription: "Gestionează abonamentul", doYouNeedSupport: "Aveți nevoie de ajutor?", supportText: "Suntem aici pentru a vă ajuta. Dacă doriți ca MG AutoTech să integreze widgetul, trimiteți-ne detaliile site-ului.", advanced: "Avansat", getVehicleDataOnceSelected: "Preluați datele vehiculului selectat", advancedDescription: "Folosiți JavaScript pentru a trimite vehiculul selectat către formularul de contact.", selectVehicle: "Selectați un vehicul", selectVehicleType: "Selectați tipul vehiculului", selectMake: "Selectați marca", selectModel: "Selectați modelul", selectYear: "Selectați anul / generația", selectEngine: "Selectați motorul", searchPlaceholder: "Căutați vehicule", noResults: "Niciun rezultat", loading: "Se încarcă...", unavailable: "Selectorul auto este temporar indisponibil.", poweredBy: "Furnizat de MG AutoTech", startSubscription: "Începeți cu 4,99 EUR/lună", monthlyPrice: "pe lună", cancelAnytime: "Anulați oricând", easyIntegration: "Integrare simplă prin script sau iframe", languagesIncluded: "12 limbi incluse", showTuningOptions: "Afișați opțiunile de tuning", contactSupport: "Contactați asistența", manageBilling: "Gestionați facturarea", domainLocked: "Domeniu blocat", domainChangeRequest: "Solicitați schimbarea domeniului" }),
  pt: dictionary({ vehicleLookupCodeGenerator: "Gerador do seletor de veículos", widgetSettings: "Definições do widget", themeMode: "Modo do tema", mainColour: "Cor principal", buttonTextColour: "Cor do texto do botão", differenceColour: "Cor de destaque", otherSettings: "Outras definições", language: "Idioma", enabledLanguages: "Idiomas ativos", emailAddressForEnquiries: "E-mail para pedidos", whatsappNumber: "Número de WhatsApp", websiteDomain: "Domínio do site", livePreview: "Pré-visualização", yourEmbedCodeIs: "Código de incorporação", copy: "Copiar", copied: "Copiado", subscriptionInactive: "A subscrição do widget está inativa. Atualize-a para reativar o serviço.", manageSubscription: "Gerir subscrição", doYouNeedSupport: "Precisa de ajuda?", supportText: "Estamos disponíveis para ajudar. Se desejar que a MG AutoTech integre o widget, envie-nos os dados do seu site.", advanced: "Avançado", getVehicleDataOnceSelected: "Obter dados do veículo selecionado", advancedDescription: "Use JavaScript para enviar o veículo selecionado para o seu formulário de contacto.", selectVehicle: "Selecionar veículo", selectVehicleType: "Selecionar tipo de veículo", selectMake: "Selecionar marca", selectModel: "Selecionar modelo", selectYear: "Selecionar ano / geração", selectEngine: "Selecionar motor", searchPlaceholder: "Pesquisar veículos", noResults: "Sem resultados", loading: "A carregar...", unavailable: "O seletor de veículos está temporariamente indisponível.", poweredBy: "Fornecido pela MG AutoTech", startSubscription: "Começar por 4,99 EUR/mês", monthlyPrice: "por mês", cancelAnytime: "Cancele a qualquer momento", easyIntegration: "Integração fácil por script ou iframe", languagesIncluded: "12 idiomas incluídos", showTuningOptions: "Mostrar opções de tuning", contactSupport: "Contactar suporte", manageBilling: "Gerir faturação", domainLocked: "Domínio bloqueado", domainChangeRequest: "Pedir alteração de domínio" }),
  ru: dictionary({ vehicleLookupCodeGenerator: "Генератор виджета подбора автомобиля", widgetSettings: "Настройки виджета", themeMode: "Режим темы", mainColour: "Основной цвет", buttonTextColour: "Цвет текста кнопки", differenceColour: "Акцентный цвет", otherSettings: "Другие настройки", language: "Язык", enabledLanguages: "Доступные языки", emailAddressForEnquiries: "E-mail для запросов", whatsappNumber: "Номер WhatsApp", websiteDomain: "Домен сайта", livePreview: "Предпросмотр", yourEmbedCodeIs: "Код для вставки", copy: "Копировать", copied: "Скопировано", subscriptionInactive: "Подписка на виджет неактивна. Обновите подписку, чтобы снова включить виджет.", manageSubscription: "Управление подпиской", doYouNeedSupport: "Нужна помощь?", supportText: "Мы готовы помочь. Если вы хотите, чтобы MG AutoTech установил виджет, отправьте нам данные вашего сайта.", advanced: "Расширенные возможности", getVehicleDataOnceSelected: "Получать данные выбранного автомобиля", advancedDescription: "Используйте JavaScript, чтобы передать выбранный автомобиль в контактную форму.", selectVehicle: "Выберите автомобиль", selectVehicleType: "Выберите тип автомобиля", selectMake: "Выберите марку", selectModel: "Выберите модель", selectYear: "Выберите год / поколение", selectEngine: "Выберите двигатель", searchPlaceholder: "Поиск автомобилей", noResults: "Ничего не найдено", loading: "Загрузка...", unavailable: "Подбор автомобиля временно недоступен.", poweredBy: "Работает на MG AutoTech", startSubscription: "Подключить за 4,99 EUR/месяц", monthlyPrice: "в месяц", cancelAnytime: "Отмена в любое время", easyIntegration: "Простая интеграция через script или iframe", languagesIncluded: "12 языков включено", showTuningOptions: "Показать варианты тюнинга", contactSupport: "Связаться с поддержкой", manageBilling: "Управление оплатой", domainLocked: "Домен закреплён", domainChangeRequest: "Запросить смену домена" }),
  ar: dictionary({ vehicleLookupCodeGenerator: "مولد كود اختيار المركبة", widgetSettings: "إعدادات الأداة", themeMode: "نمط العرض", mainColour: "اللون الرئيسي", buttonTextColour: "لون نص الزر", differenceColour: "لون التمييز", otherSettings: "إعدادات أخرى", language: "اللغة", enabledLanguages: "اللغات المفعلة", emailAddressForEnquiries: "البريد الإلكتروني للاستفسارات", whatsappNumber: "رقم واتساب", websiteDomain: "نطاق الموقع", livePreview: "معاينة مباشرة", yourEmbedCodeIs: "كود التضمين", copy: "نسخ", copied: "تم النسخ", subscriptionInactive: "اشتراك الأداة غير نشط حالياً. حدّث الاشتراك لإعادة تشغيلها.", manageSubscription: "إدارة الاشتراك", doYouNeedSupport: "هل تحتاج إلى دعم؟", supportText: "نحن هنا للمساعدة. إذا أردت من MG AutoTech تضمين الأداة في موقعك، تواصل معنا وأرسل تفاصيل الموقع.", advanced: "متقدم", getVehicleDataOnceSelected: "الحصول على بيانات المركبة بعد اختيارها", advancedDescription: "استخدم JavaScript لنقل بيانات المركبة المختارة إلى نموذج التواصل في موقعك.", selectVehicle: "اختر مركبة", selectVehicleType: "اختر نوع المركبة", selectMake: "اختر الشركة المصنعة", selectModel: "اختر الطراز", selectYear: "اختر السنة / الجيل", selectEngine: "اختر المحرك", searchPlaceholder: "البحث عن مركبة", noResults: "لا توجد نتائج", loading: "جارٍ التحميل...", unavailable: "أداة اختيار المركبة غير متاحة مؤقتاً.", poweredBy: "مقدم من MG AutoTech", startSubscription: "ابدأ مقابل 4.99 EUR شهرياً", monthlyPrice: "شهرياً", cancelAnytime: "يمكن الإلغاء في أي وقت", easyIntegration: "دمج سهل عبر script أو iframe", languagesIncluded: "12 لغة مشمولة", showTuningOptions: "عرض خيارات التعديل", contactSupport: "التواصل مع الدعم", manageBilling: "إدارة الفوترة", domainLocked: "النطاق مقيد", domainChangeRequest: "طلب تغيير النطاق" }),
};

export const widgetVehicleTypeLabels: Record<WidgetLanguage, string> = {
  de: "PKW / Transporter", en: "Car / Light commercial", tr: "Otomobil / Hafif ticari",
  fr: "Voiture / Utilitaire léger", es: "Turismo / Comercial ligero", it: "Auto / Veicolo commerciale leggero",
  nl: "Personenauto / Lichte bedrijfswagen", pl: "Samochód / Lekki pojazd użytkowy",
  ro: "Autoturism / Utilitară ușoară", pt: "Automóvel / Comercial ligeiro",
  ru: "Легковой / Лёгкий коммерческий", ar: "سيارة / مركبة تجارية خفيفة",
};

export type WidgetResultLabels = {
  performance: string;
  stock: string;
  tuned: string;
  gain: string;
  supportedServices: string;
  compatibleEcu: string;
  technicalDataNotice: string;
  power: string;
  torque: string;
  requestOffer: string;
};

export const widgetResultLabels: Record<WidgetLanguage, WidgetResultLabels> = {
  en: { performance: "Performance data", stock: "Stock", tuned: "Tuned", gain: "Gain", supportedServices: "Supported software options", compatibleEcu: "Compatible ECU families", technicalDataNotice: "Reference values from the selected vehicle record. Final availability is confirmed after file identification.", power: "Power", torque: "Torque", requestOffer: "Request an offer" },
  de: { performance: "Leistungsdaten", stock: "Serie", tuned: "Optimiert", gain: "Zuwachs", supportedServices: "Unterstützte Softwareoptionen", compatibleEcu: "Kompatible Steuergeräte", technicalDataNotice: "Referenzwerte aus dem gewählten Fahrzeugdatensatz. Die endgültige Verfügbarkeit wird nach der Dateiidentifikation bestätigt.", power: "Leistung", torque: "Drehmoment", requestOffer: "Angebot anfragen" },
  tr: { performance: "Performans verileri", stock: "Orijinal", tuned: "Yazılımlı", gain: "Kazanç", supportedServices: "Desteklenen yazılım seçenekleri", compatibleEcu: "Uyumlu ECU aileleri", technicalDataNotice: "Değerler seçilen araç kaydına aittir. Kesin uygunluk dosya tanımlamasından sonra onaylanır.", power: "Güç", torque: "Tork", requestOffer: "Teklif iste" },
  fr: { performance: "Données de performance", stock: "Origine", tuned: "Optimisé", gain: "Gain", supportedServices: "Options logicielles prises en charge", compatibleEcu: "Calculateurs compatibles", technicalDataNotice: "Valeurs de référence du véhicule sélectionné. La disponibilité finale est confirmée après identification du fichier.", power: "Puissance", torque: "Couple", requestOffer: "Demander un devis" },
  es: { performance: "Datos de rendimiento", stock: "Serie", tuned: "Optimizado", gain: "Ganancia", supportedServices: "Opciones de software disponibles", compatibleEcu: "ECU compatibles", technicalDataNotice: "Valores de referencia del vehículo seleccionado. La disponibilidad final se confirma tras identificar el archivo.", power: "Potencia", torque: "Par motor", requestOffer: "Solicitar presupuesto" },
  it: { performance: "Dati prestazionali", stock: "Originale", tuned: "Ottimizzato", gain: "Incremento", supportedServices: "Opzioni software supportate", compatibleEcu: "Centraline compatibili", technicalDataNotice: "Valori di riferimento del veicolo selezionato. La disponibilità finale viene confermata dopo l’identificazione del file.", power: "Potenza", torque: "Coppia", requestOffer: "Richiedi un preventivo" },
  nl: { performance: "Prestatiegegevens", stock: "Standaard", tuned: "Geoptimaliseerd", gain: "Winst", supportedServices: "Ondersteunde softwareopties", compatibleEcu: "Compatibele ECU-families", technicalDataNotice: "Referentiewaarden uit het geselecteerde voertuigrecord. Definitieve beschikbaarheid volgt na bestandsidentificatie.", power: "Vermogen", torque: "Koppel", requestOffer: "Offerte aanvragen" },
  pl: { performance: "Dane osiągów", stock: "Seria", tuned: "Po modyfikacji", gain: "Przyrost", supportedServices: "Obsługiwane opcje programowe", compatibleEcu: "Zgodne sterowniki ECU", technicalDataNotice: "Wartości referencyjne dla wybranego pojazdu. Ostateczna dostępność jest potwierdzana po identyfikacji pliku.", power: "Moc", torque: "Moment obrotowy", requestOffer: "Poproś o ofertę" },
  ro: { performance: "Date de performanță", stock: "Standard", tuned: "Optimizat", gain: "Câștig", supportedServices: "Opțiuni software disponibile", compatibleEcu: "Familii ECU compatibile", technicalDataNotice: "Valori de referință pentru vehiculul selectat. Disponibilitatea finală se confirmă după identificarea fișierului.", power: "Putere", torque: "Cuplu", requestOffer: "Solicitați o ofertă" },
  pt: { performance: "Dados de desempenho", stock: "Original", tuned: "Otimizado", gain: "Ganho", supportedServices: "Opções de software suportadas", compatibleEcu: "ECU compatíveis", technicalDataNotice: "Valores de referência do veículo selecionado. A disponibilidade final é confirmada após a identificação do ficheiro.", power: "Potência", torque: "Binário", requestOffer: "Pedir proposta" },
  ru: { performance: "Данные мощности", stock: "Стандарт", tuned: "После настройки", gain: "Прирост", supportedServices: "Поддерживаемые программные опции", compatibleEcu: "Совместимые блоки ECU", technicalDataNotice: "Справочные значения выбранного автомобиля. Окончательная доступность подтверждается после идентификации файла.", power: "Мощность", torque: "Крутящий момент", requestOffer: "Запросить предложение" },
  ar: { performance: "بيانات الأداء", stock: "قياسي", tuned: "بعد التعديل", gain: "الزيادة", supportedServices: "خيارات البرمجة المدعومة", compatibleEcu: "وحدات ECU المتوافقة", technicalDataNotice: "قيم مرجعية لسجل المركبة المختارة. يتم تأكيد التوفر النهائي بعد تحديد ملف المركبة.", power: "القوة", torque: "عزم الدوران", requestOffer: "طلب عرض" },
};

export type WidgetEnquiryLabels = {
  contactChannels: string;
  contactDescription: string;
  enableEmail: string;
  enableWhatsapp: string;
  chooseContact: string;
  continueByEmail: string;
  continueByWhatsapp: string;
  name: string;
  emailAddress: string;
  phone: string;
  location: string;
  vehicleRegistration: string;
  additionalInformation: string;
  sendEnquiry: string;
  sending: string;
  enquirySent: string;
  enquiryFailed: string;
  requiredNote: string;
};

export const widgetEnquiryLabels: Record<WidgetLanguage, WidgetEnquiryLabels> = {
  en: { contactChannels: "Contact channels", contactDescription: "Choose how visitors can contact your business from the widget.", enableEmail: "Email enquiry form", enableWhatsapp: "WhatsApp enquiries", chooseContact: "How would you like to continue?", continueByEmail: "Send by email", continueByWhatsapp: "Continue on WhatsApp", name: "Name", emailAddress: "Email address", phone: "Phone number", location: "Location", vehicleRegistration: "Vehicle registration", additionalInformation: "Additional information or requirements", sendEnquiry: "Send enquiry", sending: "Sending...", enquirySent: "Your enquiry was sent successfully.", enquiryFailed: "The enquiry could not be sent. Please try again.", requiredNote: "Name and email address are required." },
  de: { contactChannels: "Kontaktkanäle", contactDescription: "Legen Sie fest, wie Besucher Sie über das Widget kontaktieren können.", enableEmail: "Anfrageformular per E-Mail", enableWhatsapp: "Anfragen über WhatsApp", chooseContact: "Wie möchten Sie fortfahren?", continueByEmail: "Per E-Mail senden", continueByWhatsapp: "Über WhatsApp fortfahren", name: "Name", emailAddress: "E-Mail-Adresse", phone: "Telefonnummer", location: "Standort", vehicleRegistration: "Fahrzeugkennzeichen", additionalInformation: "Zusätzliche Informationen oder Anforderungen", sendEnquiry: "Anfrage senden", sending: "Wird gesendet...", enquirySent: "Ihre Anfrage wurde erfolgreich gesendet.", enquiryFailed: "Die Anfrage konnte nicht gesendet werden. Bitte versuchen Sie es erneut.", requiredNote: "Name und E-Mail-Adresse sind Pflichtfelder." },
  tr: { contactChannels: "İletişim kanalları", contactDescription: "Ziyaretçilerin widget üzerinden işletmenize nasıl ulaşacağını seçin.", enableEmail: "E-posta teklif formu", enableWhatsapp: "WhatsApp talepleri", chooseContact: "Nasıl devam etmek istersiniz?", continueByEmail: "E-posta ile gönder", continueByWhatsapp: "WhatsApp ile devam et", name: "Ad soyad", emailAddress: "E-posta adresi", phone: "Telefon numarası", location: "Konum", vehicleRegistration: "Araç plakası", additionalInformation: "Ek bilgi veya talepler", sendEnquiry: "Talebi gönder", sending: "Gönderiliyor...", enquirySent: "Talebiniz başarıyla gönderildi.", enquiryFailed: "Talep gönderilemedi. Lütfen tekrar deneyin.", requiredNote: "Ad soyad ve e-posta adresi zorunludur." },
  fr: { contactChannels: "Canaux de contact", contactDescription: "Choisissez comment les visiteurs peuvent contacter votre entreprise depuis le widget.", enableEmail: "Formulaire de demande par e-mail", enableWhatsapp: "Demandes via WhatsApp", chooseContact: "Comment souhaitez-vous continuer ?", continueByEmail: "Envoyer par e-mail", continueByWhatsapp: "Continuer sur WhatsApp", name: "Nom", emailAddress: "Adresse e-mail", phone: "Numéro de téléphone", location: "Localisation", vehicleRegistration: "Immatriculation du véhicule", additionalInformation: "Informations ou demandes complémentaires", sendEnquiry: "Envoyer la demande", sending: "Envoi en cours...", enquirySent: "Votre demande a bien été envoyée.", enquiryFailed: "La demande n’a pas pu être envoyée. Veuillez réessayer.", requiredNote: "Le nom et l’adresse e-mail sont obligatoires." },
  es: { contactChannels: "Canales de contacto", contactDescription: "Elige cómo pueden contactar los visitantes con tu empresa desde el widget.", enableEmail: "Formulario de consulta por correo", enableWhatsapp: "Consultas por WhatsApp", chooseContact: "¿Cómo desea continuar?", continueByEmail: "Enviar por correo", continueByWhatsapp: "Continuar por WhatsApp", name: "Nombre", emailAddress: "Correo electrónico", phone: "Número de teléfono", location: "Ubicación", vehicleRegistration: "Matrícula del vehículo", additionalInformation: "Información o requisitos adicionales", sendEnquiry: "Enviar consulta", sending: "Enviando...", enquirySent: "Su consulta se ha enviado correctamente.", enquiryFailed: "No se pudo enviar la consulta. Inténtelo de nuevo.", requiredNote: "El nombre y el correo electrónico son obligatorios." },
  it: { contactChannels: "Canali di contatto", contactDescription: "Scegli come i visitatori possono contattare la tua attività dal widget.", enableEmail: "Modulo di richiesta via e-mail", enableWhatsapp: "Richieste via WhatsApp", chooseContact: "Come desideri continuare?", continueByEmail: "Invia via e-mail", continueByWhatsapp: "Continua su WhatsApp", name: "Nome", emailAddress: "Indirizzo e-mail", phone: "Numero di telefono", location: "Località", vehicleRegistration: "Targa del veicolo", additionalInformation: "Informazioni o richieste aggiuntive", sendEnquiry: "Invia richiesta", sending: "Invio in corso...", enquirySent: "La richiesta è stata inviata correttamente.", enquiryFailed: "Impossibile inviare la richiesta. Riprova.", requiredNote: "Nome e indirizzo e-mail sono obbligatori." },
  nl: { contactChannels: "Contactkanalen", contactDescription: "Kies hoe bezoekers via de widget contact met uw bedrijf kunnen opnemen.", enableEmail: "Aanvraagformulier per e-mail", enableWhatsapp: "Aanvragen via WhatsApp", chooseContact: "Hoe wilt u verdergaan?", continueByEmail: "Per e-mail verzenden", continueByWhatsapp: "Doorgaan via WhatsApp", name: "Naam", emailAddress: "E-mailadres", phone: "Telefoonnummer", location: "Locatie", vehicleRegistration: "Kenteken", additionalInformation: "Aanvullende informatie of wensen", sendEnquiry: "Aanvraag verzenden", sending: "Wordt verzonden...", enquirySent: "Uw aanvraag is succesvol verzonden.", enquiryFailed: "De aanvraag kon niet worden verzonden. Probeer het opnieuw.", requiredNote: "Naam en e-mailadres zijn verplicht." },
  pl: { contactChannels: "Kanały kontaktu", contactDescription: "Wybierz, w jaki sposób odwiedzający mogą kontaktować się z firmą przez widżet.", enableEmail: "Formularz zapytania e-mail", enableWhatsapp: "Zapytania przez WhatsApp", chooseContact: "Jak chcesz kontynuować?", continueByEmail: "Wyślij e-mailem", continueByWhatsapp: "Kontynuuj w WhatsApp", name: "Imię i nazwisko", emailAddress: "Adres e-mail", phone: "Numer telefonu", location: "Lokalizacja", vehicleRegistration: "Numer rejestracyjny", additionalInformation: "Dodatkowe informacje lub wymagania", sendEnquiry: "Wyślij zapytanie", sending: "Wysyłanie...", enquirySent: "Zapytanie zostało wysłane pomyślnie.", enquiryFailed: "Nie udało się wysłać zapytania. Spróbuj ponownie.", requiredNote: "Imię i adres e-mail są wymagane." },
  ro: { contactChannels: "Canale de contact", contactDescription: "Alegeți cum pot vizitatorii să contacteze compania prin widget.", enableEmail: "Formular de solicitare prin e-mail", enableWhatsapp: "Solicitări prin WhatsApp", chooseContact: "Cum doriți să continuați?", continueByEmail: "Trimiteți prin e-mail", continueByWhatsapp: "Continuați pe WhatsApp", name: "Nume", emailAddress: "Adresă de e-mail", phone: "Număr de telefon", location: "Localitate", vehicleRegistration: "Număr de înmatriculare", additionalInformation: "Informații sau cerințe suplimentare", sendEnquiry: "Trimiteți solicitarea", sending: "Se trimite...", enquirySent: "Solicitarea a fost trimisă cu succes.", enquiryFailed: "Solicitarea nu a putut fi trimisă. Încercați din nou.", requiredNote: "Numele și adresa de e-mail sunt obligatorii." },
  pt: { contactChannels: "Canais de contacto", contactDescription: "Escolha como os visitantes podem contactar a sua empresa através do widget.", enableEmail: "Formulário de pedido por e-mail", enableWhatsapp: "Pedidos por WhatsApp", chooseContact: "Como pretende continuar?", continueByEmail: "Enviar por e-mail", continueByWhatsapp: "Continuar no WhatsApp", name: "Nome", emailAddress: "Endereço de e-mail", phone: "Número de telefone", location: "Localização", vehicleRegistration: "Matrícula do veículo", additionalInformation: "Informações ou requisitos adicionais", sendEnquiry: "Enviar pedido", sending: "A enviar...", enquirySent: "O pedido foi enviado com sucesso.", enquiryFailed: "Não foi possível enviar o pedido. Tente novamente.", requiredNote: "O nome e o endereço de e-mail são obrigatórios." },
  ru: { contactChannels: "Каналы связи", contactDescription: "Выберите, как посетители смогут связаться с вашей компанией через виджет.", enableEmail: "Форма заявки по электронной почте", enableWhatsapp: "Заявки через WhatsApp", chooseContact: "Как вы хотите продолжить?", continueByEmail: "Отправить по электронной почте", continueByWhatsapp: "Продолжить в WhatsApp", name: "Имя", emailAddress: "Электронная почта", phone: "Номер телефона", location: "Местоположение", vehicleRegistration: "Регистрационный номер", additionalInformation: "Дополнительная информация или требования", sendEnquiry: "Отправить заявку", sending: "Отправка...", enquirySent: "Ваша заявка успешно отправлена.", enquiryFailed: "Не удалось отправить заявку. Повторите попытку.", requiredNote: "Имя и электронная почта обязательны." },
  ar: { contactChannels: "قنوات التواصل", contactDescription: "اختر كيف يمكن للزوار التواصل مع نشاطك من خلال الأداة.", enableEmail: "نموذج طلب عبر البريد الإلكتروني", enableWhatsapp: "طلبات عبر واتساب", chooseContact: "كيف تريد المتابعة؟", continueByEmail: "إرسال عبر البريد الإلكتروني", continueByWhatsapp: "المتابعة عبر واتساب", name: "الاسم", emailAddress: "البريد الإلكتروني", phone: "رقم الهاتف", location: "الموقع", vehicleRegistration: "رقم تسجيل المركبة", additionalInformation: "معلومات أو متطلبات إضافية", sendEnquiry: "إرسال الطلب", sending: "جارٍ الإرسال...", enquirySent: "تم إرسال طلبك بنجاح.", enquiryFailed: "تعذر إرسال الطلب. يرجى المحاولة مرة أخرى.", requiredNote: "الاسم والبريد الإلكتروني مطلوبان." },
};

export function normalizeWidgetLanguage(value: unknown, fallback: WidgetLanguage = "en") {
  const code = typeof value === "string" ? value.toLowerCase().split(/[-_]/)[0] : "";
  return isWidgetLanguage(code) ? code : fallback;
}

export function widgetT(language: WidgetLanguage, key: WidgetTranslationKey) {
  return widgetTranslations[language]?.[key] ?? widgetTranslations.en[key] ?? key;
}
